#!/usr/bin/env python3
"""Expand cognates.json with 50 new concepts."""
import json, os

PATH = os.path.join(os.path.dirname(__file__), "..", "data", "clusters", "cognates.json")

def T(ru, uk, be, sk, cs, pl, sl, hr, bg, mk, it, es, pt, fr, ro, zh, ja, ko, vi, hu, fi, et_):
    """Build translations dict. Each arg is a dict for that language."""
    return {"ru": ru, "uk": uk, "be": be, "sk": sk, "cs": cs, "pl": pl,
            "sl": sl, "hr": hr, "bg": bg, "mk": mk, "it": it, "es": es,
            "pt": pt, "fr": fr, "ro": ro, "zh": zh, "ja": ja, "ko": ko,
            "vi": vi, "hu": hu, "fi": fi, "et": et_}

def C(id, de, en, cat, rank, trans, etym, hint):
    """Build a concept entry."""
    return {"id": id, "de": de, "en": en, "category": cat, "frequency_rank": rank,
            "translations": trans, "etymology_note": etym, "mnemonic_hint": hint}

# Shorthand helpers for translation entries
def r(w, rom, **kw):
    """Cyrillic/CJK entry with romanization."""
    d = {"word": w, "romanization": rom}
    d.update(kw)
    return d

def l(w, **kw):
    """Latin-script entry."""
    d = {"word": w}
    d.update(kw)
    return d

def s(w, sim, **kw):
    """Latin-script entry with similarity."""
    d = {"word": w, "similarity_to": sim}
    d.update(kw)
    return d

def rs(w, rom, sim, **kw):
    """Cyrillic entry with romanization and similarity."""
    d = {"word": w, "romanization": rom, "similarity_to": sim}
    d.update(kw)
    return d

NEW = [
    # ===== GROUP 1: 10 nouns =====
    C("milk", "Milch", "milk", "nomen", 350,
      T(r("молоко", "moloko"), rs("молоко", "moloko", {"ru": 1.0}), rs("малако", "malako", {"ru": 0.8}),
        s("mlieko", {"cs": 0.9}), s("mléko", {"sk": 0.9}), s("mleko", {"cs": 0.9, "sk": 0.8}),
        s("mleko", {"hr": 1.0, "pl": 1.0}), s("mlijeko", {"sl": 0.8}),
        rs("мляко", "mlyako", {"mk": 0.9}), rs("млеко", "mleko", {"bg": 0.9}),
        l("latte"), s("leche", {"pt": 0.7}), s("leite", {"es": 0.7}),
        s("lait", {"it": 0.6}), s("lapte", {"it": 0.6}),
        r("牛奶", "niúnǎi"), r("牛乳", "gyūnyū"), r("우유", "uyu"),
        l("sữa"), l("tej"), s("maito", {"et": 0.5}), l("piim")),
      "Proto-Slavic *melko, Latein lac/lactis", "Moloko wie in 'A Clockwork Orange' – Milch!"),

    C("school", "Schule", "school", "nomen", 140,
      T(r("школа", "shkola"), rs("школа", "shkola", {"ru": 1.0}), rs("школа", "shkola", {"ru": 1.0}),
        s("škola", {"cs": 1.0}), s("škola", {"sk": 1.0}), s("szkoła", {"cs": 0.8}),
        s("šola", {"hr": 0.7}), s("škola", {"sl": 0.8, "cs": 1.0}),
        rs("училище", "uchilishte", {"mk": 0.5}), rs("училиште", "uchilishte", {"bg": 0.9}),
        l("scuola"), s("escuela", {"pt": 0.8}), s("escola", {"es": 0.8}),
        s("école", {"it": 0.6}), s("școală", {"it": 0.7}),
        r("学校", "xuéxiào"), r("学校", "gakkō"), r("학교", "hakgyo"),
        l("trường"), l("iskola"), s("koulu", {"et": 0.6}), l("kool")),
      "Griech. scholē > Latein schola > alle europäischen Sprachen", "Shkola klingt wie 'Schule' – fast gleich!"),

    C("city", "Stadt", "city", "nomen", 160,
      T(r("город", "gorod"), rs("місто", "misto", {}), rs("горад", "horad", {"ru": 0.8}),
        s("mesto", {"cs": 1.0, "sl": 0.9}), s("město", {"sk": 1.0}), s("miasto", {"cs": 0.8}),
        s("mesto", {"cs": 1.0, "sk": 1.0}), s("grad", {"sl": 0.5}),
        rs("град", "grad", {"mk": 1.0}), rs("град", "grad", {"bg": 1.0}),
        s("città", {"es": 0.6}), s("ciudad", {"pt": 0.8}), s("cidade", {"es": 0.8}),
        s("cité", {"it": 0.7}), s("oraș", {}),
        r("城市", "chéngshì"), r("都市", "toshi"), r("도시", "dosi"),
        l("thành phố"), l("város"), s("kaupunki", {"et": 0.3}), l("linn")),
      "Proto-Slavic *gordŭ (Zaun/Burg), Latein civitas", "Gorod wie 'Grad' – Belgrad = weiße Stadt!"),

    C("road", "Straße", "road", "nomen", 180,
      T(r("дорога", "doroga"), rs("дорога", "doroha", {"ru": 0.9}), rs("дарога", "daroha", {"ru": 0.8}),
        s("cesta", {"cs": 1.0}), s("cesta", {"sk": 1.0}), s("droga", {"ru": 0.6}),
        s("cesta", {"hr": 1.0, "cs": 1.0}), s("cesta", {"sl": 1.0}),
        rs("път", "pat", {"mk": 0.8}), rs("пат", "pat", {"bg": 0.8}),
        l("strada"), s("camino", {"pt": 0.7}), s("caminho", {"es": 0.7}),
        s("route", {"ro": 0.5}), s("drum", {}),
        r("道路", "dàolù"), r("道", "michi"), r("길", "gil"),
        l("đường"), l("út"), s("tie", {"et": 0.7}), l("tee")),
      "Proto-Slavic *dorga, Latein strata (> it. strada)", "Doroga – 'der Oga' geht seinen Weg, seine Straße!"),

    C("king", "König", "king", "nomen", 280,
      T(r("король", "korol"), rs("король", "korol", {"ru": 1.0}), rs("кароль", "karol", {"ru": 0.9}),
        s("kráľ", {"cs": 0.9}), s("král", {"sk": 0.9}), s("król", {"cs": 0.8}),
        s("kralj", {"hr": 1.0}), s("kralj", {"sl": 1.0}),
        rs("крал", "kral", {"mk": 0.9}), rs("крал", "kral", {"bg": 1.0}),
        l("re"), s("rey", {"pt": 0.8}), s("rei", {"es": 0.8}),
        s("roi", {"it": 0.6}), s("rege", {"it": 0.6}),
        r("国王", "guówáng"), r("王", "ō"), r("왕", "wang"),
        l("vua"), s("király", {}), s("kuningas", {"et": 0.8}), l("kuningas")),
      "Proto-Slavic *korlĭ (von Karl dem Großen!), Latein rex", "Korol kommt von Karl dem Großen – der König aller Könige!"),

    C("heart", "Herz", "heart", "nomen", 220,
      T(r("сердце", "serdtse"), rs("серце", "sertse", {"ru": 0.9}), rs("сэрца", "sertsa", {"ru": 0.8}),
        s("srdce", {"cs": 1.0}), s("srdce", {"sk": 1.0}), s("serce", {"cs": 0.8}),
        s("srce", {"hr": 1.0}), s("srce", {"sl": 1.0}),
        rs("сърце", "sartse", {"mk": 0.8}), rs("срце", "srtse", {"bg": 0.8}),
        s("cuore", {"es": 0.6}), s("corazón", {"pt": 0.7}), s("coração", {"es": 0.7}),
        s("cœur", {"it": 0.6}), s("inimă", {}),
        r("心", "xīn"), r("心", "kokoro"), r("마음", "maeum"),
        l("trái tim"), l("szív"), s("sydän", {"et": 0.6}), l("süda")),
      "Proto-Slavic *sьrdьce, Latein cor/cordis, PIE *ḱḗr", "Serdtse – wie 'Scherz' mit -tse: Das Herz liebt Scherze!"),

    C("horse", "Pferd", "horse", "nomen", 400,
      T(r("лошадь", "loshad"), rs("кінь", "kin", {}), rs("конь", "kon", {"ru": 0.5}),
        s("kôň", {"cs": 0.9}), s("kůň", {"sk": 0.9}), s("koń", {"cs": 0.8}),
        s("konj", {"hr": 1.0}), s("konj", {"sl": 1.0}),
        rs("кон", "kon", {"mk": 1.0}), rs("коњ", "konj", {"bg": 0.9}),
        l("cavallo"), s("caballo", {"pt": 0.8}), s("cavalo", {"es": 0.8}),
        s("cheval", {"it": 0.6}), s("cal", {}),
        r("马", "mǎ"), r("馬", "uma"), r("말", "mal"),
        l("ngựa"), l("ló"), s("hevonen", {"et": 0.4}), l("hobune")),
      "Proto-Slavic *konjĭ, Latein caballus", "Loshad – 'Losch-ab!': Das Pferd galoppiert los!"),

    C("bird", "Vogel", "bird", "nomen", 370,
      T(r("птица", "ptitsa"), rs("птах", "ptakh", {"ru": 0.7}), rs("птушка", "ptushka", {"ru": 0.7}),
        s("vták", {"cs": 0.9}), s("pták", {"sk": 0.9}), s("ptak", {"cs": 0.9}),
        s("ptič", {"hr": 0.7}), s("ptica", {"sl": 0.7}),
        rs("птица", "ptitsa", {"ru": 1.0, "mk": 0.9}), rs("птица", "ptitsa", {"bg": 1.0, "ru": 1.0}),
        l("uccello"), s("pájaro", {"pt": 0.6}), s("pássaro", {"es": 0.6}),
        s("oiseau", {"ro": 0.5}), s("pasăre", {"pt": 0.5}),
        r("鸟", "niǎo"), r("鳥", "tori"), r("새", "sae"),
        l("chim"), l("madár"), s("lintu", {"et": 0.4}), l("lind")),
      "Proto-Slavic *pŭtica, Latein avis > fr. oiseau", "Ptitsa – denk an 'Pizza mit Vogel' – Pt-itsa!"),

    C("flower", "Blume", "flower", "nomen", 420,
      T(r("цветок", "tsvetok"), rs("квітка", "kvitka", {"ru": 0.5}), rs("кветка", "kvetka", {"uk": 0.9}),
        s("kvet", {"cs": 1.0}), s("květ", {"sk": 1.0}), s("kwiat", {"cs": 0.7}),
        s("cvet", {"hr": 0.9}), s("cvijet", {"sl": 0.8}),
        rs("цвете", "tsvete", {"mk": 0.9}), rs("цвет", "tsvet", {"bg": 0.9}),
        s("fiore", {"es": 0.7}), s("flor", {"pt": 1.0}), s("flor", {"es": 1.0}),
        s("fleur", {"it": 0.6}), s("floare", {"fr": 0.7}),
        r("花", "huā"), r("花", "hana"), r("꽃", "kkot"),
        l("hoa"), l("virág"), s("kukka", {"et": 0.4}), l("lill")),
      "Proto-Slavic *květŭ, Latein flos/floris", "Tsvetok – wie 'Zwetschge' mit Blüte: Die Blume blüht!"),

    C("snow", "Schnee", "snow", "nomen", 380,
      T(r("снег", "sneg"), rs("сніг", "snih", {"ru": 0.9}), rs("снег", "sneh", {"ru": 1.0}),
        s("sneh", {"cs": 0.9}), s("sníh", {"sk": 0.9}), s("śnieg", {"cs": 0.8}),
        s("sneg", {"hr": 1.0}), s("snijeg", {"sl": 0.8}),
        rs("сняг", "snyag", {"mk": 0.8}), rs("снег", "sneg", {"ru": 1.0, "bg": 0.8}),
        l("neve"), s("nieve", {"pt": 0.7}), s("neve", {"it": 1.0}),
        s("neige", {"it": 0.7}), s("nea", {"it": 0.5}),
        r("雪", "xuě"), r("雪", "yuki"), r("눈", "nun"),
        l("tuyết"), l("hó"), s("lumi", {"et": 0.7}), l("lumi")),
      "Proto-Slavic *sněgŭ, Latein nix/nivis, PIE *snóygʷʰos", "Sneg klingt wie 'Schnee-g' – Schnee auf Russisch!"),

    # ===== GROUP 2: 10 nouns =====
    C("rain", "Regen", "rain", "nomen", 390,
      T(r("дождь", "dozhd"), rs("дощ", "doshch", {"ru": 0.8}), rs("дождж", "dozhdzh", {"ru": 0.9}),
        s("dážď", {"cs": 0.9}), s("déšť", {"sk": 0.9}), s("deszcz", {"cs": 0.7}),
        s("dež", {"hr": 0.8}), s("kiša", {}),
        rs("дъжд", "dazhd", {"mk": 0.8}), rs("дожд", "dozhd", {"bg": 0.9, "ru": 0.9}),
        s("pioggia", {"es": 0.5}), s("lluvia", {"pt": 0.6}), s("chuva", {}),
        s("pluie", {"it": 0.5, "ro": 0.7}), s("ploaie", {"fr": 0.7}),
        r("雨", "yǔ"), r("雨", "ame"), r("비", "bi"),
        l("mưa"), l("eső"), s("sade", {"et": 0.5}), l("vihm")),
      "Proto-Slavic *dъždĭ, Latein pluvia", "Dozhd – wie 'Dosch(e)' – der Regen macht alles nass!"),

    C("wind", "Wind", "wind", "nomen", 360,
      T(r("ветер", "veter"), rs("вітер", "viter", {"ru": 0.9}), rs("вецер", "vetser", {"ru": 0.8}),
        s("vietor", {"cs": 0.8}), s("vítr", {"sk": 0.8}), s("wiatr", {"cs": 0.7}),
        s("veter", {"hr": 0.9}), s("vjetar", {"sl": 0.8}),
        rs("вятър", "vyatar", {"mk": 0.8}), rs("ветер", "veter", {"ru": 1.0, "bg": 0.8}),
        s("vento", {"es": 0.9, "pt": 1.0}), s("viento", {"it": 0.8, "pt": 0.8}),
        s("vento", {"it": 1.0, "es": 0.8}),
        s("vent", {"it": 0.9}), s("vânt", {"it": 0.7}),
        r("风", "fēng"), r("風", "kaze"), r("바람", "baram"),
        l("gió"), l("szél"), s("tuuli", {"et": 0.7}), l("tuul")),
      "Proto-Slavic *větrŭ, Latein ventus, PIE *h₂wéh₁ntos", "Veter klingt wie 'Wetter' – Wind bestimmt das Wetter!"),

    C("river", "Fluss", "river", "nomen", 300,
      T(r("река", "reka"), rs("ріка", "rika", {"ru": 0.9}), rs("рака", "raka", {"ru": 0.8}),
        s("rieka", {"cs": 0.9}), s("řeka", {"sk": 0.9}), s("rzeka", {"cs": 0.7}),
        s("reka", {"hr": 1.0}), s("rijeka", {"sl": 0.8}),
        rs("река", "reka", {"ru": 1.0, "mk": 1.0}), rs("река", "reka", {"bg": 1.0, "ru": 1.0}),
        s("fiume", {}), s("río", {"pt": 0.8}), s("rio", {"es": 0.8}),
        s("rivière", {"ro": 0.5}), s("râu", {}),
        r("河", "hé"), r("川", "kawa"), r("강", "gang"),
        l("sông"), l("folyó"), s("joki", {"et": 0.5}), l("jõgi")),
      "Proto-Slavic *rěka, Latein rivus", "Reka – wie 'Rekord': Der Fluss bricht Rekorde an Länge!"),

    C("mountain", "Berg", "mountain", "nomen", 310,
      T(r("гора", "gora"), rs("гора", "hora", {"ru": 0.9}), rs("гара", "hara", {"ru": 0.8}),
        s("hora", {"cs": 1.0}), s("hora", {"sk": 1.0}), s("góra", {"cs": 0.8}),
        s("gora", {"hr": 1.0}), s("gora", {"sl": 1.0}),
        rs("планина", "planina", {"mk": 1.0}), rs("планина", "planina", {"bg": 1.0}),
        s("montagna", {"es": 0.7, "fr": 0.7}), s("montaña", {"it": 0.7, "pt": 0.8}),
        s("montanha", {"es": 0.8}),
        s("montagne", {"it": 0.7}), s("munte", {}),
        r("山", "shān"), r("山", "yama"), r("산", "san"),
        l("núi"), l("hegy"), s("vuori", {"et": 0.4}), l("mägi")),
      "Proto-Slavic *gora, Latein mons/montis", "Gora – wie 'Gora!' (Hurra) – man ruft es vom Berg herab!"),

    C("sea", "Meer", "sea", "nomen", 250,
      T(r("море", "more"), rs("море", "more", {"ru": 1.0}), rs("мора", "mora", {"ru": 0.9}),
        s("more", {"cs": 1.0}), s("moře", {"sk": 1.0}), s("morze", {"cs": 0.8}),
        s("morje", {"hr": 0.9}), s("more", {"sl": 0.9, "cs": 1.0}),
        rs("море", "more", {"ru": 1.0, "mk": 1.0}), rs("море", "more", {"bg": 1.0}),
        s("mare", {"es": 0.7, "ro": 0.9}), s("mar", {"it": 0.7, "pt": 1.0}),
        s("mar", {"es": 1.0}),
        s("mer", {"it": 0.7}), s("mare", {"it": 0.9}),
        r("海", "hǎi"), r("海", "umi"), r("바다", "bada"),
        l("biển"), l("tenger"), s("meri", {"et": 0.7}), l("meri")),
      "Proto-Slavic *morje, Latein mare, PIE *móri", "More wie 'Morgen am Meer' – more = Meer!"),

    C("brother", "Bruder", "brother", "nomen", 260,
      T(r("брат", "brat"), rs("брат", "brat", {"ru": 1.0}), rs("брат", "brat", {"ru": 1.0}),
        s("brat", {"cs": 1.0, "pl": 1.0}), s("bratr", {"sk": 0.9}), s("brat", {"cs": 1.0, "sk": 0.9}),
        s("brat", {"hr": 1.0, "cs": 1.0}), s("brat", {"sl": 1.0}),
        rs("брат", "brat", {"ru": 1.0, "mk": 1.0}), rs("брат", "brat", {"bg": 1.0}),
        s("fratello", {"es": 0.6}), s("hermano", {"pt": 0.7}), s("irmão", {"es": 0.7}),
        s("frère", {"it": 0.6}), s("frate", {"it": 0.7, "fr": 0.7}),
        r("兄弟", "xiōngdì"), r("兄弟", "kyōdai"), r("형제", "hyeongje"),
        l("anh em"), l("fivér"), s("veli", {"et": 0.5}), l("vend")),
      "Proto-Slavic *bratrŭ, Latein frater, PIE *bʰréh₂tēr", "Brat – wie 'Braten': Mit dem Bruder isst man den Braten!"),

    C("sister", "Schwester", "sister", "nomen", 270,
      T(r("сестра", "sestra"), rs("сестра", "sestra", {"ru": 1.0}), rs("сястра", "syastra", {"ru": 0.9}),
        s("sestra", {"cs": 1.0, "pl": 0.9}), s("sestra", {"sk": 1.0}), s("siostra", {"cs": 0.8}),
        s("sestra", {"hr": 1.0, "cs": 1.0}), s("sestra", {"sl": 1.0}),
        rs("сестра", "sestra", {"ru": 1.0, "mk": 1.0}), rs("сестра", "sestra", {"bg": 1.0}),
        s("sorella", {"es": 0.5}), s("hermana", {"pt": 0.7}), s("irmã", {"es": 0.7}),
        s("sœur", {"it": 0.5}), s("soră", {"it": 0.6, "fr": 0.6}),
        r("姐妹", "jiěmèi"), r("姉妹", "shimai"), r("자매", "jamae"),
        l("chị em"), l("nővér"), s("sisko", {"et": 0.4}), l("õde")),
      "Proto-Slavic *sestra, Latein soror, PIE *swésōr", "Sestra klingt wie 'Schwester' – fast gleich!"),

    C("son", "Sohn", "son", "nomen", 240,
      T(r("сын", "syn"), rs("син", "syn", {"ru": 0.9}), rs("сын", "syn", {"ru": 1.0}),
        s("syn", {"cs": 1.0, "pl": 1.0}), s("syn", {"sk": 1.0}), s("syn", {"cs": 1.0, "sk": 1.0}),
        s("sin", {"hr": 1.0}), s("sin", {"sl": 1.0}),
        rs("син", "sin", {"mk": 1.0}), rs("син", "sin", {"bg": 1.0}),
        s("figlio", {"es": 0.5}), s("hijo", {"pt": 0.6}), s("filho", {"es": 0.6}),
        s("fils", {"it": 0.5}), s("fiu", {}),
        r("儿子", "érzi"), r("息子", "musuko"), r("아들", "adeul"),
        l("con trai"), l("fiú"), s("poika", {"et": 0.4}), l("poeg")),
      "Proto-Slavic *synŭ, Latein filius, PIE *suHnús", "Syn klingt wie 'Sohn' – fast identisch!"),

    C("daughter", "Tochter", "daughter", "nomen", 245,
      T(r("дочь", "doch"), rs("дочка", "dochka", {"ru": 0.9}), rs("дачка", "dachka", {"ru": 0.8}),
        s("dcéra", {"cs": 0.8}), s("dcera", {"sk": 0.8}), s("córka", {}),
        s("hči", {}), s("kći", {}),
        rs("дъщеря", "dashterya", {"mk": 0.7}), rs("ќерка", "kjerka", {}),
        s("figlia", {"es": 0.6}), s("hija", {"pt": 0.6}), s("filha", {"es": 0.6}),
        s("fille", {"it": 0.6}), s("fiică", {"it": 0.5}),
        r("女儿", "nǚér"), r("娘", "musume"), r("딸", "ttal"),
        l("con gái"), l("lány"), s("tytär", {"et": 0.6}), l("tütar")),
      "Proto-Slavic *dъkti, Latein filia, PIE *dʰugh₂tḗr", "Doch – wie 'doch': Die Tochter sagt doch immer 'doch!'"),

    C("friend", "Freund", "friend", "nomen", 190,
      T(r("друг", "drug"), rs("друг", "druh", {"ru": 0.9}), rs("сябар", "syabar", {}),
        s("priateľ", {"cs": 0.9}), s("přítel", {"sk": 0.9}), s("przyjaciel", {"cs": 0.6}),
        s("prijatelj", {"hr": 1.0}), s("prijatelj", {"sl": 1.0}),
        rs("приятел", "priyatel", {"mk": 0.9}), rs("пријател", "prijatel", {"bg": 0.9}),
        s("amico", {"es": 0.8}), s("amigo", {"pt": 1.0}), s("amigo", {"es": 1.0}),
        s("ami", {"it": 0.7}), s("prieten", {"cs": 0.5}),
        r("朋友", "péngyou"), r("友達", "tomodachi"), r("친구", "chingu"),
        l("bạn"), l("barát"), s("ystävä", {"et": 0.4}), l("sõber")),
      "Proto-Slavic *drugŭ (der andere), Latein amicus", "Drug – wie 'Drücken': Einen Freund drückt man fest!"),

    # ===== GROUP 3: 15 verbs =====
    C("eat", "essen", "to eat", "verb", 170,
      T(r("есть", "yest"), rs("їсти", "yisty", {"ru": 0.8}), rs("есці", "yestsi", {"ru": 0.9}),
        s("jesť", {"cs": 0.9}), s("jíst", {"sk": 0.9}), s("jeść", {"cs": 0.8}),
        s("jesti", {"hr": 1.0}), s("jesti", {"sl": 1.0}),
        rs("ям", "yam", {"mk": 0.7}), rs("јадам", "jadam", {}),
        s("mangiare", {}), s("comer", {"pt": 1.0}), s("comer", {"es": 1.0}),
        s("manger", {"it": 0.5}), s("a mânca", {"fr": 0.5}),
        r("吃", "chī"), r("食べる", "taberu"), r("먹다", "meokda"),
        l("ăn"), l("enni"), s("syödä", {"et": 0.5}), l("sööma")),
      "Proto-Slavic *ěsti, Latein edere, PIE *h₁édti", "Yest – wie 'Jetzt ess ich!' – yest = essen!"),

    C("drink", "trinken", "to drink", "verb", 200,
      T(r("пить", "pit"), rs("пити", "pyty", {"ru": 0.9}), rs("піць", "pits", {"ru": 0.9}),
        s("piť", {"cs": 1.0}), s("pít", {"sk": 1.0}), s("pić", {"cs": 0.9}),
        s("piti", {"hr": 1.0}), s("piti", {"sl": 1.0}),
        rs("пия", "piya", {"mk": 0.8}), rs("пијам", "pijam", {"bg": 0.7}),
        s("bere", {"ro": 0.7}), s("beber", {"pt": 1.0}), s("beber", {"es": 1.0}),
        s("boire", {"it": 0.6}), s("a bea", {"it": 0.6}),
        r("喝", "hē"), r("飲む", "nomu"), r("마시다", "masida"),
        l("uống"), l("inni"), s("juoda", {"et": 0.5}), l("jooma")),
      "Proto-Slavic *piti, Latein bibere, PIE *peh₃-", "Pit – wie 'Pint' trinken: piti = trinken!"),

    C("go", "gehen", "to go", "verb", 20,
      T(r("идти", "idti"), rs("іти", "ity", {"ru": 0.8}), rs("ісці", "istsi", {"ru": 0.7}),
        s("ísť", {"cs": 0.9}), s("jít", {"sk": 0.8}), s("iść", {"cs": 0.7}),
        s("iti", {"hr": 1.0}), s("ići", {"sl": 0.9}),
        rs("отивам", "otivam", {"mk": 0.7}), rs("одам", "odam", {}),
        s("andare", {}), s("ir", {"pt": 1.0}), s("ir", {"es": 1.0}),
        s("aller", {}), s("a merge", {}),
        r("去", "qù"), r("行く", "iku"), r("가다", "gada"),
        l("đi"), l("menni"), s("mennä", {"et": 0.5}), l("minema")),
      "Proto-Slavic *iti, Latein ire, PIE *h₁ey-", "Idti – wie 'I.D.' zeigen und dann gehen!"),

    C("come", "kommen", "to come", "verb", 40,
      T(r("приходить", "prikhodit"), rs("приходити", "prykhodity", {"ru": 0.9}),
        rs("прыходзіць", "prykhodziits", {"ru": 0.8}),
        s("prísť", {"cs": 0.8}), s("přijít", {"sk": 0.8}), s("przyjść", {"cs": 0.7}),
        s("priti", {"hr": 0.9}), s("doći", {"sl": 0.5}),
        rs("идвам", "idvam", {}), rs("доаѓам", "doagjam", {}),
        s("venire", {"es": 0.7, "fr": 0.7}), s("venir", {"it": 0.7, "pt": 0.8}),
        s("vir", {"es": 0.7}),
        s("venir", {"it": 0.7}), s("a veni", {"it": 0.7, "fr": 0.8}),
        r("来", "lái"), r("来る", "kuru"), r("오다", "oda"),
        l("đến"), l("jönni"), s("tulla", {"et": 0.6}), l("tulema")),
      "Proto-Slavic *prichoditi, Latein venire", "Prikhodit – 'pri' (bei) + 'khodit' (gehen) = herkommen!"),

    C("see", "sehen", "to see", "verb", 50,
      T(r("видеть", "videt"), rs("бачити", "bachyty", {}), rs("бачыць", "bachyts", {"uk": 0.9}),
        s("vidieť", {"cs": 0.9}), s("vidět", {"sk": 0.9}), s("widzieć", {"cs": 0.7}),
        s("videti", {"hr": 1.0}), s("vidjeti", {"sl": 0.9}),
        rs("виждам", "vizhdam", {"mk": 0.7}), rs("гледам", "gledam", {}),
        s("vedere", {"es": 0.8, "fr": 0.7}), s("ver", {"pt": 0.9}), s("ver", {"es": 0.9}),
        s("voir", {"it": 0.6}), s("a vedea", {"it": 0.8}),
        r("看", "kàn"), r("見る", "miru"), r("보다", "boda"),
        l("nhìn"), l("látni"), s("nähdä", {"et": 0.6}), l("nägema")),
      "Proto-Slavic *viděti, Latein videre, PIE *weyd-", "Videt – wie 'Video' – sehen = videt!"),

    C("hear", "hören", "to hear", "verb", 120,
      T(r("слышать", "slyshat"), rs("чути", "chuty", {}), rs("чуць", "chuts", {"uk": 0.9}),
        s("počuť", {"cs": 0.7}), s("slyšet", {"sk": 0.6}), s("słyszeć", {"cs": 0.7, "ru": 0.7}),
        s("slišati", {"hr": 0.9}), s("čuti", {"sl": 0.5}),
        rs("чувам", "chuvam", {"mk": 0.8}), rs("слушам", "slusham", {"ru": 0.6}),
        s("sentire", {"es": 0.7}), s("oír", {"pt": 0.6}), s("ouvir", {"es": 0.6}),
        s("entendre", {"ro": 0.5}), s("a auzi", {}),
        r("听", "tīng"), r("聞く", "kiku"), r("듣다", "deutda"),
        l("nghe"), l("hallani"), s("kuulla", {"et": 0.6}), l("kuulma")),
      "Proto-Slavic *slyšati, Latein audire", "Slyshat – wie 'Schlysch-at': Das Ohr schlüpft ans Hören!"),

    C("know", "wissen", "to know", "verb", 30,
      T(r("знать", "znat"), rs("знати", "znaty", {"ru": 0.9}), rs("ведаць", "vedats", {}),
        s("vedieť", {"cs": 0.9}), s("vědět", {"sk": 0.9}), s("wiedzieć", {"cs": 0.7}),
        s("vedeti", {"hr": 0.9}), s("znati", {"sl": 0.7, "ru": 0.7}),
        rs("зная", "znaya", {"ru": 0.8, "mk": 0.8}), rs("знам", "znam", {"bg": 0.8}),
        s("sapere", {}), s("saber", {"pt": 1.0}), s("saber", {"es": 1.0}),
        s("savoir", {"it": 0.6}), s("a ști", {}),
        r("知道", "zhīdào"), r("知る", "shiru"), r("알다", "alda"),
        l("biết"), l("tudni"), s("tietää", {"et": 0.5}), l("teadma")),
      "Proto-Slavic *znati, Latein scire/sapere, PIE *ǵneh₃-", "Znat – wie 'Z-Naht' wissen, wo die Naht ist!"),

    C("speak", "sprechen", "to speak", "verb", 80,
      T(r("говорить", "govorit"), rs("говорити", "hovoryty", {"ru": 0.9}),
        rs("гаварыць", "havaryts", {"ru": 0.8}),
        s("hovoriť", {"cs": 0.8}), s("hovořit", {"sk": 0.8}), s("mówić", {}),
        s("govoriti", {"hr": 1.0}), s("govoriti", {"sl": 1.0}),
        rs("говоря", "govorya", {"ru": 0.9, "mk": 0.9}), rs("зборувам", "zboruvam", {}),
        s("parlare", {"fr": 0.7}), s("hablar", {"pt": 0.5}), s("falar", {}),
        s("parler", {"it": 0.7}), s("a vorbi", {}),
        r("说", "shuō"), r("話す", "hanasu"), r("말하다", "malhada"),
        l("nói"), l("beszélni"), s("puhua", {"et": 0.4}), l("rääkima")),
      "Proto-Slavic *govoriti, Latein parlare (aus griech.)", "Govorit – 'Go-wo-rit' – wohin geht das Wort? Er spricht!"),

    C("write", "schreiben", "to write", "verb", 150,
      T(r("писать", "pisat"), rs("писати", "pysaty", {"ru": 0.9}), rs("пісаць", "pisats", {"ru": 0.9}),
        s("písať", {"cs": 1.0}), s("psát", {"sk": 0.8}), s("pisać", {"cs": 0.9}),
        s("pisati", {"hr": 1.0}), s("pisati", {"sl": 1.0}),
        rs("пиша", "pisha", {"mk": 0.8}), rs("пишувам", "pishuvam", {"bg": 0.7}),
        s("scrivere", {"fr": 0.5}), s("escribir", {"pt": 0.8}), s("escrever", {"es": 0.8}),
        s("écrire", {"it": 0.5}), s("a scrie", {"it": 0.6}),
        r("写", "xiě"), r("書く", "kaku"), r("쓰다", "sseuda"),
        l("viết"), l("írni"), s("kirjoittaa", {"et": 0.4}), l("kirjutama")),
      "Proto-Slavic *pĭsati, Latein scribere", "Pisat – wie 'Pizza-t' schreiben: Schreib mir eine Pizza-Bestellung!"),

    C("read", "lesen", "to read", "verb", 155,
      T(r("читать", "chitat"), rs("читати", "chytaty", {"ru": 0.9}), rs("чытаць", "chytats", {"ru": 0.9}),
        s("čítať", {"cs": 1.0}), s("číst", {"sk": 0.8}), s("czytać", {"cs": 0.8}),
        s("brati", {}), s("čitati", {"sl": 0.7}),
        rs("чета", "cheta", {"mk": 0.8}), rs("читам", "chitam", {"ru": 0.8, "bg": 0.8}),
        s("leggere", {}), s("leer", {"pt": 0.8}), s("ler", {"es": 0.8}),
        s("lire", {"it": 0.6}), s("a citi", {}),
        r("读", "dú"), r("読む", "yomu"), r("읽다", "ilkda"),
        l("đọc"), l("olvasni"), s("lukea", {"et": 0.4}), l("lugema")),
      "Proto-Slavic *čitati, Latein legere", "Chitat – wie 'Tschita-t' – liest man in der Stadt Tschita!"),

    C("sleep", "schlafen", "to sleep", "verb", 210,
      T(r("спать", "spat"), rs("спати", "spaty", {"ru": 0.9}), rs("спаць", "spats", {"ru": 0.9}),
        s("spať", {"cs": 1.0}), s("spát", {"sk": 1.0}), s("spać", {"cs": 0.9}),
        s("spati", {"hr": 1.0}), s("spavati", {"sl": 0.8}),
        rs("спя", "spya", {"mk": 0.8}), rs("спијам", "spijam", {"bg": 0.7}),
        s("dormire", {"es": 0.8, "fr": 0.7}), s("dormir", {"it": 0.8, "pt": 1.0}),
        s("dormir", {"es": 1.0}),
        s("dormir", {"it": 0.8, "es": 0.9}), s("a dormi", {"fr": 0.9}),
        r("睡", "shuì"), r("寝る", "neru"), r("자다", "jada"),
        l("ngủ"), l("aludni"), s("nukkua", {"et": 0.4}), l("magama")),
      "Proto-Slavic *sŭpati, Latein dormire", "Spat – wie 'spät' schlafen gehen: Wer spat schläft!"),

    C("give", "geben", "to give", "verb", 60,
      T(r("давать", "davat"), rs("давати", "davaty", {"ru": 0.9}), rs("даваць", "davats", {"ru": 0.9}),
        s("dávať", {"cs": 1.0}), s("dávat", {"sk": 1.0}), s("dawać", {"cs": 0.8}),
        s("davati", {"hr": 0.9}), s("davati", {"sl": 0.9}),
        rs("давам", "davam", {"ru": 0.8, "mk": 1.0}), rs("давам", "davam", {"bg": 1.0}),
        s("dare", {"es": 0.8}), s("dar", {"pt": 1.0}), s("dar", {"es": 1.0}),
        s("donner", {"it": 0.6}), s("a da", {"it": 0.6}),
        r("给", "gěi"), r("あげる", "ageru"), r("주다", "juda"),
        l("cho"), l("adni"), s("antaa", {"et": 0.5}), l("andma")),
      "Proto-Slavic *dati/davati, Latein dare, PIE *deh₃-", "Davat – wie 'da-fast': Da, nimm, ich gebe es dir!"),

    C("take", "nehmen", "to take", "verb", 65,
      T(r("брать", "brat"), rs("брати", "braty", {"ru": 0.9}), rs("браць", "brats", {"ru": 0.9}),
        s("brať", {"cs": 1.0}), s("brát", {"sk": 1.0}), s("brać", {"cs": 0.9}),
        s("brati", {"hr": 1.0}), s("uzeti", {}),
        rs("вземам", "vzemam", {}), rs("земам", "zemam", {"bg": 0.6}),
        s("prendere", {"fr": 0.7}), s("tomar", {"pt": 0.8}), s("tomar", {"es": 0.8}),
        s("prendre", {"it": 0.7}), s("a lua", {}),
        r("拿", "ná"), r("取る", "toru"), r("가져가다", "gajyeogada"),
        l("lấy"), l("venni"), s("ottaa", {"et": 0.5}), l("võtma")),
      "Proto-Slavic *bĭrati, Latein prendere", "Brat – wie 'Braten' greifen: Nimm den Braten!"),

    C("sit", "sitzen", "to sit", "verb", 130,
      T(r("сидеть", "sidet"), rs("сидіти", "sydity", {"ru": 0.9}), rs("сядзець", "syadzets", {"ru": 0.7}),
        s("sedieť", {"cs": 0.9}), s("sedět", {"sk": 0.9}), s("siedzieć", {"cs": 0.8}),
        s("sedeti", {"hr": 1.0}), s("sjediti", {"sl": 0.8}),
        rs("седя", "sedya", {"mk": 0.9}), rs("седам", "sedam", {"bg": 0.9}),
        s("sedere", {"es": 0.7}), s("sentar", {"pt": 0.8}), s("sentar", {"es": 0.8}),
        s("s'asseoir", {}), s("a ședea", {"it": 0.7}),
        r("坐", "zuò"), r("座る", "suwaru"), r("앉다", "anda"),
        l("ngồi"), l("ülni"), s("istua", {"et": 0.5}), l("istuma")),
      "Proto-Slavic *sěděti, Latein sedere, PIE *sed-", "Sidet – wie 'Sit-det': Er sitzt da! Verwandt mit lat. sedere!"),

    C("stand", "stehen", "to stand", "verb", 135,
      T(r("стоять", "stoyat"), rs("стояти", "stoyaty", {"ru": 0.9}), rs("стаяць", "stayats", {"ru": 0.8}),
        s("stáť", {"cs": 1.0}), s("stát", {"sk": 1.0}), s("stać", {"cs": 0.9}),
        s("stati", {"hr": 0.9}), s("stajati", {"sl": 0.7}),
        rs("стоя", "stoya", {"ru": 0.8, "mk": 0.9}), rs("стојам", "stojam", {"bg": 0.8}),
        s("stare", {"es": 0.7}), s("estar de pie", {}), s("estar de pé", {}),
        s("se tenir debout", {}), s("a sta", {"it": 0.7}),
        r("站", "zhàn"), r("立つ", "tatsu"), r("서다", "seoda"),
        l("đứng"), l("állni"), s("seisoa", {"et": 0.5}), l("seisma")),
      "Proto-Slavic *stojati, Latein stare, PIE *steh₂-", "Stoyat – wie 'Stoi!' (Halt/Steh!) – der russische Polizist ruft!"),

    # ===== GROUP 4: 8 adjectives =====
    C("small", "klein", "small", "adjektiv", 55,
      T(r("маленький", "malenkiy"), rs("маленький", "malenkiy", {"ru": 1.0}),
        rs("маленькі", "malenki", {"ru": 0.9}),
        s("malý", {"cs": 1.0}), s("malý", {"sk": 1.0}), s("mały", {"cs": 0.9}),
        s("majhen", {"hr": 0.5}), s("mali", {"sl": 0.6}),
        rs("малък", "malak", {"mk": 0.8}), rs("мал", "mal", {"bg": 0.8}),
        s("piccolo", {}), s("pequeño", {"pt": 0.7}), s("pequeno", {"es": 0.7}),
        s("petit", {"ro": 0.5}), s("mic", {}),
        r("小", "xiǎo"), r("小さい", "chiisai"), r("작은", "jageun"),
        l("nhỏ"), l("kicsi"), s("pieni", {"et": 0.4}), l("väike")),
      "Proto-Slavic *malŭ, Latein parvus", "Malenkiy – 'Mal-ein-kleiner': Mal ein kleiner Schritt!"),

    C("old", "alt", "old", "adjektiv", 70,
      T(r("старый", "staryy"), rs("старий", "staryy", {"ru": 1.0}), rs("стары", "stary", {"ru": 0.9}),
        s("starý", {"cs": 1.0}), s("starý", {"sk": 1.0}), s("stary", {"cs": 1.0}),
        s("star", {"hr": 1.0}), s("star", {"sl": 1.0}),
        rs("стар", "star", {"mk": 1.0}), rs("стар", "star", {"bg": 1.0}),
        s("vecchio", {}), s("viejo", {"pt": 0.7}), s("velho", {"es": 0.7}),
        s("vieux", {"it": 0.5}), s("vechi", {"it": 0.6}),
        r("老", "lǎo"), r("古い", "furui"), r("오래된", "oraedoen"),
        l("cũ"), l("öreg"), s("vanha", {"et": 0.4}), l("vana")),
      "Proto-Slavic *starŭ, Latein vetus/vetulus", "Staryy – wie 'Star' am Himmel: Sterne sind alt!"),

    C("young", "jung", "young", "adjektiv", 100,
      T(r("молодой", "molodoy"), rs("молодий", "molodyy", {"ru": 0.9}),
        rs("малады", "malady", {"ru": 0.8}),
        s("mladý", {"cs": 1.0}), s("mladý", {"sk": 1.0}), s("młody", {"cs": 0.9}),
        s("mlad", {"hr": 1.0}), s("mlad", {"sl": 1.0}),
        rs("млад", "mlad", {"mk": 1.0}), rs("млад", "mlad", {"bg": 1.0}),
        s("giovane", {}), s("joven", {"pt": 0.8}), s("jovem", {"es": 0.8}),
        s("jeune", {"it": 0.5}), s("tânăr", {}),
        r("年轻", "niánqīng"), r("若い", "wakai"), r("젊은", "jeolmeun"),
        l("trẻ"), l("fiatal"), s("nuori", {"et": 0.5}), l("noor")),
      "Proto-Slavic *moldŭ, Latein juvenis", "Molodoy – 'Molodoj Melodie': Eine junge Melodie!"),

    C("cold", "kalt", "cold", "adjektiv", 230,
      T(r("холодный", "kholodnyy"), rs("холодний", "kholodnyy", {"ru": 1.0}),
        rs("халодны", "khalodny", {"ru": 0.9}),
        s("studený", {"cs": 0.9}), s("studený", {"sk": 0.9}), s("zimny", {}),
        s("mrzel", {}), s("hladan", {"cs": 0.5}),
        rs("студен", "studen", {"mk": 0.9}), rs("студен", "studen", {"bg": 1.0}),
        s("freddo", {}), s("frío", {"pt": 0.7}), s("frio", {"es": 0.7}),
        s("froid", {"it": 0.6}), s("rece", {}),
        r("冷", "lěng"), r("寒い", "samui"), r("차가운", "chagaun"),
        l("lạnh"), l("hideg"), s("kylmä", {"et": 0.5}), l("külm")),
      "Proto-Slavic *xoldŭnŭ, Latein frigidus", "Kholodnyy – 'Holo-kalt' – im Holodeck ist es kalt!"),

    C("hot", "heiß", "hot", "adjektiv", 235,
      T(r("горячий", "goryachiy"), rs("гарячий", "haryachiy", {"ru": 0.9}),
        rs("гарачы", "harachy", {"ru": 0.8}),
        s("horúci", {"cs": 0.8}), s("horký", {"sk": 0.8}), s("gorący", {"cs": 0.7, "ru": 0.6}),
        s("vroč", {"hr": 0.5}), s("vruć", {"sl": 0.7}),
        rs("горещ", "goresht", {"mk": 0.7}), rs("жежок", "zhezhok", {}),
        s("caldo", {}), s("caliente", {"pt": 0.6}), s("quente", {"es": 0.6}),
        s("chaud", {"it": 0.5}), s("fierbinte", {}),
        r("热", "rè"), r("暑い", "atsui"), r("뜨거운", "tteugeoun"),
        l("nóng"), l("forró"), s("kuuma", {"et": 0.7}), l("kuum")),
      "Proto-Slavic *gorěčĭ (von *gorěti = brennen), Latein calidus", "Goryachiy – 'Gorja-tschij' – das Gorja (Bergland) brennt heiß!"),

    C("beautiful", "schön", "beautiful", "adjektiv", 115,
      T(r("красивый", "krasivyy"), rs("красивий", "krasyvyy", {"ru": 1.0}),
        rs("прыгожы", "pryhozy", {}),
        s("krásny", {"cs": 1.0}), s("krásný", {"sk": 1.0}), s("piękny", {}),
        s("lep", {"hr": 0.8}), s("lijep", {"sl": 0.7}),
        rs("красив", "krasiv", {"ru": 0.9, "mk": 0.8}), rs("убав", "ubav", {}),
        s("bello", {"es": 0.8, "fr": 0.7}), s("hermoso", {"pt": 0.6}), s("bonito", {}),
        s("beau", {"it": 0.7}), s("frumos", {}),
        r("美丽", "měilì"), r("美しい", "utsukushii"), r("아름다운", "areumdaun"),
        l("đẹp"), l("szép"), s("kaunis", {"et": 0.8}), l("kaunis")),
      "Proto-Slavic *krasĭnŭ (von *krasa = Schönheit)", "Krasivyy – wie 'Krass!' – krass schön!"),

    C("fast", "schnell", "fast", "adjektiv", 175,
      T(r("быстрый", "bystryy"), rs("швидкий", "shvydkyy", {}),
        rs("хуткі", "khutki", {}),
        s("rýchly", {"cs": 0.9}), s("rychlý", {"sk": 0.9}), s("szybki", {}),
        s("hiter", {"hr": 0.5}), s("brz", {"sl": 0.4}),
        rs("бърз", "barz", {"mk": 0.8}), rs("брз", "brz", {"bg": 0.8}),
        s("veloce", {}), s("rápido", {"pt": 1.0}), s("rápido", {"es": 1.0}),
        s("rapide", {"it": 0.7, "es": 0.7}), s("rapid", {"fr": 0.9}),
        r("快", "kuài"), r("速い", "hayai"), r("빠른", "ppareun"),
        l("nhanh"), l("gyors"), s("nopea", {"et": 0.4}), l("kiire")),
      "Proto-Slavic *bystrŭ, Latein rapidus", "Bystryy – wie 'Biest-rij' – so schnell wie ein Biest!"),

    C("slow", "langsam", "slow", "adjektiv", 340,
      T(r("медленный", "medlennyy"), rs("повільний", "povilnyy", {}),
        rs("павольны", "pavolny", {}),
        s("pomalý", {"cs": 1.0}), s("pomalý", {"sk": 1.0}), s("powolny", {"cs": 0.7}),
        s("počasen", {"hr": 0.6}), s("spor", {}),
        rs("бавен", "baven", {"mk": 0.7}), rs("бавен", "baven", {"bg": 1.0}),
        s("lento", {"es": 1.0, "pt": 1.0}), s("lento", {"it": 1.0, "pt": 1.0}),
        s("lento", {"it": 1.0, "es": 1.0}),
        s("lent", {"it": 0.8}), s("lent", {"fr": 1.0}),
        r("慢", "màn"), r("遅い", "osoi"), r("느린", "neurin"),
        l("chậm"), l("lassú"), s("hidas", {"et": 0.4}), l("aeglane")),
      "Proto-Slavic *medlĭnŭ, Latein lentus", "Medlennyy – wie 'Med-Lenny': Lenny isst langsam seinen Honig (med)!"),

    # ===== GROUP 5: 7 numerals =====
    C("four", "vier", "four", "numerale", 28,
      T(r("четыре", "chetyre"), rs("чотири", "chotyry", {"ru": 0.8}), rs("чатыры", "chatyry", {"ru": 0.8}),
        s("štyri", {"cs": 0.8}), s("čtyři", {"sk": 0.8}), s("cztery", {"cs": 0.7}),
        s("štiri", {"hr": 0.7}), s("četiri", {"sl": 0.7}),
        rs("четири", "chetiri", {"ru": 0.9, "mk": 1.0}), rs("четири", "chetiri", {"bg": 1.0}),
        s("quattro", {"es": 0.7}), s("cuatro", {"pt": 0.7}), s("quatro", {"es": 0.7}),
        s("quatre", {"it": 0.7}), s("patru", {}),
        r("四", "sì"), r("四", "shi"), r("넷", "net"),
        l("bốn"), l("négy"), s("neljä", {"et": 0.8}), l("neli")),
      "Proto-Slavic *četyre, Latein quattuor, PIE *kʷetwóres", "Chetyre – 'Tschetüre' klingt wie 'Tschechischer Türe' – vier Türen!"),

    C("five", "fünf", "five", "numerale", 32,
      T(r("пять", "pyat"), rs("п'ять", "pyat", {"ru": 1.0}), rs("пяць", "pyats", {"ru": 0.9}),
        s("päť", {"cs": 0.9}), s("pět", {"sk": 0.9}), s("pięć", {"cs": 0.8}),
        s("pet", {"hr": 1.0}), s("pet", {"sl": 1.0}),
        rs("пет", "pet", {"mk": 1.0}), rs("пет", "pet", {"bg": 1.0}),
        s("cinque", {"fr": 0.6}), s("cinco", {"pt": 1.0}), s("cinco", {"es": 1.0}),
        s("cinq", {"it": 0.7}), s("cinci", {"it": 0.6}),
        r("五", "wǔ"), r("五", "go"), r("다섯", "daseot"),
        l("năm"), l("öt"), s("viisi", {"et": 0.8}), l("viis")),
      "Proto-Slavic *pętĭ, Latein quinque, PIE *pénkʷe", "Pyat – wie die 'fünf Finger' einer Pyat(Pfote)!"),

    C("six", "sechs", "six", "numerale", 35,
      T(r("шесть", "shest"), rs("шість", "shist", {"ru": 0.8}), rs("шэсць", "shests", {"ru": 0.9}),
        s("šesť", {"cs": 1.0}), s("šest", {"sk": 1.0}), s("sześć", {"cs": 0.8}),
        s("šest", {"hr": 1.0}), s("šest", {"sl": 1.0}),
        rs("шест", "shest", {"ru": 1.0, "mk": 1.0}), rs("шест", "shest", {"bg": 1.0}),
        s("sei", {"es": 0.7}), s("seis", {"pt": 1.0}), s("seis", {"es": 1.0}),
        s("six", {"it": 0.5}), s("șase", {"it": 0.4}),
        r("六", "liù"), r("六", "roku"), r("여섯", "yeoseot"),
        l("sáu"), l("hat"), s("kuusi", {"et": 0.7}), l("kuus")),
      "Proto-Slavic *šestĭ, Latein sex, PIE *swéḱs", "Shest – wie 'Schest' – sechs Scherze!"),

    C("seven", "sieben", "seven", "numerale", 38,
      T(r("семь", "sem"), rs("сім", "sim", {"ru": 0.8}), rs("сем", "sem", {"ru": 1.0}),
        s("sedem", {"cs": 0.9}), s("sedm", {"sk": 0.8}), s("siedem", {"cs": 0.8}),
        s("sedem", {"hr": 1.0}), s("sedam", {"sl": 0.9}),
        rs("седем", "sedem", {"mk": 1.0}), rs("седум", "sedum", {"bg": 0.9}),
        s("sette", {"es": 0.7}), s("siete", {"pt": 0.7}), s("sete", {"es": 0.7}),
        s("sept", {"it": 0.6}), s("șapte", {"it": 0.5}),
        r("七", "qī"), r("七", "nana"), r("일곱", "ilgop"),
        l("bảy"), l("hét"), s("seitsemän", {"et": 0.7}), l("seitse")),
      "Proto-Slavic *sedmĭ, Latein septem, PIE *septḿ̥", "Sem – wie 'Semester': Sieben Semester studiert!"),

    C("eight", "acht", "eight", "numerale", 40,
      T(r("восемь", "vosem"), rs("вісім", "visim", {"ru": 0.7}), rs("восем", "vosem", {"ru": 1.0}),
        s("osem", {"cs": 1.0}), s("osm", {"sk": 0.8}), s("osiem", {"cs": 0.8}),
        s("osem", {"hr": 1.0}), s("osam", {"sl": 0.9}),
        rs("осем", "osem", {"mk": 1.0}), rs("осум", "osum", {"bg": 0.9}),
        s("otto", {}), s("ocho", {"pt": 0.7}), s("oito", {"es": 0.7}),
        s("huit", {"it": 0.4}), s("opt", {}),
        r("八", "bā"), r("八", "hachi"), r("여덟", "yeodeol"),
        l("tám"), l("nyolc"), s("kahdeksan", {"et": 0.7}), l("kaheksa")),
      "Proto-Slavic *osmĭ, Latein octo, PIE *oḱtṓw", "Vosem – wie 'Awesome' – acht ist awesome!"),

    C("nine", "neun", "nine", "numerale", 42,
      T(r("девять", "devyat"), rs("дев'ять", "devyat", {"ru": 1.0}), rs("дзевяць", "dzevyats", {"ru": 0.8}),
        s("deväť", {"cs": 0.9}), s("devět", {"sk": 0.9}), s("dziewięć", {"cs": 0.6}),
        s("devet", {"hr": 1.0}), s("devet", {"sl": 1.0}),
        rs("девет", "devet", {"mk": 1.0}), rs("девет", "devet", {"bg": 1.0}),
        s("nove", {"es": 0.8}), s("nueve", {"pt": 0.7}), s("nove", {"it": 0.8}),
        s("neuf", {"it": 0.5}), s("nouă", {"it": 0.5}),
        r("九", "jiǔ"), r("九", "kyū"), r("아홉", "ahop"),
        l("chín"), l("kilenc"), s("yhdeksän", {"et": 0.7}), l("üheksa")),
      "Proto-Slavic *devętĭ, Latein novem, PIE *h₁néwn̥", "Devyat – wie 'Dewey hat' neun Bücher!"),

    C("ten", "zehn", "ten", "numerale", 25,
      T(r("десять", "desyat"), rs("десять", "desyat", {"ru": 1.0}), rs("дзесяць", "dzesyats", {"ru": 0.8}),
        s("desať", {"cs": 0.9}), s("deset", {"sk": 0.8}), s("dziesięć", {"cs": 0.6}),
        s("deset", {"hr": 1.0}), s("deset", {"sl": 1.0}),
        rs("десет", "deset", {"mk": 1.0}), rs("десет", "deset", {"bg": 1.0}),
        s("dieci", {}), s("diez", {"pt": 0.7}), s("dez", {"es": 0.7}),
        s("dix", {"it": 0.5}), s("zece", {}),
        r("十", "shí"), r("十", "jū"), r("열", "yeol"),
        l("mười"), l("tíz"), s("kymmenen", {"et": 0.5}), l("kümme")),
      "Proto-Slavic *desętĭ, Latein decem, PIE *déḱm̥t", "Desyat – wie 'Dessert': Zehn Desserts zum Nachtisch!"),
]

# Main
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

existing_ids = {c["id"] for c in data["concepts"]}
added = 0
for concept in NEW:
    if concept["id"] not in existing_ids:
        data["concepts"].append(concept)
        added += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Added {added} new concepts. Total: {len(data['concepts'])}")
