#!/usr/bin/env python3
"""
Generate new vocabulary entries for 7 languages across 4 new categories:
  - koerper_gesundheit (body/health)
  - essen_trinken (food/drink)
  - natur_wetter (nature/weather)
  - beruf_bildung (work/education)

Languages: Chinese (zh), Japanese (ja), Korean (ko), Vietnamese (vi),
           Hungarian (hu), Finnish (fi), Estonian (et)

Run from the project root:
    python scripts/gen_other_vocab.py
"""

import json
import os
import sys

# Resolve paths relative to the project root (parent of scripts/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(PROJECT_ROOT, "data", "words")

# ---------------------------------------------------------------------------
# Category definitions: concept_id -> (meaning_de, meaning_en)
# ---------------------------------------------------------------------------

CATEGORIES = {
    "koerper_gesundheit": [
        ("hand", "Hand", "hand"),
        ("fuss", "Fuß", "foot"),
        ("zahn", "Zahn", "tooth"),
        ("ohr", "Ohr", "ear"),
        ("nase", "Nase", "nose"),
        ("mund", "Mund", "mouth"),
        ("finger", "Finger", "finger"),
        ("ruecken", "Rücken", "back"),
        ("arm_body", "Arm", "arm"),
        ("bein", "Bein", "leg"),
        ("haut", "Haut", "skin"),
        ("blut", "Blut", "blood"),
        ("knochen", "Knochen", "bone"),
        ("krankenhaus", "Krankenhaus", "hospital"),
        ("medizin", "Medizin", "medicine"),
        ("krank", "krank", "sick"),
        ("gesund", "gesund", "healthy"),
        ("bauch", "Bauch", "stomach"),
        ("arzt", "Arzt", "doctor"),
        ("schmerz", "Schmerz", "pain"),
        ("fieber", "Fieber", "fever"),
        ("husten", "Husten", "cough"),
        ("apotheke", "Apotheke", "pharmacy"),
        ("zunge", "Zunge", "tongue"),
        ("schulter", "Schulter", "shoulder"),
    ],
    "essen_trinken": [
        ("fleisch", "Fleisch", "meat"),
        ("fisch", "Fisch", "fish"),
        ("reis", "Reis", "rice"),
        ("kaffee", "Kaffee", "coffee"),
        ("tee", "Tee", "tea"),
        ("bier", "Bier", "beer"),
        ("wein", "Wein", "wine"),
        ("suppe", "Suppe", "soup"),
        ("gemuese", "Gemüse", "vegetables"),
        ("obst", "Obst", "fruit"),
        ("ei", "Ei", "egg"),
        ("kaese", "Käse", "cheese"),
        ("zucker", "Zucker", "sugar"),
        ("salz", "Salz", "salt"),
        ("butter", "Butter", "butter"),
        ("oel", "Öl", "oil"),
        ("kartoffel", "Kartoffel", "potato"),
        ("huhn", "Huhn", "chicken"),
        ("tomate", "Tomate", "tomato"),
        ("apfel", "Apfel", "apple"),
        ("kuchen", "Kuchen", "cake"),
        ("kochen", "kochen", "to cook"),
        ("restaurant", "Restaurant", "restaurant"),
        ("fruehstueck", "Frühstück", "breakfast"),
        ("abendessen", "Abendessen", "dinner"),
    ],
    "natur_wetter": [
        ("wald", "Wald", "forest"),
        ("himmel", "Himmel", "sky"),
        ("stern", "Stern", "star"),
        ("erde", "Erde", "earth"),
        ("wind", "Wind", "wind"),
        ("wolke", "Wolke", "cloud"),
        ("donner", "Donner", "thunder"),
        ("insel", "Insel", "island"),
        ("see_lake", "See", "lake"),
        ("gras", "Gras", "grass"),
        ("stein", "Stein", "stone"),
        ("sand", "Sand", "sand"),
        ("eis", "Eis", "ice"),
        ("nebel", "Nebel", "fog"),
        ("strand", "Strand", "beach"),
        ("wueste", "Wüste", "desert"),
        ("fruehling", "Frühling", "spring"),
        ("sommer", "Sommer", "summer"),
        ("herbst", "Herbst", "autumn"),
        ("winter", "Winter", "winter"),
        ("luft", "Luft", "air"),
        ("feuer", "Feuer", "fire"),
        ("sturm", "Sturm", "storm"),
        ("regenbogen", "Regenbogen", "rainbow"),
        ("feld", "Feld", "field"),
    ],
    "beruf_bildung": [
        ("lehrer", "Lehrer", "teacher"),
        ("schueler", "Schüler", "student"),
        ("buero", "Büro", "office"),
        ("computer", "Computer", "computer"),
        ("universitaet", "Universität", "university"),
        ("pruefung", "Prüfung", "exam"),
        ("beruf", "Beruf", "profession"),
        ("chef", "Chef", "boss"),
        ("gehalt", "Gehalt", "salary"),
        ("ingenieur", "Ingenieur", "engineer"),
        ("rechtsanwalt", "Rechtsanwalt", "lawyer"),
        ("polizist", "Polizist", "police officer"),
        ("wissenschaft", "Wissenschaft", "science"),
        ("mathematik", "Mathematik", "mathematics"),
        ("geschichte", "Geschichte", "history"),
        ("sprache_lang", "Sprache", "language"),
        ("bibliothek", "Bibliothek", "library"),
        ("klasse", "Klasse", "class"),
        ("studieren", "studieren", "to study"),
        ("unterrichten", "unterrichten", "to teach"),
        ("aufgabe", "Aufgabe", "task"),
        ("erfahrung", "Erfahrung", "experience"),
        ("unternehmen", "Unternehmen", "company"),
        ("projekt", "Projekt", "project"),
        ("meeting", "Besprechung", "meeting"),
    ],
}

# ---------------------------------------------------------------------------
# Per-language translations
# Each entry: (word, romanization, pronunciation_hint, tone, notes)
# For languages without tones, tone is None.
# For Vietnamese, tone is an integer 1-6.
# For Chinese, tone is an integer 1-4 (or 0 for neutral).
# ---------------------------------------------------------------------------

TRANSLATIONS = {}

# ===========================
# CHINESE (zh)
# ===========================
TRANSLATIONS["chinese"] = {
    "koerper_gesundheit": [
        ("手", "shǒu", "schoh (3. Ton: fallend-steigend, wie nachdenklich 'Hmm?')", 3, ""),
        ("脚", "jiǎo", "dschiau (3. Ton: fallend-steigend)", 3, ""),
        ("牙齿", "yáchǐ", "ja-tschii (2.+3. Ton: steigend + fallend-steigend)", None, "牙 = Zahn, 齿 = Zähne"),
        ("耳朵", "ěrduo", "är-duo (3. Ton + neutraler Ton)", 3, "朵 wird im neutralen Ton gesprochen"),
        ("鼻子", "bízi", "bi-ds (2. Ton: steigend + neutraler Ton)", 2, "子 wird im neutralen Ton gesprochen"),
        ("嘴", "zuǐ", "dsuei (3. Ton: fallend-steigend)", 3, ""),
        ("手指", "shǒuzhǐ", "schoh-dschii (3.+3. Ton → 2.+3. Tonsandhi)", None, "Zwei 3. Töne: erster wird zu 2. Ton"),
        ("背", "bèi", "bei (4. Ton: scharf fallend)", 4, "Als Nomen: Rücken; als Verb: tragen"),
        ("胳膊", "gēbo", "gö-bo (1. Ton + neutraler Ton)", 1, "膊 wird im neutralen Ton gesprochen"),
        ("腿", "tuǐ", "tuei (3. Ton: fallend-steigend)", 3, ""),
        ("皮肤", "pífū", "pi-fu (2.+1. Ton: steigend + hoch)", None, ""),
        ("血", "xuè", "schüe (4. Ton: scharf fallend)", 4, "x = sch mit gespitzten Lippen"),
        ("骨头", "gǔtou", "gu-toh (3. Ton + neutraler Ton)", 3, "头 wird im neutralen Ton gesprochen"),
        ("医院", "yīyuàn", "ii-jüen (1.+4. Ton: hoch + fallend)", None, ""),
        ("药", "yào", "jau (4. Ton: scharf fallend)", 4, ""),
        ("生病", "shēngbìng", "schöng-bing (1.+4. Ton: hoch + fallend)", None, "Wörtl.: 'Krankheit erzeugen'"),
        ("健康", "jiànkāng", "dschien-kang (4.+1. Ton: fallend + hoch)", None, ""),
        ("肚子", "dùzi", "du-ds (4. Ton + neutraler Ton)", 4, "子 wird im neutralen Ton gesprochen"),
        ("医生", "yīshēng", "ii-schöng (1.+1. Ton: hoch + hoch)", None, ""),
        ("疼痛", "téngtòng", "töng-tong (2.+4. Ton: steigend + fallend)", None, "疼 allein heißt auch 'schmerzen'"),
        ("发烧", "fāshāo", "fa-schau (1.+1. Ton: hoch + hoch)", None, "Wörtl.: 'Hitze entwickeln'"),
        ("咳嗽", "késou", "kö-soh (2. Ton + neutraler Ton)", 2, "嗽 wird im neutralen Ton gesprochen"),
        ("药房", "yàofáng", "jau-fang (4.+2. Ton: fallend + steigend)", None, "Wörtl.: 'Medizin-Raum'"),
        ("舌头", "shétou", "schö-toh (2. Ton + neutraler Ton)", 2, "头 wird im neutralen Ton gesprochen"),
        ("肩膀", "jiānbǎng", "dschien-bang (1.+3. Ton: hoch + fallend-steigend)", None, ""),
    ],
    "essen_trinken": [
        ("肉", "ròu", "roh (4. Ton: scharf fallend)", 4, ""),
        ("鱼", "yú", "jü (2. Ton: steigend)", 2, ""),
        ("米饭", "mǐfàn", "mi-fan (3.+4. Ton: fallend-steigend + fallend)", None, "米 = Reis (roh), 饭 = gekochter Reis"),
        ("咖啡", "kāfēi", "ka-fei (1.+1. Ton: hoch + hoch)", None, "Lehnwort aus dem Englischen"),
        ("茶", "chá", "tscha (2. Ton: steigend)", 2, ""),
        ("啤酒", "píjiǔ", "pi-dschioh (2.+3. Ton: steigend + fallend-steigend)", None, ""),
        ("葡萄酒", "pútaojiǔ", "pu-tau-dschioh (2. Ton + neutral + 3. Ton)", None, "Wörtl.: 'Trauben-Alkohol'"),
        ("汤", "tāng", "tang (1. Ton: hoch und gleichbleibend)", 1, ""),
        ("蔬菜", "shūcài", "schu-tsai (1.+4. Ton: hoch + fallend)", None, ""),
        ("水果", "shuǐguǒ", "schuei-guo (3.+3. Ton → 2.+3. Tonsandhi)", None, "Zwei 3. Töne: erster wird zu 2. Ton"),
        ("鸡蛋", "jīdàn", "dschi-dan (1.+4. Ton: hoch + fallend)", None, "Wörtl.: 'Hühner-Ei'"),
        ("奶酪", "nǎilào", "nai-lau (3.+4. Ton: fallend-steigend + fallend)", None, ""),
        ("糖", "táng", "tang (2. Ton: steigend)", 2, ""),
        ("盐", "yán", "jen (2. Ton: steigend)", 2, ""),
        ("黄油", "huángyóu", "huang-joh (2.+2. Ton: steigend + steigend)", None, "Wörtl.: 'gelbes Öl'"),
        ("油", "yóu", "joh (2. Ton: steigend)", 2, ""),
        ("土豆", "tǔdòu", "tu-doh (3.+4. Ton: fallend-steigend + fallend)", None, "Wörtl.: 'Erd-Bohne'"),
        ("鸡肉", "jīròu", "dschi-roh (1.+4. Ton: hoch + fallend)", None, "Wörtl.: 'Hühner-Fleisch'"),
        ("西红柿", "xīhóngshì", "schi-hong-schii (1.+2.+4. Ton)", None, "Wörtl.: 'westliche rote Frucht'"),
        ("苹果", "píngguǒ", "ping-guo (2.+3. Ton: steigend + fallend-steigend)", None, ""),
        ("蛋糕", "dàngāo", "dan-gau (4.+1. Ton: fallend + hoch)", None, ""),
        ("做饭", "zuòfàn", "dsuo-fan (4.+4. Ton: fallend + fallend)", None, "Wörtl.: 'Reis/Essen machen'"),
        ("餐厅", "cāntīng", "tsan-ting (1.+1. Ton: hoch + hoch)", None, ""),
        ("早餐", "zǎocān", "dsau-tsan (3.+1. Ton: fallend-steigend + hoch)", None, "Wörtl.: 'frühe Mahlzeit'"),
        ("晚餐", "wǎncān", "wan-tsan (3.+1. Ton: fallend-steigend + hoch)", None, "Wörtl.: 'Abend-Mahlzeit'"),
    ],
    "natur_wetter": [
        ("森林", "sēnlín", "sön-lin (1.+2. Ton: hoch + steigend)", None, ""),
        ("天空", "tiānkōng", "tien-kong (1.+1. Ton: hoch + hoch)", None, "Wörtl.: 'Himmels-Leere'"),
        ("星星", "xīngxing", "sching-sching (1. Ton + neutraler Ton)", 1, "Verdoppelung typisch im Chinesischen"),
        ("地球", "dìqiú", "di-tschioh (4.+2. Ton: fallend + steigend)", None, "Wörtl.: 'Erd-Kugel'"),
        ("风", "fēng", "föng (1. Ton: hoch und gleichbleibend)", 1, ""),
        ("云", "yún", "jün (2. Ton: steigend)", 2, ""),
        ("雷", "léi", "lei (2. Ton: steigend)", 2, ""),
        ("岛", "dǎo", "dau (3. Ton: fallend-steigend)", 3, ""),
        ("湖", "hú", "hu (2. Ton: steigend)", 2, ""),
        ("草", "cǎo", "tsau (3. Ton: fallend-steigend)", 3, ""),
        ("石头", "shítou", "schii-toh (2. Ton + neutraler Ton)", 2, "头 wird im neutralen Ton gesprochen"),
        ("沙子", "shāzi", "scha-ds (1. Ton + neutraler Ton)", 1, "子 wird im neutralen Ton gesprochen"),
        ("冰", "bīng", "bing (1. Ton: hoch und gleichbleibend)", 1, ""),
        ("雾", "wù", "wu (4. Ton: scharf fallend)", 4, ""),
        ("海滩", "hǎitān", "hai-tan (3.+1. Ton: fallend-steigend + hoch)", None, "Wörtl.: 'Meer-Strand'"),
        ("沙漠", "shāmò", "scha-mo (1.+4. Ton: hoch + fallend)", None, "Wörtl.: 'Sand-Wüste'"),
        ("春天", "chūntiān", "tschun-tien (1.+1. Ton: hoch + hoch)", None, "天 = Tag/Himmel"),
        ("夏天", "xiàtiān", "schja-tien (4.+1. Ton: fallend + hoch)", None, ""),
        ("秋天", "qiūtiān", "tschioh-tien (1.+1. Ton: hoch + hoch)", None, ""),
        ("冬天", "dōngtiān", "dong-tien (1.+1. Ton: hoch + hoch)", None, ""),
        ("空气", "kōngqì", "kong-tschi (1.+4. Ton: hoch + fallend)", None, ""),
        ("火", "huǒ", "chuo (3. Ton: fallend-steigend)", 3, ""),
        ("暴风雨", "bàofēngyǔ", "bau-föng-jü (4.+1.+3. Ton)", None, "Wörtl.: 'heftiger Wind-Regen'"),
        ("彩虹", "cǎihóng", "tsai-hong (3.+2. Ton: fallend-steigend + steigend)", None, ""),
        ("田", "tián", "tien (2. Ton: steigend)", 2, "Reisfeld"),
    ],
    "beruf_bildung": [
        ("老师", "lǎoshī", "lau-schii (3.+1. Ton: fallend-steigend + hoch)", None, "老 = alt/ehrwürdig"),
        ("学生", "xuéshēng", "schüe-schöng (2.+1. Ton: steigend + hoch)", None, "Wörtl.: 'Lern-Geborener'"),
        ("办公室", "bàngōngshì", "ban-gong-schii (4.+1.+4. Ton)", None, "Wörtl.: 'Angelegenheiten-Raum'"),
        ("电脑", "diànnǎo", "dien-nau (4.+3. Ton: fallend + fallend-steigend)", None, "Wörtl.: 'elektrisches Gehirn'"),
        ("大学", "dàxué", "da-schüe (4.+2. Ton: fallend + steigend)", None, "Wörtl.: 'großes Lernen'"),
        ("考试", "kǎoshì", "kau-schii (3.+4. Ton: fallend-steigend + fallend)", None, ""),
        ("职业", "zhíyè", "dschii-je (2.+4. Ton: steigend + fallend)", None, ""),
        ("老板", "lǎobǎn", "lau-ban (3.+3. Ton → 2.+3. Tonsandhi)", None, "Zwei 3. Töne: erster wird zu 2. Ton"),
        ("工资", "gōngzī", "gong-ds (1.+1. Ton: hoch + hoch)", None, ""),
        ("工程师", "gōngchéngshī", "gong-tschöng-schii (1.+2.+1. Ton)", None, ""),
        ("律师", "lǜshī", "lü-schii (4.+1. Ton: fallend + hoch)", None, "律 = Gesetz"),
        ("警察", "jǐngchá", "dsching-tscha (3.+2. Ton: fallend-steigend + steigend)", None, ""),
        ("科学", "kēxué", "kö-schüe (1.+2. Ton: hoch + steigend)", None, ""),
        ("数学", "shùxué", "schu-schüe (4.+2. Ton: fallend + steigend)", None, ""),
        ("历史", "lìshǐ", "li-schii (4.+3. Ton: fallend + fallend-steigend)", None, ""),
        ("语言", "yǔyán", "jü-jen (3.+2. Ton: fallend-steigend + steigend)", None, ""),
        ("图书馆", "túshūguǎn", "tu-schu-guan (2.+1.+3. Ton)", None, "Wörtl.: 'Bücher-Halle'"),
        ("班级", "bānjí", "ban-dschi (1.+2. Ton: hoch + steigend)", None, ""),
        ("学习", "xuéxí", "schüe-schi (2.+2. Ton: steigend + steigend)", None, ""),
        ("教", "jiāo", "dschiau (1. Ton: hoch und gleichbleibend)", 1, "Als Verb 'lehren'; auch jiào (4. Ton)"),
        ("任务", "rènwù", "rön-wu (4.+4. Ton: fallend + fallend)", None, ""),
        ("经验", "jīngyàn", "dsching-jen (1.+4. Ton: hoch + fallend)", None, ""),
        ("公司", "gōngsī", "gong-s (1.+1. Ton: hoch + hoch)", None, ""),
        ("项目", "xiàngmù", "schjang-mu (4.+4. Ton: fallend + fallend)", None, ""),
        ("会议", "huìyì", "huei-ii (4.+4. Ton: fallend + fallend)", None, ""),
    ],
}

# ===========================
# JAPANESE (ja)
# ===========================
TRANSLATIONS["japanese"] = {
    "koerper_gesundheit": [
        ("手", "te", "te (kurz)", None, ""),
        ("足", "ashi", "a-schi", None, "Auch 'Fuß'"),
        ("歯", "ha", "ha", None, ""),
        ("耳", "mimi", "mi-mi", None, "Verdoppelung"),
        ("鼻", "hana", "ha-na", None, "Auch 'Blume' (花)"),
        ("口", "kuchi", "ku-tschi", None, ""),
        ("指", "yubi", "ju-bi", None, ""),
        ("背中", "senaka", "se-na-ka", None, "背 = Rücken + 中 = Mitte"),
        ("腕", "ude", "u-de", None, ""),
        ("脚", "ashi", "a-schi", None, "Gleiche Aussprache wie 足 (Fuß)"),
        ("肌", "hada", "ha-da", None, ""),
        ("血", "chi", "tschi", None, ""),
        ("骨", "hone", "ho-ne", None, ""),
        ("病院", "byouin", "bjoo-in (langes o)", None, "病 = krank + 院 = Einrichtung"),
        ("薬", "kusuri", "ku-su-ri", None, ""),
        ("病気", "byouki", "bjoo-ki (langes o)", None, "病 = krank + 気 = Geist/Energie"),
        ("健康", "kenkou", "ken-koo (langes o)", None, "On-Lesung"),
        ("お腹", "onaka", "o-na-ka", None, "お = Höflichkeitspräfix"),
        ("医者", "isha", "i-scha", None, ""),
        ("痛み", "itami", "i-ta-mi", None, "Nomen von 痛い (itai = schmerzhaft)"),
        ("熱", "netsu", "ne-tsu", None, "Auch 'Hitze'"),
        ("咳", "seki", "se-ki", None, ""),
        ("薬局", "yakkyoku", "jak-kjo-ku (Doppel-k)", None, "薬 = Medizin + 局 = Amt"),
        ("舌", "shita", "schta", None, "Auch 'unter' (下)"),
        ("肩", "kata", "ka-ta", None, ""),
    ],
    "essen_trinken": [
        ("肉", "niku", "ni-ku", None, ""),
        ("魚", "sakana", "sa-ka-na", None, ""),
        ("ご飯", "gohan", "go-han", None, "ご = Höflichkeitspräfix; auch 'Mahlzeit'"),
        ("コーヒー", "koohii", "koo-hii (lange Vokale)", None, "Lehnwort (Katakana)"),
        ("お茶", "ocha", "o-tscha", None, "お = Höflichkeitspräfix"),
        ("ビール", "biiru", "bii-ru (langes i)", None, "Lehnwort (Katakana)"),
        ("ワイン", "wain", "wa-in", None, "Lehnwort (Katakana)"),
        ("スープ", "suupu", "suu-pu (langes u)", None, "Lehnwort (Katakana)"),
        ("野菜", "yasai", "ja-sai", None, "野 = Feld + 菜 = Gemüse"),
        ("果物", "kudamono", "ku-da-mo-no", None, ""),
        ("卵", "tamago", "ta-ma-go", None, ""),
        ("チーズ", "chiizu", "tschii-su (langes i)", None, "Lehnwort (Katakana)"),
        ("砂糖", "satou", "sa-too (langes o)", None, "砂 = Sand + 糖 = Zucker"),
        ("塩", "shio", "schi-o", None, ""),
        ("バター", "bataa", "ba-taa (langes a)", None, "Lehnwort (Katakana)"),
        ("油", "abura", "a-bu-ra", None, ""),
        ("じゃがいも", "jagaimo", "dscha-ga-i-mo", None, "Hiragana geschrieben"),
        ("鶏肉", "toriniku", "to-ri-ni-ku", None, "鶏 = Huhn + 肉 = Fleisch"),
        ("トマト", "tomato", "to-ma-to", None, "Lehnwort (Katakana)"),
        ("りんご", "ringo", "rin-go", None, "Oft in Hiragana geschrieben"),
        ("ケーキ", "keeki", "kee-ki (langes e)", None, "Lehnwort (Katakana)"),
        ("料理する", "ryouri suru", "rjoo-ri su-ru", None, "料理 = Kochen/Gericht + する = tun"),
        ("レストラン", "resutoran", "re-su-to-ran", None, "Lehnwort (Katakana)"),
        ("朝ご飯", "asagohan", "a-sa-go-han", None, "朝 = Morgen + ご飯 = Essen"),
        ("晩ご飯", "bangohan", "ban-go-han", None, "晩 = Abend + ご飯 = Essen"),
    ],
    "natur_wetter": [
        ("森", "mori", "mo-ri", None, ""),
        ("空", "sora", "so-ra", None, "Auch 'leer' (から/kara)"),
        ("星", "hoshi", "ho-schi", None, ""),
        ("地球", "chikyuu", "tschi-kjuu (langes u)", None, "地 = Erde + 球 = Kugel"),
        ("風", "kaze", "ka-se", None, ""),
        ("雲", "kumo", "ku-mo", None, "Auch 'Spinne' (蜘蛛)"),
        ("雷", "kaminari", "ka-mi-na-ri", None, "Wörtl.: 'Gottes Donner'"),
        ("島", "shima", "schi-ma", None, ""),
        ("湖", "mizuumi", "mi-su-u-mi (langes u)", None, "Wörtl.: 'Wasser-Meer'"),
        ("草", "kusa", "ku-sa", None, ""),
        ("石", "ishi", "i-schi", None, ""),
        ("砂", "suna", "su-na", None, ""),
        ("氷", "koori", "koo-ri (langes o)", None, ""),
        ("霧", "kiri", "ki-ri", None, ""),
        ("浜", "hama", "ha-ma", None, "Auch in Ortsnamen: 横浜 (Yokohama)"),
        ("砂漠", "sabaku", "sa-ba-ku", None, "砂 = Sand + 漠 = Wüste"),
        ("春", "haru", "ha-ru", None, ""),
        ("夏", "natsu", "na-tsu", None, ""),
        ("秋", "aki", "a-ki", None, ""),
        ("冬", "fuyu", "fu-ju", None, ""),
        ("空気", "kuuki", "kuu-ki (langes u)", None, "空 = leer + 気 = Energie"),
        ("火", "hi", "hi", None, "Auch 'Tag' (日)"),
        ("嵐", "arashi", "a-ra-schi", None, ""),
        ("虹", "niji", "ni-dschi", None, ""),
        ("畑", "hatake", "ha-ta-ke", None, "Speziell für Trockenfelder"),
    ],
    "beruf_bildung": [
        ("先生", "sensei", "sen-sei", None, "Auch Anrede für Ärzte, Anwälte etc."),
        ("学生", "gakusei", "ga-ku-sei", None, "学 = lernen + 生 = geboren"),
        ("オフィス", "ofisu", "o-fi-su", None, "Lehnwort (Katakana)"),
        ("パソコン", "pasokon", "pa-so-kon", None, "Abk. von パーソナルコンピューター"),
        ("大学", "daigaku", "dai-ga-ku", None, "大 = groß + 学 = lernen"),
        ("試験", "shiken", "schi-ken", None, ""),
        ("職業", "shokugyou", "scho-ku-gjoo (langes o)", None, ""),
        ("上司", "joushi", "dscho-u-schi", None, "上 = oben + 司 = leiten"),
        ("給料", "kyuuryou", "kjuu-rjoo (lange Vokale)", None, ""),
        ("エンジニア", "enjinia", "en-dschi-ni-a", None, "Lehnwort (Katakana)"),
        ("弁護士", "bengoshi", "ben-go-schi", None, "弁 = sprechen + 護 = schützen + 士 = Meister"),
        ("警察官", "keisatsukan", "kei-sa-tsu-kan", None, "警察 = Polizei + 官 = Beamter"),
        ("科学", "kagaku", "ka-ga-ku", None, "科 = Fach + 学 = Lehre"),
        ("数学", "suugaku", "suu-ga-ku (langes u)", None, "数 = Zahl + 学 = Lehre"),
        ("歴史", "rekishi", "re-ki-schi", None, ""),
        ("言語", "gengo", "gen-go", None, "言 = Wort + 語 = Sprache"),
        ("図書館", "toshokan", "to-scho-kan", None, "図書 = Bücher + 館 = Gebäude"),
        ("クラス", "kurasu", "ku-ra-su", None, "Lehnwort (Katakana)"),
        ("勉強する", "benkyou suru", "ben-kjoo su-ru (langes o)", None, "勉強 = Studium + する = tun"),
        ("教える", "oshieru", "o-schi-e-ru", None, "Ichidan-Verb"),
        ("課題", "kadai", "ka-dai", None, "課 = Lektion + 題 = Thema"),
        ("経験", "keiken", "kei-ken", None, ""),
        ("会社", "kaisha", "kai-scha", None, "会 = treffen + 社 = Gesellschaft"),
        ("プロジェクト", "purojekuto", "pu-ro-dsche-ku-to", None, "Lehnwort (Katakana)"),
        ("会議", "kaigi", "kai-gi", None, "会 = treffen + 議 = beraten"),
    ],
}

# ===========================
# KOREAN (ko)
# ===========================
TRANSLATIONS["korean"] = {
    "koerper_gesundheit": [
        ("손", "son", "son", None, ""),
        ("발", "bal", "bal", None, ""),
        ("이", "i", "i", None, "Auch 치아 (chia) formell"),
        ("귀", "gwi", "gwi (g wie in 'gut')", None, ""),
        ("코", "ko", "ko", None, ""),
        ("입", "ip", "ip", None, "p wird am Silbenende nicht losgelassen"),
        ("손가락", "songarak", "son-ga-rak", None, "손 = Hand + 가락 = Streifen"),
        ("등", "deung", "döng", None, ""),
        ("팔", "pal", "pal", None, ""),
        ("다리", "dari", "da-ri", None, ""),
        ("피부", "pibu", "pi-bu", None, ""),
        ("피", "pi", "pi", None, ""),
        ("뼈", "ppyeo", "ppjö (Doppel-p: gespannter Laut)", None, "ㅃ = gespanntes p"),
        ("병원", "byeongwon", "bjöng-won", None, ""),
        ("약", "yak", "jak", None, ""),
        ("아픈", "apeun", "a-pön", None, "Adjektivform von 아프다 (apeuda)"),
        ("건강한", "geonganghan", "gön-gang-han", None, "건강 + 한 (Adjektivsuffix)"),
        ("배", "bae", "bä", None, "Auch 'Schiff' und 'Birne'"),
        ("의사", "uisa", "üi-sa", None, "ㅢ = spezieller Diphthong"),
        ("통증", "tongjeung", "tong-dschöng", None, ""),
        ("열", "yeol", "jöl", None, "Auch 'zehn' in sino-koreanisch"),
        ("기침", "gichim", "gi-tschim", None, ""),
        ("약국", "yakguk", "jak-guk", None, "약 = Medizin + 국 = Amt"),
        ("혀", "hyeo", "hjö", None, ""),
        ("어깨", "eokkae", "ök-kä (Doppel-k)", None, ""),
    ],
    "essen_trinken": [
        ("고기", "gogi", "go-gi", None, ""),
        ("생선", "saengseon", "säng-sön", None, "Fisch (als Essen)"),
        ("밥", "bap", "bap", None, "Auch 'Mahlzeit'"),
        ("커피", "keopi", "kö-pi", None, "Lehnwort"),
        ("차", "cha", "tscha", None, "Auch 'Auto' (車)"),
        ("맥주", "maekju", "mäk-dschu", None, ""),
        ("포도주", "podoju", "po-do-dschu", None, "포도 = Traube + 주 = Alkohol"),
        ("국", "guk", "guk", None, "Auch Suppe im weiteren Sinne"),
        ("채소", "chaeso", "tschä-so", None, ""),
        ("과일", "gwail", "gwa-il", None, ""),
        ("달걀", "dalgyal", "dal-gjal", None, ""),
        ("치즈", "chijeu", "tschi-dsö", None, "Lehnwort"),
        ("설탕", "seoltang", "söl-tang", None, ""),
        ("소금", "sogeum", "so-göm", None, ""),
        ("버터", "beoteo", "bö-tö", None, "Lehnwort"),
        ("기름", "gireum", "gi-röm", None, ""),
        ("감자", "gamja", "gam-dscha", None, ""),
        ("닭고기", "dakgogi", "dak-go-gi", None, "닭 = Huhn + 고기 = Fleisch"),
        ("토마토", "tomato", "to-ma-to", None, "Lehnwort"),
        ("사과", "sagwa", "sa-gwa", None, "Auch 'Entschuldigung'"),
        ("케이크", "keikeu", "kei-kö", None, "Lehnwort"),
        ("요리하다", "yorihada", "jo-ri-ha-da", None, "요리 = Kochen + 하다 = tun"),
        ("식당", "sikdang", "sik-dang", None, ""),
        ("아침", "achim", "a-tschim", None, "Auch 'Morgen'"),
        ("저녁", "jeonyeok", "dschö-njök", None, "Auch 'Abend'"),
    ],
    "natur_wetter": [
        ("숲", "sup", "sup", None, ""),
        ("하늘", "haneul", "ha-nöl", None, ""),
        ("별", "byeol", "bjöl", None, ""),
        ("지구", "jigu", "dschi-gu", None, ""),
        ("바람", "baram", "ba-ram", None, ""),
        ("구름", "gureum", "gu-röm", None, ""),
        ("천둥", "cheondung", "tschön-dung", None, ""),
        ("섬", "seom", "söm", None, ""),
        ("호수", "hosu", "ho-su", None, ""),
        ("풀", "pul", "pul", None, ""),
        ("돌", "dol", "dol", None, ""),
        ("모래", "morae", "mo-rä", None, ""),
        ("얼음", "eoreum", "ö-röm", None, ""),
        ("안개", "angae", "an-gä", None, ""),
        ("해변", "haebyeon", "hä-bjön", None, "해 = Meer + 변 = Seite"),
        ("사막", "samak", "sa-mak", None, ""),
        ("봄", "bom", "bom", None, ""),
        ("여름", "yeoreum", "jö-röm", None, ""),
        ("가을", "gaeul", "ga-öl", None, ""),
        ("겨울", "gyeoul", "gjö-ul", None, ""),
        ("공기", "gonggi", "gong-gi", None, ""),
        ("불", "bul", "bul", None, ""),
        ("폭풍", "pokpung", "pok-pung (aspiriertes p)", None, ""),
        ("무지개", "mujigae", "mu-dschi-gä", None, ""),
        ("밭", "bat", "bat", None, "Trockenfeld"),
    ],
    "beruf_bildung": [
        ("선생님", "seonsaengnim", "sön-säng-nim", None, "Ehrende Anrede für Lehrer"),
        ("학생", "haksaeng", "hak-säng", None, ""),
        ("사무실", "samusil", "sa-mu-schil", None, ""),
        ("컴퓨터", "keompyuteo", "köm-pju-tö", None, "Lehnwort"),
        ("대학교", "daehakgyo", "dä-hak-gjo", None, "대 = groß + 학 = lernen + 교 = Schule"),
        ("시험", "siheom", "schi-höm", None, ""),
        ("직업", "jigeop", "dschi-göp", None, ""),
        ("사장", "sajang", "sa-dschang", None, "Firmenchef"),
        ("월급", "wolgeup", "wol-göp", None, "월 = Monat + 급 = Zahlung"),
        ("엔지니어", "enjinieo", "en-dschi-ni-ö", None, "Lehnwort"),
        ("변호사", "byeonhosa", "bjön-ho-sa", None, ""),
        ("경찰", "gyeongchal", "gjöng-tschal", None, ""),
        ("과학", "gwahak", "gwa-hak", None, ""),
        ("수학", "suhak", "su-hak", None, ""),
        ("역사", "yeoksa", "jök-sa", None, ""),
        ("언어", "eoneo", "ön-ö", None, ""),
        ("도서관", "doseogwan", "do-sö-gwan", None, ""),
        ("반", "ban", "ban", None, ""),
        ("공부하다", "gongbuhada", "gong-bu-ha-da", None, "공부 = Studium + 하다 = tun"),
        ("가르치다", "gareuchida", "ga-rö-tschi-da", None, ""),
        ("과제", "gwaje", "gwa-dsche", None, ""),
        ("경험", "gyeongheom", "gjöng-höm", None, ""),
        ("회사", "hoesa", "hwä-sa", None, ""),
        ("프로젝트", "peurojekteu", "pö-ro-dschek-tö", None, "Lehnwort"),
        ("회의", "hoeui", "hwä-üi", None, ""),
    ],
}

# ===========================
# VIETNAMESE (vi)
# ===========================
# Vietnamese tones: 1=ngang(level), 2=sắc(rising), 3=huyền(falling),
#                   4=hỏi(dipping), 5=ngã(broken), 6=nặng(heavy)
TRANSLATIONS["vietnamese"] = {
    "koerper_gesundheit": [
        ("tay", "tay", "tai (Ngang-Ton, eben)", 1, ""),
        ("chân", "chân", "tschön (Ngang-Ton, eben)", 1, "Auch 'Bein'"),
        ("răng", "răng", "rang (Nặng-Ton kurzer Vokal ă)", 1, "ă = kurzes a"),
        ("tai", "tai", "tai (Ngang-Ton, eben)", 1, ""),
        ("mũi", "mũi", "mui (Ngã-Ton: gebrochen, steigend mit Glottisschlag)", 5, ""),
        ("miệng", "miệng", "miöng (Nặng-Ton: tief, schwer)", 6, ""),
        ("ngón tay", "ngón tay", "ngon tai (ng wie in 'singen'; Sắc-Ton + Ngang)", None, "ngón = Finger/Zehe"),
        ("lưng", "lưng", "lung (ư = hinteres u, Lippen nicht gerundet)", 1, "ư ist ein spezieller Vokal"),
        ("cánh tay", "cánh tay", "kaing tai (Sắc-Ton + Ngang)", None, "cánh = Flügel/Arm"),
        ("chân", "chân", "tschön (Ngang-Ton, eben)", 1, "Im Vietnamesischen gleich wie 'Fuß'"),
        ("da", "da", "ja (Ngang-Ton, eben)", 1, ""),
        ("máu", "máu", "mau (Sắc-Ton: steigend)", 2, ""),
        ("xương", "xương", "suöng (ươ = spezieller Diphthong; Ngang-Ton)", 1, "x = s"),
        ("bệnh viện", "bệnh viện", "böng wien (Nặng-Ton + Nặng-Ton)", None, ""),
        ("thuốc", "thuốc", "tuok (Sắc-Ton: steigend)", 2, "Auch 'Medikament'"),
        ("ốm", "ốm", "om (Sắc-Ton: steigend)", 2, "Nordvietnam; Süden: bệnh"),
        ("khỏe mạnh", "khỏe mạnh", "kwä mang (Hỏi-Ton + Nặng-Ton)", None, "khỏe = fit + mạnh = stark"),
        ("bụng", "bụng", "bung (Nặng-Ton: tief, schwer)", 6, ""),
        ("bác sĩ", "bác sĩ", "bak sii (Sắc-Ton + Ngã-Ton)", None, ""),
        ("đau", "đau", "dau (đ = hartes d; Ngang-Ton)", 1, "đ = stimmhafter Verschlusslaut"),
        ("sốt", "sốt", "sot (Sắc-Ton: steigend)", 2, ""),
        ("ho", "ho", "ho (Ngang-Ton, eben)", 1, ""),
        ("nhà thuốc", "nhà thuốc", "nja tuok (Huyền-Ton + Sắc-Ton)", None, "nhà = Haus + thuốc = Medizin"),
        ("lưỡi", "lưỡi", "lui (ư = hinteres u; Ngã-Ton: gebrochen)", 5, ""),
        ("vai", "vai", "wai (Ngang-Ton, eben)", 1, ""),
    ],
    "essen_trinken": [
        ("thịt", "thịt", "tit (th = aspiriertes t; Nặng-Ton)", 6, ""),
        ("cá", "cá", "ka (Sắc-Ton: steigend)", 2, ""),
        ("cơm", "cơm", "köm (ơ = offenes ö; Ngang-Ton)", 1, ""),
        ("cà phê", "cà phê", "ka fe (Huyền-Ton + Ngang-Ton)", None, "Lehnwort aus dem Französischen"),
        ("trà", "trà", "tscha (Huyền-Ton: fallend)", 3, ""),
        ("bia", "bia", "bia (Ngang-Ton, eben)", 1, "Lehnwort"),
        ("rượu vang", "rượu vang", "ruöu wang (Nặng-Ton + Ngang)", None, "rượu = Alkohol"),
        ("súp", "súp", "sup (Sắc-Ton: steigend)", 2, "Lehnwort"),
        ("rau", "rau", "rau (Ngang-Ton, eben)", 1, ""),
        ("trái cây", "trái cây", "tschai köi (Sắc-Ton + Ngang)", None, ""),
        ("trứng", "trứng", "tschung (Sắc-Ton: steigend)", 2, ""),
        ("phô mai", "phô mai", "fo mai (Ngang-Ton + Ngang)", None, "Lehnwort aus dem Französischen (fromage)"),
        ("đường", "đường", "duöng (đ = hartes d; Huyền-Ton: fallend)", 3, "Auch 'Straße'"),
        ("muối", "muối", "muoi (Sắc-Ton: steigend)", 2, ""),
        ("bơ", "bơ", "bö (ơ = offenes ö; Ngang-Ton)", 1, "Lehnwort aus dem Französischen (beurre)"),
        ("dầu", "dầu", "jau (Huyền-Ton: fallend)", 3, ""),
        ("khoai tây", "khoai tây", "kwai töi (Ngang + Ngang)", None, "Wörtl.: 'westliche Knolle'"),
        ("thịt gà", "thịt gà", "tit ga (Nặng-Ton + Huyền-Ton)", None, "thịt = Fleisch + gà = Huhn"),
        ("cà chua", "cà chua", "ka tschua (Huyền-Ton + Ngang)", None, "Wörtl.: 'saure Aubergine'"),
        ("táo", "táo", "tau (Sắc-Ton: steigend)", 2, ""),
        ("bánh ngọt", "bánh ngọt", "bang ngot (Sắc-Ton + Nặng-Ton)", None, "bánh = Kuchen + ngọt = süß"),
        ("nấu ăn", "nấu ăn", "nau an (Hỏi-Ton + Ngang)", None, "nấu = kochen + ăn = essen"),
        ("nhà hàng", "nhà hàng", "nja hang (Huyền-Ton + Huyền-Ton)", None, "nhà = Haus + hàng = Waren"),
        ("bữa sáng", "bữa sáng", "bua sang (Ngã-Ton + Sắc-Ton)", None, "bữa = Mahlzeit + sáng = Morgen"),
        ("bữa tối", "bữa tối", "bua toi (Ngã-Ton + Sắc-Ton)", None, "bữa = Mahlzeit + tối = Abend"),
    ],
    "natur_wetter": [
        ("rừng", "rừng", "rung (Huyền-Ton: fallend)", 3, ""),
        ("bầu trời", "bầu trời", "böu tschöi (Huyền-Ton + Huyền-Ton)", None, ""),
        ("ngôi sao", "ngôi sao", "ngoi sau (Ngang + Ngang)", None, "ngôi = Zähler + sao = Stern"),
        ("trái đất", "trái đất", "tschai döt (Sắc-Ton + Sắc-Ton)", None, "trái = Kugel + đất = Erde"),
        ("gió", "gió", "jo (Sắc-Ton: steigend)", 2, ""),
        ("mây", "mây", "möi (Ngang-Ton, eben)", 1, ""),
        ("sấm", "sấm", "söm (Sắc-Ton: steigend)", 2, ""),
        ("đảo", "đảo", "dau (đ = hartes d; Hỏi-Ton: fallend-steigend)", 4, ""),
        ("hồ", "hồ", "ho (Huyền-Ton: fallend)", 3, ""),
        ("cỏ", "cỏ", "ko (Hỏi-Ton: fallend-steigend)", 4, ""),
        ("đá", "đá", "da (đ = hartes d; Sắc-Ton: steigend)", 2, "Auch 'Eis' (in Getränken)"),
        ("cát", "cát", "kat (Sắc-Ton: steigend)", 2, ""),
        ("băng", "băng", "bang (ă = kurzes a; Ngang-Ton)", 1, ""),
        ("sương mù", "sương mù", "suöng mu (Ngang + Huyền-Ton)", None, ""),
        ("bãi biển", "bãi biển", "bai bien (Ngã-Ton + Hỏi-Ton)", None, "bãi = Platz + biển = Meer"),
        ("sa mạc", "sa mạc", "sa mak (Ngang + Nặng-Ton)", None, ""),
        ("mùa xuân", "mùa xuân", "mua swan (Huyền-Ton + Ngang)", None, "mùa = Jahreszeit"),
        ("mùa hè", "mùa hè", "mua he (Huyền-Ton + Huyền-Ton)", None, ""),
        ("mùa thu", "mùa thu", "mua tu (Huyền-Ton + Ngang)", None, ""),
        ("mùa đông", "mùa đông", "mua dong (Huyền-Ton + Ngang)", None, ""),
        ("không khí", "không khí", "kong ki (Ngang + Sắc-Ton)", None, ""),
        ("lửa", "lửa", "lua (Hỏi-Ton: fallend-steigend)", 4, ""),
        ("bão", "bão", "bau (Ngã-Ton: gebrochen)", 5, ""),
        ("cầu vồng", "cầu vồng", "köu wong (Huyền-Ton + Huyền-Ton)", None, ""),
        ("cánh đồng", "cánh đồng", "kaing dong (Sắc-Ton + Huyền-Ton)", None, "cánh = Flügel/Fläche"),
    ],
    "beruf_bildung": [
        ("giáo viên", "giáo viên", "jau wien (Sắc-Ton + Ngang)", None, ""),
        ("học sinh", "học sinh", "hok sing (Nặng-Ton + Ngang)", None, "học = lernen + sinh = geboren"),
        ("văn phòng", "văn phòng", "wan fong (Ngang + Huyền-Ton)", None, ""),
        ("máy tính", "máy tính", "mai ting (Sắc-Ton + Sắc-Ton)", None, "máy = Maschine + tính = rechnen"),
        ("đại học", "đại học", "dai hok (Nặng-Ton + Nặng-Ton)", None, "đại = groß + học = lernen"),
        ("kỳ thi", "kỳ thi", "ki ti (Huyền-Ton + Ngang)", None, ""),
        ("nghề nghiệp", "nghề nghiệp", "ngä ngiep (Huyền-Ton + Nặng-Ton)", None, "ngh = ng vor e/ê/i"),
        ("sếp", "sếp", "sep (Sắc-Ton: steigend)", 2, "Lehnwort (aus 'chef')"),
        ("lương", "lương", "luöng (Ngang-Ton, eben)", 1, ""),
        ("kỹ sư", "kỹ sư", "ki su (Ngã-Ton + Ngang)", None, ""),
        ("luật sư", "luật sư", "luat su (Nặng-Ton + Ngang)", None, "luật = Gesetz + sư = Meister"),
        ("cảnh sát", "cảnh sát", "kang sat (Hỏi-Ton + Sắc-Ton)", None, ""),
        ("khoa học", "khoa học", "kwa hok (Ngang + Nặng-Ton)", None, ""),
        ("toán học", "toán học", "twan hok (Sắc-Ton + Nặng-Ton)", None, ""),
        ("lịch sử", "lịch sử", "lik su (Nặng-Ton + Hỏi-Ton)", None, ""),
        ("ngôn ngữ", "ngôn ngữ", "ngon ngu (Ngang + Ngã-Ton)", None, ""),
        ("thư viện", "thư viện", "tu wien (Ngang + Nặng-Ton)", None, "thư = Brief/Buch + viện = Institut"),
        ("lớp", "lớp", "löp (ơ = offenes ö; Sắc-Ton)", 2, ""),
        ("học", "học", "hok (Nặng-Ton: tief, schwer)", 6, ""),
        ("dạy", "dạy", "jai (Nặng-Ton: tief, schwer)", 6, ""),
        ("nhiệm vụ", "nhiệm vụ", "njiem wu (Nặng-Ton + Nặng-Ton)", None, ""),
        ("kinh nghiệm", "kinh nghiệm", "king ngiem (Ngang + Nặng-Ton)", None, ""),
        ("công ty", "công ty", "kong ti (Ngang + Ngang)", None, ""),
        ("dự án", "dự án", "ju an (Nặng-Ton + Sắc-Ton)", None, ""),
        ("cuộc họp", "cuộc họp", "kuok hop (Nặng-Ton + Nặng-Ton)", None, ""),
    ],
}

# ===========================
# HUNGARIAN (hu)
# ===========================
TRANSLATIONS["hungarian"] = {
    "koerper_gesundheit": [
        ("kéz", "kéz", "keez (é = langes e; Betonung auf 1. Silbe)", None, ""),
        ("láb", "láb", "laab (á = langes a, offener als dt. a)", None, "Auch 'Bein'"),
        ("fog", "fog", "fog (kurzes o)", None, "Auch 'fangen' (Verb)"),
        ("fül", "fül", "fül (ü wie dt. 'Tür')", None, ""),
        ("orr", "orr", "orr (gerolltes r)", None, "Doppel-r = langes r"),
        ("száj", "száj", "saaj (sz = s wie dt. 'Sonne'; á = langes a)", None, "sz = stimmloser s-Laut"),
        ("ujj", "ujj", "ujj (langes j)", None, ""),
        ("hát", "hát", "haat (á = langes a)", None, "Auch 'also/denn'"),
        ("kar", "kar", "kar", None, ""),
        ("láb", "láb", "laab (á = langes a)", None, "Im Ungarischen gleich wie 'Fuß'"),
        ("bőr", "bőr", "bör (ő = langes ö)", None, "ő = langes ö"),
        ("vér", "vér", "weer (é = langes e, v = w)", None, "v wird wie dt. w gesprochen"),
        ("csont", "csont", "tschont (cs = tsch)", None, "cs = tsch-Laut"),
        ("kórház", "kórház", "koor-haas (ó = langes o; á = langes a)", None, "kór = Krankheit + ház = Haus"),
        ("gyógyszer", "gyógyszer", "djoodj-ser (gy = stimmhaftes dj; ó = langes o)", None, "gyógy = heilen + szer = Mittel"),
        ("beteg", "beteg", "be-teg", None, ""),
        ("egészséges", "egészséges", "e-gees-shee-gesch (sz = s; s = sch)", None, "egész = ganz + séges = Suffix"),
        ("has", "has", "hasch (s = sch im Ungarischen!)", None, "s = sch-Laut"),
        ("orvos", "orvos", "or-wosch (v = w; s = sch)", None, ""),
        ("fájdalom", "fájdalom", "faaj-da-lom (á = langes a)", None, ""),
        ("láz", "láz", "laas (á = langes a)", None, ""),
        ("köhögés", "köhögés", "kö-hö-geesch (ö kurz; é = langes e; s = sch)", None, ""),
        ("gyógyszertár", "gyógyszertár", "djoodj-ser-taar (gy = dj; á = langes a)", None, "Wörtl.: 'Heilmittel-Lager'"),
        ("nyelv", "nyelv", "njelw (ny = nj wie span. ñ; v = w)", None, "Auch 'Sprache'"),
        ("váll", "váll", "wall (á = langes a; ll = langes l)", None, ""),
    ],
    "essen_trinken": [
        ("hús", "hús", "huusch (ú = langes u; s = sch)", None, ""),
        ("hal", "hal", "hal", None, ""),
        ("rizs", "rizs", "risch (zs = sch/zh wie frz. 'j')", None, "zs = stimmhaftes sch"),
        ("kávé", "kávé", "kaa-wee (á = langes a; é = langes e)", None, ""),
        ("tea", "tea", "te-a", None, ""),
        ("sör", "sör", "schör (s = sch)", None, ""),
        ("bor", "bor", "bor", None, ""),
        ("leves", "leves", "le-wesch (v = w; s = sch)", None, ""),
        ("zöldség", "zöldség", "söld-scheeg (z = stimmhaftes s; s = sch)", None, "zöld = grün"),
        ("gyümölcs", "gyümölcs", "djü-möltsch (gy = dj; cs = tsch)", None, ""),
        ("tojás", "tojás", "to-jaasch (á = langes a; s = sch)", None, ""),
        ("sajt", "sajt", "schajt (s = sch)", None, ""),
        ("cukor", "cukor", "tsu-kor (c = ts)", None, "c = ts-Laut"),
        ("só", "só", "schoo (s = sch; ó = langes o)", None, ""),
        ("vaj", "vaj", "waj (v = w)", None, ""),
        ("olaj", "olaj", "o-laj", None, ""),
        ("krumpli", "krumpli", "krum-pli", None, "Umgangssprachlich; formell: burgonya"),
        ("csirke", "csirke", "tschir-ke (cs = tsch)", None, ""),
        ("paradicsom", "paradicsom", "pa-ra-di-tschom (cs = tsch)", None, "Aus dem Lateinischen (paradies)"),
        ("alma", "alma", "al-ma", None, ""),
        ("sütemény", "sütemény", "schü-te-meenj (s = sch; ny = nj; é = langes e)", None, ""),
        ("főzni", "főzni", "fös-ni (ő = langes ö; z = stimmhaftes s)", None, "Infinitivform"),
        ("étterem", "étterem", "eet-te-rem (é = langes e; tt = langes t)", None, ""),
        ("reggeli", "reggeli", "reg-ge-li (gg = langes g)", None, "Auch 'morgens'"),
        ("vacsora", "vacsora", "wa-tscho-ra (v = w; cs = tsch)", None, ""),
    ],
    "natur_wetter": [
        ("erdő", "erdő", "er-dö (ő = langes ö)", None, ""),
        ("ég", "ég", "eeg (é = langes e)", None, "Auch 'brennen' (Verb)"),
        ("csillag", "csillag", "tschil-lag (cs = tsch; ll = langes l)", None, ""),
        ("föld", "föld", "föld", None, ""),
        ("szél", "szél", "seel (sz = stimmloser s; é = langes e)", None, ""),
        ("felhő", "felhő", "fel-hö (ő = langes ö)", None, ""),
        ("mennydörgés", "mennydörgés", "menj-dör-geesch (ny = nj; é = langes e; s = sch)", None, ""),
        ("sziget", "sziget", "si-get (sz = s; g = hart)", None, ""),
        ("tó", "tó", "too (ó = langes o)", None, ""),
        ("fű", "fű", "fü (ű = langes ü)", None, "ű = extra langes ü"),
        ("kő", "kő", "kö (ő = langes ö)", None, ""),
        ("homok", "homok", "ho-mok", None, ""),
        ("jég", "jég", "jeeg (é = langes e)", None, ""),
        ("köd", "köd", "köd", None, ""),
        ("strand", "strand", "schtrand (s = sch)", None, "Lehnwort"),
        ("sivatag", "sivatag", "schi-wa-tag (s = sch; v = w)", None, ""),
        ("tavasz", "tavasz", "ta-was (v = w; sz = s)", None, ""),
        ("nyár", "nyár", "njaar (ny = nj; á = langes a)", None, ""),
        ("ősz", "ősz", "ös (ő = langes ö; sz = s)", None, ""),
        ("tél", "tél", "teel (é = langes e)", None, ""),
        ("levegő", "levegő", "le-we-gö (v = w; ő = langes ö)", None, ""),
        ("tűz", "tűz", "tüs (ű = langes ü; z = stimmhaftes s)", None, ""),
        ("vihar", "vihar", "wi-har (v = w)", None, ""),
        ("szivárvány", "szivárvány", "si-waar-waanj (sz = s; v = w; á = langes a; ny = nj)", None, ""),
        ("mező", "mező", "me-sö (z = stimmhaftes s; ő = langes ö)", None, ""),
    ],
    "beruf_bildung": [
        ("tanár", "tanár", "ta-naar (á = langes a)", None, ""),
        ("diák", "diák", "di-aak (á = langes a)", None, ""),
        ("iroda", "iroda", "i-ro-da", None, ""),
        ("számítógép", "számítógép", "saa-mii-too-geep (sz = s; á,í,ó,é = lang)", None, "Wörtl.: 'Rechenmaschine'"),
        ("egyetem", "egyetem", "e-dje-tem (gy = dj)", None, ""),
        ("vizsga", "vizsga", "wisch-ga (v = w; zs = stimmhaftes sch)", None, ""),
        ("szakma", "szakma", "sak-ma (sz = s)", None, ""),
        ("főnök", "főnök", "fö-nök (ő = langes ö)", None, ""),
        ("fizetés", "fizetés", "fi-se-teesch (z = stimmhaftes s; é = langes e; s = sch)", None, ""),
        ("mérnök", "mérnök", "meer-nök (é = langes e)", None, ""),
        ("ügyvéd", "ügyvéd", "üdj-weed (gy = dj; v = w; é = langes e)", None, "ügy = Angelegenheit + véd = verteidigen"),
        ("rendőr", "rendőr", "ren-dör (ő = langes ö)", None, ""),
        ("tudomány", "tudomány", "tu-do-maanj (á = langes a; ny = nj)", None, ""),
        ("matematika", "matematika", "ma-te-ma-ti-ka", None, ""),
        ("történelem", "történelem", "tör-tee-ne-lem (é = langes e)", None, ""),
        ("nyelv", "nyelv", "njelw (ny = nj; v = w)", None, "Auch 'Zunge'"),
        ("könyvtár", "könyvtár", "könjw-taar (ny = nj; v = w; á = langes a)", None, "könyv = Buch + tár = Lager"),
        ("osztály", "osztály", "os-taaj (sz = s; á = langes a; ly = j)", None, "ly = j-Laut"),
        ("tanulni", "tanulni", "ta-nul-ni", None, "Infinitivform"),
        ("tanítani", "tanítani", "ta-nii-ta-ni (í = langes i)", None, "Infinitivform"),
        ("feladat", "feladat", "fe-la-dat", None, "fel = auf + adat = Daten"),
        ("tapasztalat", "tapasztalat", "ta-pas-ta-lat (sz = s)", None, ""),
        ("vállalat", "vállalat", "waal-la-lat (v = w; á = langes a; ll = langes l)", None, ""),
        ("projekt", "projekt", "pro-jekt", None, "Lehnwort"),
        ("megbeszélés", "megbeszélés", "meg-be-see-leesch (sz = s; é = langes e; s = sch)", None, "meg = Präfix + beszél = sprechen"),
    ],
}

# ===========================
# FINNISH (fi)
# ===========================
TRANSLATIONS["finnish"] = {
    "koerper_gesundheit": [
        ("käsi", "käsi", "käsi (ä wie dt. 'Bär'; Betonung auf 1. Silbe)", None, ""),
        ("jalka", "jalka", "jal-ka (j wie dt. j)", None, "Auch 'Bein'"),
        ("hammas", "hammas", "ham-mas (Doppel-m = langer Konsonant)", None, "Stamm: hampaa-"),
        ("korva", "korva", "kor-wa (v = w-ähnlich)", None, ""),
        ("nenä", "nenä", "ne-nä (ä wie dt. 'Bär')", None, ""),
        ("suu", "suu", "suu (langes u)", None, "Doppelvokal = langer Vokal"),
        ("sormi", "sormi", "sor-mi", None, ""),
        ("selkä", "selkä", "sel-kä (ä wie dt. 'Bär')", None, ""),
        ("käsivarsi", "käsivarsi", "kä-si-war-si (ä wie 'Bär'; Betonung auf 1. Silbe)", None, "käsi = Hand + varsi = Stiel"),
        ("jalka", "jalka", "jal-ka", None, "Im Finnischen gleich wie 'Fuß'"),
        ("iho", "iho", "i-ho", None, ""),
        ("veri", "veri", "we-ri (v = w-ähnlich)", None, ""),
        ("luu", "luu", "luu (langes u)", None, ""),
        ("sairaala", "sairaala", "sai-raa-la (langes a)", None, "sairas = krank"),
        ("lääke", "lääke", "lää-ke (langes ä)", None, ""),
        ("sairas", "sairas", "sai-ras", None, ""),
        ("terve", "terve", "ter-we (v = w-ähnlich)", None, "Auch Begrüßung 'Hallo'"),
        ("vatsa", "vatsa", "wat-sa (v = w-ähnlich)", None, ""),
        ("lääkäri", "lääkäri", "lää-kä-ri (langes ä + kurzes ä)", None, "lääke = Medizin → lääkäri"),
        ("kipu", "kipu", "ki-pu", None, ""),
        ("kuume", "kuume", "kuu-me (langes u)", None, ""),
        ("yskä", "yskä", "üs-kä (y = ü wie dt. 'über')", None, "y = ü-Laut"),
        ("apteekki", "apteekki", "ap-teek-ki (langes e + Doppel-k)", None, ""),
        ("kieli", "kieli", "kie-li", None, "Auch 'Sprache'"),
        ("olkapää", "olkapää", "ol-ka-pää (langes ä)", None, "olka = Schulter + pää = Kopf/Ende"),
    ],
    "essen_trinken": [
        ("liha", "liha", "li-ha", None, ""),
        ("kala", "kala", "ka-la", None, ""),
        ("riisi", "riisi", "rii-si (langes i)", None, ""),
        ("kahvi", "kahvi", "kah-wi (v = w-ähnlich)", None, ""),
        ("tee", "tee", "tee (langes e)", None, ""),
        ("olut", "olut", "o-lut", None, ""),
        ("viini", "viini", "wii-ni (v = w; langes i)", None, ""),
        ("keitto", "keitto", "keit-to (Doppel-t)", None, ""),
        ("vihannekset", "vihannekset", "wi-han-nek-set (v = w; Doppel-n)", None, "Plural; Singular: vihannes"),
        ("hedelmä", "hedelmä", "he-del-mä", None, ""),
        ("muna", "muna", "mu-na", None, ""),
        ("juusto", "juusto", "juus-to (langes u; j wie dt. j)", None, ""),
        ("sokeri", "sokeri", "so-ke-ri", None, ""),
        ("suola", "suola", "suo-la (uo = Diphthong)", None, ""),
        ("voi", "voi", "woi (v = w-ähnlich)", None, "Auch 'kann' (voida)"),
        ("öljy", "öljy", "öl-jü (y = ü)", None, ""),
        ("peruna", "peruna", "pe-ru-na", None, ""),
        ("kana", "kana", "ka-na", None, ""),
        ("tomaatti", "tomaatti", "to-maat-ti (langes a + Doppel-t)", None, ""),
        ("omena", "omena", "o-me-na", None, ""),
        ("kakku", "kakku", "kak-ku (Doppel-k)", None, ""),
        ("kokata", "kokata", "ko-ka-ta", None, "Infinitivform; auch: keittää, laittaa ruokaa"),
        ("ravintola", "ravintola", "ra-win-to-la (v = w-ähnlich)", None, ""),
        ("aamiainen", "aamiainen", "aa-mi-ai-nen (langes a)", None, ""),
        ("illallinen", "illallinen", "il-lal-li-nen (Doppel-l)", None, ""),
    ],
    "natur_wetter": [
        ("metsä", "metsä", "met-sä (ä wie dt. 'Bär')", None, ""),
        ("taivas", "taivas", "tai-was (v = w-ähnlich)", None, ""),
        ("tähti", "tähti", "täh-ti (ä wie dt. 'Bär')", None, ""),
        ("maa", "maa", "maa (langes a)", None, "Auch 'Land'"),
        ("tuuli", "tuuli", "tuu-li (langes u)", None, ""),
        ("pilvi", "pilvi", "pil-wi (v = w-ähnlich)", None, ""),
        ("ukkonen", "ukkonen", "uk-ko-nen (Doppel-k)", None, ""),
        ("saari", "saari", "saa-ri (langes a)", None, ""),
        ("järvi", "järvi", "jär-wi (ä wie 'Bär'; v = w)", None, ""),
        ("ruoho", "ruoho", "ruo-ho (uo = Diphthong)", None, ""),
        ("kivi", "kivi", "ki-wi", None, ""),
        ("hiekka", "hiekka", "hiek-ka (ie = Diphthong; Doppel-k)", None, ""),
        ("jää", "jää", "jää (langes ä)", None, ""),
        ("sumu", "sumu", "su-mu", None, ""),
        ("ranta", "ranta", "ran-ta", None, ""),
        ("aavikko", "aavikko", "aa-wik-ko (langes a; v = w; Doppel-k)", None, ""),
        ("kevät", "kevät", "ke-wät (v = w; ä wie 'Bär')", None, ""),
        ("kesä", "kesä", "ke-sä (ä wie 'Bär')", None, ""),
        ("syksy", "syksy", "sük-sü (y = ü)", None, ""),
        ("talvi", "talvi", "tal-wi (v = w-ähnlich)", None, ""),
        ("ilma", "ilma", "il-ma", None, "Auch 'Wetter'"),
        ("tuli", "tuli", "tu-li", None, "Auch Vergangenheit von 'tulla' (kommen)"),
        ("myrsky", "myrsky", "mürs-kü (y = ü)", None, ""),
        ("sateenkaari", "sateenkaari", "sa-teen-kaa-ri (langes e + langes a)", None, "sade = Regen + kaari = Bogen"),
        ("pelto", "pelto", "pel-to", None, ""),
    ],
    "beruf_bildung": [
        ("opettaja", "opettaja", "o-pet-ta-ja (Doppel-t; j wie dt. j)", None, "opettaa = lehren + -ja = Suffix"),
        ("opiskelija", "opiskelija", "o-pis-ke-li-ja", None, "opiskella = studieren + -ja"),
        ("toimisto", "toimisto", "toi-mis-to", None, ""),
        ("tietokone", "tietokone", "tie-to-ko-ne", None, "tieto = Wissen + kone = Maschine"),
        ("yliopisto", "yliopisto", "ü-li-o-pis-to (y = ü)", None, "yli = über + opisto = Institut"),
        ("koe", "koe", "ko-e", None, "Auch 'Versuch'"),
        ("ammatti", "ammatti", "am-mat-ti (Doppel-m + Doppel-t)", None, ""),
        ("pomo", "pomo", "po-mo", None, "Umgangssprachlich"),
        ("palkka", "palkka", "palk-ka (Doppel-k)", None, ""),
        ("insinööri", "insinööri", "in-si-nöö-ri (langes ö)", None, ""),
        ("asianajaja", "asianajaja", "a-si-a-na-ja-ja", None, "asia = Angelegenheit + ajaja = Treiber"),
        ("poliisi", "poliisi", "po-lii-si (langes i)", None, ""),
        ("tiede", "tiede", "tie-de (ie = Diphthong)", None, ""),
        ("matematiikka", "matematiikka", "ma-te-ma-tiik-ka (langes i + Doppel-k)", None, ""),
        ("historia", "historia", "his-to-ri-a", None, ""),
        ("kieli", "kieli", "kie-li (ie = Diphthong)", None, "Auch 'Zunge'"),
        ("kirjasto", "kirjasto", "kir-jas-to", None, "kirja = Buch + -sto = Sammlung"),
        ("luokka", "luokka", "luok-ka (uo = Diphthong; Doppel-k)", None, ""),
        ("opiskella", "opiskella", "o-pis-kel-la (Doppel-l)", None, "Infinitivform"),
        ("opettaa", "opettaa", "o-pet-taa (Doppel-t + langes a)", None, "Infinitivform"),
        ("tehtävä", "tehtävä", "teh-tä-wä (v = w; ä wie 'Bär')", None, ""),
        ("kokemus", "kokemus", "ko-ke-mus", None, "kokea = erfahren + -mus"),
        ("yritys", "yritys", "ü-ri-tüs (y = ü)", None, "yrittää = versuchen"),
        ("projekti", "projekti", "pro-jek-ti", None, "Lehnwort"),
        ("kokous", "kokous", "ko-ko-us", None, "kokoontua = sich versammeln"),
    ],
}

# ===========================
# ESTONIAN (et)
# ===========================
TRANSLATIONS["estonian"] = {
    "koerper_gesundheit": [
        ("käsi", "käsi", "käsi (ä wie dt. 'Bär'; Betonung auf 1. Silbe)", None, ""),
        ("jalg", "jalg", "jalg (g am Ende stimmlos)", None, "Auch 'Bein'"),
        ("hammas", "hammas", "ham-mas (Doppel-m = lang)", None, "Stamm: hamba-"),
        ("kõrv", "kõrv", "körw (õ = hinteres ö, Lippen nicht gerundet)", None, "õ = spezieller estnischer Vokal"),
        ("nina", "nina", "ni-na", None, ""),
        ("suu", "suu", "suu (langes u)", None, ""),
        ("sõrm", "sõrm", "sörm (õ = hinteres ö)", None, ""),
        ("selg", "selg", "selg (g am Ende stimmlos)", None, ""),
        ("käsivars", "käsivars", "kä-si-wars (ä wie 'Bär')", None, "käsi = Hand + vars = Stiel"),
        ("jalg", "jalg", "jalg", None, "Im Estnischen gleich wie 'Fuß'"),
        ("nahk", "nahk", "nahk (h deutlich hörbar)", None, ""),
        ("veri", "veri", "we-ri (v = w)", None, ""),
        ("luu", "luu", "luu (langes u)", None, ""),
        ("haigla", "haigla", "haig-la", None, "haige = krank"),
        ("ravim", "ravim", "ra-wim (v = w)", None, ""),
        ("haige", "haige", "hai-ge", None, ""),
        ("terve", "terve", "ter-we (v = w)", None, "Auch Begrüßung"),
        ("kõht", "kõht", "köht (õ = hinteres ö)", None, ""),
        ("arst", "arst", "arst", None, ""),
        ("valu", "valu", "wa-lu (v = w)", None, ""),
        ("palavik", "palavik", "pa-la-wik (v = w)", None, "palav = heiß/brennend"),
        ("köha", "köha", "kö-ha", None, ""),
        ("apteek", "apteek", "ap-teek (langes e)", None, ""),
        ("keel", "keel", "keel (langes e)", None, "Auch 'Sprache'"),
        ("õlg", "õlg", "ölg (õ = hinteres ö)", None, ""),
    ],
    "essen_trinken": [
        ("liha", "liha", "li-ha", None, ""),
        ("kala", "kala", "ka-la", None, ""),
        ("riis", "riis", "riis (langes i)", None, ""),
        ("kohv", "kohv", "kohw (v = w; h deutlich)", None, ""),
        ("tee", "tee", "tee (langes e)", None, ""),
        ("õlu", "õlu", "ölu (õ = hinteres ö)", None, ""),
        ("vein", "vein", "wein (v = w; wie dt. 'Wein')", None, ""),
        ("supp", "supp", "supp (Doppel-p = lang)", None, ""),
        ("köögivili", "köögivili", "köö-gi-wi-li (langes ö; v = w)", None, "köök = Küche + vili = Frucht"),
        ("puuvili", "puuvili", "puu-wi-li (langes u; v = w)", None, "puu = Baum + vili = Frucht"),
        ("muna", "muna", "mu-na", None, ""),
        ("juust", "juust", "juust (langes u)", None, ""),
        ("suhkur", "suhkur", "suh-kur (h deutlich)", None, ""),
        ("sool", "sool", "sool (langes o)", None, ""),
        ("või", "või", "wöi (v = w; õ = hinteres ö)", None, "Auch 'oder'"),
        ("õli", "õli", "öli (õ = hinteres ö)", None, ""),
        ("kartul", "kartul", "kar-tul", None, ""),
        ("kana", "kana", "ka-na", None, ""),
        ("tomat", "tomat", "to-mat", None, ""),
        ("õun", "õun", "öun (õ = hinteres ö)", None, ""),
        ("kook", "kook", "kook (langes o)", None, ""),
        ("kokata", "kokata", "ko-ka-ta", None, "Auch: süüa tegema (wörtl.: 'Essen machen')"),
        ("restoran", "restoran", "res-to-ran", None, ""),
        ("hommikusöök", "hommikusöök", "hom-mi-ku-söök (Doppel-m; langes ö)", None, "hommik = Morgen + söök = Essen"),
        ("õhtusöök", "õhtusöök", "öh-tu-söök (õ = hinteres ö; langes ö)", None, "õhtu = Abend + söök = Essen"),
    ],
    "natur_wetter": [
        ("mets", "mets", "mets", None, "Stamm: metsa-"),
        ("taevas", "taevas", "tae-was (v = w)", None, ""),
        ("täht", "täht", "täht (ä wie dt. 'Bär')", None, ""),
        ("maa", "maa", "maa (langes a)", None, "Auch 'Land'"),
        ("tuul", "tuul", "tuul (langes u)", None, ""),
        ("pilv", "pilv", "pilw (v = w)", None, ""),
        ("kõu", "kõu", "köu (õ = hinteres ö)", None, ""),
        ("saar", "saar", "saar (langes a)", None, ""),
        ("järv", "järv", "järw (ä wie 'Bär'; v = w)", None, ""),
        ("rohi", "rohi", "ro-hi", None, ""),
        ("kivi", "kivi", "ki-wi", None, ""),
        ("liiv", "liiv", "liiv (langes i; v = w)", None, ""),
        ("jää", "jää", "jää (langes ä)", None, ""),
        ("udu", "udu", "u-du", None, ""),
        ("rand", "rand", "rand", None, "Auch 'Ufer'"),
        ("kõrb", "kõrb", "körb (õ = hinteres ö)", None, ""),
        ("kevad", "kevad", "ke-wad (v = w)", None, ""),
        ("suvi", "suvi", "su-wi (v = w)", None, "Poetisch; Alltag: suvi oder suvine"),
        ("sügis", "sügis", "sü-gis (ü wie dt. 'über')", None, ""),
        ("talv", "talv", "talw (v = w)", None, ""),
        ("õhk", "õhk", "öhk (õ = hinteres ö; h deutlich)", None, ""),
        ("tuli", "tuli", "tu-li", None, "Auch Vergangenheit von 'tulema' (kommen)"),
        ("torm", "torm", "torm", None, ""),
        ("vikerkaar", "vikerkaar", "wi-ker-kaar (v = w; langes a)", None, ""),
        ("põld", "põld", "pöld (õ = hinteres ö)", None, ""),
    ],
    "beruf_bildung": [
        ("õpetaja", "õpetaja", "ö-pe-ta-ja (õ = hinteres ö)", None, "õpetama = lehren + -ja"),
        ("õpilane", "õpilane", "ö-pi-la-ne (õ = hinteres ö)", None, ""),
        ("kontor", "kontor", "kon-tor", None, ""),
        ("arvuti", "arvuti", "ar-wu-ti (v = w)", None, "arvutama = rechnen"),
        ("ülikool", "ülikool", "ü-li-kool (ü wie dt. 'über'; langes o)", None, "üli = über + kool = Schule"),
        ("eksam", "eksam", "ek-sam", None, ""),
        ("elukutse", "elukutse", "e-lu-kut-se", None, "elu = Leben + kutse = Berufung"),
        ("ülemus", "ülemus", "ü-le-mus (ü wie dt. 'über')", None, "üle = über + -mus"),
        ("palk", "palk", "palk", None, "Auch 'Balken'"),
        ("insener", "insener", "in-se-ner", None, ""),
        ("advokaat", "advokaat", "ad-wo-kaat (v = w; langes a)", None, ""),
        ("politseinik", "politseinik", "po-li-tsei-nik", None, "politsei = Polizei + -nik"),
        ("teadus", "teadus", "tea-dus", None, "teadma = wissen + -us"),
        ("matemaatika", "matemaatika", "ma-te-maa-ti-ka (langes a)", None, ""),
        ("ajalugu", "ajalugu", "a-ja-lu-gu", None, "aja = Zeit + lugu = Geschichte"),
        ("keel", "keel", "keel (langes e)", None, "Auch 'Zunge'"),
        ("raamatukogu", "raamatukogu", "raa-ma-tu-ko-gu (langes a)", None, "raamat = Buch + kogu = Sammlung"),
        ("klass", "klass", "klass (Doppel-s = lang)", None, ""),
        ("õppima", "õppima", "öp-pi-ma (õ = hinteres ö; Doppel-p)", None, ""),
        ("õpetama", "õpetama", "ö-pe-ta-ma (õ = hinteres ö)", None, ""),
        ("ülesanne", "ülesanne", "ü-les-an-ne (ü wie dt. 'über'; Doppel-n)", None, "üles = auf + anne = Gabe"),
        ("kogemus", "kogemus", "ko-ge-mus", None, "kogema = erfahren + -mus"),
        ("ettevõte", "ettevõte", "et-te-wö-te (Doppel-t; v = w; õ = hinteres ö)", None, "ette = vor + võte = Nehmen"),
        ("projekt", "projekt", "pro-jekt", None, "Lehnwort"),
        ("koosolek", "koosolek", "koo-so-lek (langes o)", None, "koos = zusammen + olek = Sein"),
    ],
}


def build_entry(word, romanization, pronunciation_hint, meaning_de, meaning_en,
                category, frequency_rank, concept_id, tone, notes):
    """Build a single word entry dictionary."""
    return {
        "word": word,
        "romanization": romanization,
        "pronunciation_hint": pronunciation_hint,
        "meaning_de": meaning_de,
        "meaning_en": meaning_en,
        "category": category,
        "frequency_rank": frequency_rank,
        "concept_id": concept_id,
        "tone": tone,
        "notes": notes,
    }


def process_language(lang_filename, lang_translations):
    """Read a language JSON file, append new words, write back."""
    filepath = os.path.join(DATA_DIR, f"{lang_filename}.json")

    if not os.path.exists(filepath):
        print(f"  ERROR: File not found: {filepath}")
        return

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Find current max frequency_rank
    max_rank = max(w["frequency_rank"] for w in data["words"])

    # Collect existing concept_ids for duplicate detection
    existing_ids = {w["concept_id"] for w in data["words"]}

    rank = max_rank
    added = 0
    skipped = 0

    for category_name, concepts in CATEGORIES.items():
        translations = lang_translations.get(category_name, [])
        if len(translations) != len(concepts):
            print(f"  WARNING: {category_name} has {len(concepts)} concepts "
                  f"but {len(translations)} translations for {lang_filename}")
            continue

        for i, (concept_id, meaning_de, meaning_en) in enumerate(concepts):
            if concept_id in existing_ids:
                skipped += 1
                continue

            word, romanization, pronunciation_hint, tone, notes = translations[i]

            rank += 1
            entry = build_entry(
                word=word,
                romanization=romanization,
                pronunciation_hint=pronunciation_hint,
                meaning_de=meaning_de,
                meaning_en=meaning_en,
                category=category_name,
                frequency_rank=rank,
                concept_id=concept_id,
                tone=tone,
                notes=notes,
            )
            data["words"].append(entry)
            existing_ids.add(concept_id)
            added += 1

    # Write back with same formatting (2-space indent, UTF-8)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"  Added {added} words, skipped {skipped} duplicates. "
          f"New max rank: {rank}. Total words: {len(data['words'])}")


def main():
    print("=== Generating new vocabulary entries ===\n")

    languages = [
        ("chinese", "Chinese (zh)"),
        ("japanese", "Japanese (ja)"),
        ("korean", "Korean (ko)"),
        ("vietnamese", "Vietnamese (vi)"),
        ("hungarian", "Hungarian (hu)"),
        ("finnish", "Finnish (fi)"),
        ("estonian", "Estonian (et)"),
    ]

    for lang_filename, lang_display in languages:
        print(f"Processing {lang_display}...")
        if lang_filename not in TRANSLATIONS:
            print(f"  ERROR: No translations defined for {lang_filename}")
            continue
        process_language(lang_filename, TRANSLATIONS[lang_filename])

    print("\nDone!")


if __name__ == "__main__":
    main()
