#!/usr/bin/env python3
"""
Generate new vocabulary entries for 10 Slavic languages.
Adds 4 new categories: koerper_gesundheit, essen_trinken, natur_wetter, beruf_bildung
Each category has ~25 words.
"""

import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
DATA_DIR = os.path.join(PROJECT_DIR, "data", "words")

# Map language IDs to filenames
LANG_FILES = {
    "ru": "russian",
    "uk": "ukrainian",
    "be": "belarusian",
    "sk": "slovak",
    "cs": "czech",
    "pl": "polish",
    "sl": "slovenian",
    "hr": "croatian",
    "bg": "bulgarian",
    "mk": "macedonian",
}

# ── Category metadata ──────────────────────────────────────────────
# Each entry: (concept_id, meaning_de, meaning_en)

KOERPER_GESUNDHEIT = [
    ("hand", "Hand", "hand"),
    ("fuss", "Fuß", "foot"),
    ("zahn", "Zahn", "tooth"),
    ("ohr", "Ohr", "ear"),
    ("nase", "Nase", "nose"),
    ("mund", "Mund", "mouth"),
    ("finger", "Finger", "finger"),
    ("ruecken", "Rücken", "back"),
    ("arm_body", "Arm", "arm"),
    ("bein", "Bein", "leg"),
    ("haut", "Haut", "skin"),
    ("blut", "Blut", "blood"),
    ("knochen", "Knochen", "bone"),
    ("krankenhaus", "Krankenhaus", "hospital"),
    ("medizin", "Medizin", "medicine"),
    ("krank", "krank", "sick"),
    ("gesund", "gesund", "healthy"),
    ("bauch", "Bauch", "stomach"),
    ("arzt", "Arzt", "doctor"),
    ("schmerz", "Schmerz", "pain"),
    ("fieber", "Fieber", "fever"),
    ("husten", "Husten", "cough"),
    ("apotheke", "Apotheke", "pharmacy"),
    ("zunge", "Zunge", "tongue"),
    ("schulter", "Schulter", "shoulder"),
]

ESSEN_TRINKEN = [
    ("fleisch", "Fleisch", "meat"),
    ("fisch", "Fisch", "fish"),
    ("reis", "Reis", "rice"),
    ("kaffee", "Kaffee", "coffee"),
    ("tee", "Tee", "tea"),
    ("bier", "Bier", "beer"),
    ("wein", "Wein", "wine"),
    ("suppe", "Suppe", "soup"),
    ("gemuese", "Gemüse", "vegetables"),
    ("obst", "Obst", "fruit"),
    ("ei", "Ei", "egg"),
    ("kaese", "Käse", "cheese"),
    ("zucker", "Zucker", "sugar"),
    ("salz", "Salz", "salt"),
    ("butter", "Butter", "butter"),
    ("oel", "Öl", "oil"),
    ("kartoffel", "Kartoffel", "potato"),
    ("huhn", "Huhn", "chicken"),
    ("tomate", "Tomate", "tomato"),
    ("apfel", "Apfel", "apple"),
    ("kuchen", "Kuchen", "cake"),
    ("kochen", "kochen", "to cook"),
    ("restaurant", "Restaurant", "restaurant"),
    ("fruehstueck", "Frühstück", "breakfast"),
    ("abendessen", "Abendessen", "dinner"),
]

NATUR_WETTER = [
    ("wald", "Wald", "forest"),
    ("himmel", "Himmel", "sky"),
    ("stern", "Stern", "star"),
    ("erde", "Erde", "earth"),
    ("wind", "Wind", "wind"),
    ("wolke", "Wolke", "cloud"),
    ("donner", "Donner", "thunder"),
    ("insel", "Insel", "island"),
    ("see_lake", "See", "lake"),
    ("gras", "Gras", "grass"),
    ("stein", "Stein", "stone"),
    ("sand", "Sand", "sand"),
    ("eis", "Eis", "ice"),
    ("nebel", "Nebel", "fog"),
    ("strand", "Strand", "beach"),
    ("wueste", "Wüste", "desert"),
    ("fruehling", "Frühling", "spring"),
    ("sommer", "Sommer", "summer"),
    ("herbst", "Herbst", "autumn"),
    ("winter", "Winter", "winter"),
    ("luft", "Luft", "air"),
    ("feuer", "Feuer", "fire"),
    ("sturm", "Sturm", "storm"),
    ("regenbogen", "Regenbogen", "rainbow"),
    ("feld", "Feld", "field"),
]

BERUF_BILDUNG = [
    ("lehrer", "Lehrer", "teacher"),
    ("schueler", "Schüler", "student"),
    ("buero", "Büro", "office"),
    ("computer", "Computer", "computer"),
    ("universitaet", "Universität", "university"),
    ("pruefung", "Prüfung", "exam"),
    ("beruf", "Beruf", "profession"),
    ("chef", "Chef", "boss"),
    ("gehalt", "Gehalt", "salary"),
    ("ingenieur", "Ingenieur", "engineer"),
    ("rechtsanwalt", "Rechtsanwalt", "lawyer"),
    ("polizist", "Polizist", "police officer"),
    ("wissenschaft", "Wissenschaft", "science"),
    ("mathematik", "Mathematik", "mathematics"),
    ("geschichte", "Geschichte", "history"),
    ("sprache_lang", "Sprache", "language"),
    ("bibliothek", "Bibliothek", "library"),
    ("klasse", "Klasse", "class"),
    ("studieren", "studieren", "to study"),
    ("unterrichten", "unterrichten", "to teach"),
    ("aufgabe", "Aufgabe", "task"),
    ("erfahrung", "Erfahrung", "experience"),
    ("unternehmen", "Unternehmen", "company"),
    ("projekt", "Projekt", "project"),
    ("meeting", "Besprechung", "meeting"),
]

ALL_CATEGORIES = [
    ("koerper_gesundheit", KOERPER_GESUNDHEIT),
    ("essen_trinken", ESSEN_TRINKEN),
    ("natur_wetter", NATUR_WETTER),
    ("beruf_bildung", BERUF_BILDUNG),
]

# ── Translations per language ──────────────────────────────────────
# Each language dict maps concept_id -> (word, romanization, pronunciation_hint, notes)
# For Latin-script languages, romanization = ""
# For Cyrillic-script languages (ru, uk, be, bg, mk), romanization is provided

TRANSLATIONS = {
    # ================================================================
    # RUSSIAN (ru) - Cyrillic
    # ================================================================
    "ru": {
        # koerper_gesundheit
        "hand": ("рука", "ruka", "ru-KA", "Also means arm"),
        "fuss": ("нога", "noga", "na-GA", "Also means leg"),
        "zahn": ("зуб", "zub", "zup", ""),
        "ohr": ("ухо", "ukho", "U-kha", ""),
        "nase": ("нос", "nos", "nos", ""),
        "mund": ("рот", "rot", "rot", ""),
        "finger": ("палец", "palets", "PA-ljets", ""),
        "ruecken": ("спина", "spina", "spi-NA", ""),
        "arm_body": ("рука", "ruka", "ru-KA", "Same word as hand in Russian"),
        "bein": ("нога", "noga", "na-GA", "Same word as foot in Russian"),
        "haut": ("кожа", "kozha", "KO-zha", ""),
        "blut": ("кровь", "krov'", "krof", ""),
        "knochen": ("кость", "kost'", "kost", ""),
        "krankenhaus": ("больница", "bol'nitsa", "bal-NI-tsa", ""),
        "medizin": ("лекарство", "lekarstvo", "lje-KAR-stwa", ""),
        "krank": ("больной", "bol'noy", "bal-NOI", ""),
        "gesund": ("здоровый", "zdorovyy", "zda-RO-wij", ""),
        "bauch": ("живот", "zhivot", "zhi-WOT", ""),
        "arzt": ("врач", "vrach", "wratsch", ""),
        "schmerz": ("боль", "bol'", "bol", ""),
        "fieber": ("температура", "temperatura", "tjem-pje-ra-TU-ra", "Lit. temperature"),
        "husten": ("кашель", "kashel'", "KA-schel", ""),
        "apotheke": ("аптека", "apteka", "ap-TJE-ka", ""),
        "zunge": ("язык", "yazyk", "ja-ZIK", "Also means language"),
        "schulter": ("плечо", "plecho", "plje-TSCHO", ""),
        # essen_trinken
        "fleisch": ("мясо", "myaso", "MJA-sa", ""),
        "fisch": ("рыба", "ryba", "RI-ba", ""),
        "reis": ("рис", "ris", "ris", ""),
        "kaffee": ("кофе", "kofe", "KO-fje", "Indeclinable noun"),
        "tee": ("чай", "chay", "tschai", ""),
        "bier": ("пиво", "pivo", "PI-wa", ""),
        "wein": ("вино", "vino", "wi-NO", ""),
        "suppe": ("суп", "sup", "sup", ""),
        "gemuese": ("овощи", "ovoshchi", "O-wa-schtschi", "Plural form"),
        "obst": ("фрукты", "frukty", "FRUK-ti", "Plural form"),
        "ei": ("яйцо", "yaytso", "jaj-ZO", ""),
        "kaese": ("сыр", "syr", "sir", ""),
        "zucker": ("сахар", "sakhar", "SA-char", ""),
        "salz": ("соль", "sol'", "sol", ""),
        "butter": ("масло", "maslo", "MAS-la", "Also means oil generically"),
        "oel": ("масло", "maslo", "MAS-la", "Use растительное масло for cooking oil"),
        "kartoffel": ("картофель", "kartofel'", "kar-TO-fjel", "Formal; colloquial: картошка"),
        "huhn": ("курица", "kuritsa", "KU-ri-tsa", ""),
        "tomate": ("помидор", "pomidor", "pa-mi-DOR", ""),
        "apfel": ("яблоко", "yabloko", "JA-bla-ka", ""),
        "kuchen": ("торт", "tort", "tort", ""),
        "kochen": ("готовить", "gotovit'", "ga-TO-wit", "Imperfective"),
        "restaurant": ("ресторан", "restoran", "rje-sta-RAN", ""),
        "fruehstueck": ("завтрак", "zavtrak", "SAF-trak", ""),
        "abendessen": ("ужин", "uzhin", "U-zhin", ""),
        # natur_wetter
        "wald": ("лес", "les", "ljes", ""),
        "himmel": ("небо", "nebo", "NJE-ba", ""),
        "stern": ("звезда", "zvezda", "swjes-DA", ""),
        "erde": ("земля", "zemlya", "zjem-LJA", ""),
        "wind": ("ветер", "veter", "WJE-tjer", ""),
        "wolke": ("облако", "oblako", "O-bla-ka", ""),
        "donner": ("гром", "grom", "grom", ""),
        "insel": ("остров", "ostrov", "O-straf", ""),
        "see_lake": ("озеро", "ozero", "O-zje-ra", ""),
        "gras": ("трава", "trava", "tra-WA", ""),
        "stein": ("камень", "kamen'", "KA-mjen", ""),
        "sand": ("песок", "pesok", "pje-SOK", ""),
        "eis": ("лёд", "lyod", "ljot", ""),
        "nebel": ("туман", "tuman", "tu-MAN", ""),
        "strand": ("пляж", "plyazh", "pljasch", ""),
        "wueste": ("пустыня", "pustynya", "pu-STI-nja", ""),
        "fruehling": ("весна", "vesna", "wjes-NA", ""),
        "sommer": ("лето", "leto", "LJE-ta", ""),
        "herbst": ("осень", "osen'", "O-sjen", ""),
        "winter": ("зима", "zima", "zi-MA", ""),
        "luft": ("воздух", "vozdukh", "WOS-duch", ""),
        "feuer": ("огонь", "ogon'", "a-GON", ""),
        "sturm": ("буря", "burya", "BU-rja", ""),
        "regenbogen": ("радуга", "raduga", "RA-du-ga", ""),
        "feld": ("поле", "pole", "PO-lje", ""),
        # beruf_bildung
        "lehrer": ("учитель", "uchitel'", "u-TSCHI-tjel", ""),
        "schueler": ("ученик", "uchenik", "u-tsche-NIK", ""),
        "buero": ("офис", "ofis", "O-fis", ""),
        "computer": ("компьютер", "komp'yuter", "kam-PJU-tjer", ""),
        "universitaet": ("университет", "universitet", "u-ni-wjer-si-TJET", ""),
        "pruefung": ("экзамен", "ekzamen", "ek-ZA-mjen", ""),
        "beruf": ("профессия", "professiya", "pra-FJES-si-ja", ""),
        "chef": ("начальник", "nachal'nik", "na-TSCHAL-nik", ""),
        "gehalt": ("зарплата", "zarplata", "zar-PLA-ta", ""),
        "ingenieur": ("инженер", "inzhener", "in-zhe-NJER", ""),
        "rechtsanwalt": ("адвокат", "advokat", "ad-wa-KAT", ""),
        "polizist": ("полицейский", "politseyskiy", "pa-li-ZJEI-skij", ""),
        "wissenschaft": ("наука", "nauka", "na-U-ka", ""),
        "mathematik": ("математика", "matematika", "ma-tje-MA-ti-ka", ""),
        "geschichte": ("история", "istoriya", "is-TO-ri-ja", ""),
        "sprache_lang": ("язык", "yazyk", "ja-ZIK", "Also means tongue"),
        "bibliothek": ("библиотека", "biblioteka", "bib-li-a-TJE-ka", ""),
        "klasse": ("класс", "klass", "klass", ""),
        "studieren": ("учиться", "uchit'sya", "u-TSCHIT-sja", "Reflexive verb"),
        "unterrichten": ("преподавать", "prepodavat'", "prje-pa-da-WAT", ""),
        "aufgabe": ("задача", "zadacha", "za-DA-tscha", ""),
        "erfahrung": ("опыт", "opyt", "O-pit", ""),
        "unternehmen": ("компания", "kompaniya", "kam-PA-ni-ja", ""),
        "projekt": ("проект", "proyekt", "pra-JEKT", ""),
        "meeting": ("совещание", "soveshchaniye", "sa-wje-SCHTSCHA-ni-je", ""),
    },

    # ================================================================
    # UKRAINIAN (uk) - Cyrillic
    # ================================================================
    "uk": {
        # koerper_gesundheit
        "hand": ("рука", "ruka", "ru-KA", "Also means arm"),
        "fuss": ("нога", "noha", "no-HA", "Also means leg; Ukrainian г = h"),
        "zahn": ("зуб", "zub", "zub", ""),
        "ohr": ("вухо", "vukho", "WU-cho", ""),
        "nase": ("ніс", "nis", "nis", ""),
        "mund": ("рот", "rot", "rot", ""),
        "finger": ("палець", "palets'", "PA-lets", ""),
        "ruecken": ("спина", "spyna", "spy-NA", ""),
        "arm_body": ("рука", "ruka", "ru-KA", "Same word as hand in Ukrainian"),
        "bein": ("нога", "noha", "no-HA", "Same word as foot in Ukrainian"),
        "haut": ("шкіра", "shkira", "SCHKI-ra", ""),
        "blut": ("кров", "krov", "krow", ""),
        "knochen": ("кістка", "kistka", "KIST-ka", ""),
        "krankenhaus": ("лікарня", "likarnya", "li-KAR-nja", ""),
        "medizin": ("ліки", "liky", "LI-ky", "Plural; means medicines"),
        "krank": ("хворий", "khvoryy", "CHWO-ryj", ""),
        "gesund": ("здоровий", "zdorovyy", "zdo-RO-wyj", ""),
        "bauch": ("живіт", "zhyvit", "zhy-WIT", ""),
        "arzt": ("лікар", "likar", "LI-kar", ""),
        "schmerz": ("біль", "bil'", "bil", ""),
        "fieber": ("гарячка", "haryachka", "ha-RJATSCH-ka", ""),
        "husten": ("кашель", "kashel'", "KA-schel", ""),
        "apotheke": ("аптека", "apteka", "ap-TE-ka", ""),
        "zunge": ("язик", "yazyk", "ja-ZYK", "Also means language"),
        "schulter": ("плече", "pleche", "ple-TSCHE", ""),
        # essen_trinken
        "fleisch": ("м'ясо", "m'yaso", "MJA-so", ""),
        "fisch": ("риба", "ryba", "RY-ba", ""),
        "reis": ("рис", "rys", "rys", ""),
        "kaffee": ("кава", "kava", "KA-wa", "Different from Russian кофе"),
        "tee": ("чай", "chay", "tschai", ""),
        "bier": ("пиво", "pyvo", "PY-wo", ""),
        "wein": ("вино", "vyno", "wy-NO", ""),
        "suppe": ("суп", "sup", "sup", ""),
        "gemuese": ("овочі", "ovochi", "O-wo-tschi", ""),
        "obst": ("фрукти", "frukty", "FRUK-ty", ""),
        "ei": ("яйце", "yaytse", "jaj-ZE", ""),
        "kaese": ("сир", "syr", "syr", ""),
        "zucker": ("цукор", "tsukor", "ZU-kor", ""),
        "salz": ("сіль", "sil'", "sil", ""),
        "butter": ("масло", "maslo", "MAS-lo", ""),
        "oel": ("олія", "oliya", "o-LI-ja", "Specifically cooking/vegetable oil"),
        "kartoffel": ("картопля", "kartoplya", "kar-TOP-lja", ""),
        "huhn": ("курка", "kurka", "KUR-ka", ""),
        "tomate": ("помідор", "pomidor", "po-mi-DOR", ""),
        "apfel": ("яблуко", "yabluko", "JA-blu-ko", ""),
        "kuchen": ("торт", "tort", "tort", ""),
        "kochen": ("готувати", "hotuvaty", "ho-tu-WA-ty", ""),
        "restaurant": ("ресторан", "restoran", "res-to-RAN", ""),
        "fruehstueck": ("сніданок", "snidanok", "sni-DA-nok", ""),
        "abendessen": ("вечеря", "vecherya", "we-TSCHE-rja", ""),
        # natur_wetter
        "wald": ("ліс", "lis", "lis", ""),
        "himmel": ("небо", "nebo", "NE-bo", ""),
        "stern": ("зірка", "zirka", "SIR-ka", ""),
        "erde": ("земля", "zemlya", "zem-LJA", ""),
        "wind": ("вітер", "viter", "WI-ter", ""),
        "wolke": ("хмара", "khmara", "CHMA-ra", ""),
        "donner": ("грім", "hrim", "hrim", ""),
        "insel": ("острів", "ostriv", "O-striw", ""),
        "see_lake": ("озеро", "ozero", "O-ze-ro", ""),
        "gras": ("трава", "trava", "tra-WA", ""),
        "stein": ("камінь", "kamin'", "KA-min", ""),
        "sand": ("пісок", "pisok", "pi-SOK", ""),
        "eis": ("лід", "lid", "lid", ""),
        "nebel": ("туман", "tuman", "tu-MAN", ""),
        "strand": ("пляж", "plyazh", "pljasch", ""),
        "wueste": ("пустеля", "pustelya", "pu-STE-lja", ""),
        "fruehling": ("весна", "vesna", "wes-NA", ""),
        "sommer": ("літо", "lito", "LI-to", ""),
        "herbst": ("осінь", "osin'", "O-sin", ""),
        "winter": ("зима", "zyma", "zy-MA", ""),
        "luft": ("повітря", "povitrya", "po-WIT-rja", ""),
        "feuer": ("вогонь", "vohon'", "WO-hon", ""),
        "sturm": ("буря", "burya", "BU-rja", ""),
        "regenbogen": ("веселка", "veselka", "we-SEL-ka", ""),
        "feld": ("поле", "pole", "PO-le", ""),
        # beruf_bildung
        "lehrer": ("вчитель", "vchytel'", "WTSCHY-tel", ""),
        "schueler": ("учень", "uchen'", "U-tschenj", ""),
        "buero": ("офіс", "ofis", "O-fis", ""),
        "computer": ("комп'ютер", "komp'yuter", "kom-PJU-ter", ""),
        "universitaet": ("університет", "universytet", "u-ni-wer-sy-TET", ""),
        "pruefung": ("іспит", "ispyt", "IS-pyt", ""),
        "beruf": ("професія", "profesiya", "pro-FE-si-ja", ""),
        "chef": ("начальник", "nachal'nyk", "na-TSCHAL-nyk", ""),
        "gehalt": ("зарплата", "zarplata", "zar-PLA-ta", ""),
        "ingenieur": ("інженер", "inzhener", "in-zhe-NER", ""),
        "rechtsanwalt": ("адвокат", "advokat", "ad-wo-KAT", ""),
        "polizist": ("поліцейський", "politseys'kyy", "po-li-ZEJS-kyj", ""),
        "wissenschaft": ("наука", "nauka", "na-U-ka", ""),
        "mathematik": ("математика", "matematyka", "ma-te-MA-ty-ka", ""),
        "geschichte": ("історія", "istoriya", "is-TO-ri-ja", ""),
        "sprache_lang": ("мова", "mova", "MO-wa", "Different from Russian язык"),
        "bibliothek": ("бібліотека", "biblioteka", "bib-li-o-TE-ka", ""),
        "klasse": ("клас", "klas", "klas", ""),
        "studieren": ("вчитися", "vchytysya", "WTSCHY-ty-sja", "Reflexive verb"),
        "unterrichten": ("викладати", "vykladaty", "wy-kla-DA-ty", ""),
        "aufgabe": ("завдання", "zavdannya", "zaw-DAN-nja", ""),
        "erfahrung": ("досвід", "dosvid", "DOS-wid", ""),
        "unternehmen": ("компанія", "kompaniya", "kom-PA-ni-ja", ""),
        "projekt": ("проєкт", "proyekt", "pro-JEKT", "Uses є in Ukrainian"),
        "meeting": ("нарада", "narada", "na-RA-da", ""),
    },

    # ================================================================
    # BELARUSIAN (be) - Cyrillic
    # ================================================================
    "be": {
        # koerper_gesundheit
        "hand": ("рука", "ruka", "ru-KA", "Also means arm"),
        "fuss": ("нага", "naha", "na-HA", "Also means leg"),
        "zahn": ("зуб", "zub", "zub", ""),
        "ohr": ("вуха", "vukha", "WU-cha", ""),
        "nase": ("нос", "nos", "nos", ""),
        "mund": ("рот", "rot", "rot", ""),
        "finger": ("палец", "palets", "PA-lets", ""),
        "ruecken": ("спіна", "spina", "spi-NA", ""),
        "arm_body": ("рука", "ruka", "ru-KA", "Same word as hand in Belarusian"),
        "bein": ("нага", "naha", "na-HA", "Same word as foot in Belarusian"),
        "haut": ("скура", "skura", "SKU-ra", ""),
        "blut": ("кроў", "kroŭ", "krow", ""),
        "knochen": ("костка", "kostka", "KOST-ka", ""),
        "krankenhaus": ("бальніца", "bal'nitsa", "bal-NI-tsa", ""),
        "medizin": ("лякарства", "lyakarstva", "lja-KAR-stwa", ""),
        "krank": ("хворы", "khvory", "CHWO-ry", ""),
        "gesund": ("здаровы", "zdarovy", "zda-RO-wy", ""),
        "bauch": ("жывот", "zhyvot", "zhy-WOT", ""),
        "arzt": ("лекар", "lekar", "LJE-kar", ""),
        "schmerz": ("боль", "bol'", "bol", ""),
        "fieber": ("гарачка", "harachka", "ha-RATSCH-ka", ""),
        "husten": ("кашаль", "kashal'", "KA-schal", ""),
        "apotheke": ("аптэка", "apteka", "ap-TE-ka", ""),
        "zunge": ("язык", "yazyk", "ja-ZYK", "Also means language"),
        "schulter": ("плячо", "plyacho", "plja-TSCHO", ""),
        # essen_trinken
        "fleisch": ("мяса", "myasa", "MJA-sa", ""),
        "fisch": ("рыба", "ryba", "RY-ba", ""),
        "reis": ("рыс", "rys", "rys", ""),
        "kaffee": ("кава", "kava", "KA-wa", ""),
        "tee": ("чай", "chay", "tschai", ""),
        "bier": ("піва", "piva", "PI-wa", ""),
        "wein": ("віно", "vino", "wi-NO", ""),
        "suppe": ("суп", "sup", "sup", ""),
        "gemuese": ("гародніна", "harodina", "ha-ra-DNI-na", ""),
        "obst": ("садавіна", "sadavina", "sa-da-WI-na", ""),
        "ei": ("яйка", "yayka", "JAI-ka", ""),
        "kaese": ("сыр", "syr", "syr", ""),
        "zucker": ("цукар", "tsukar", "ZU-kar", ""),
        "salz": ("соль", "sol'", "sol", ""),
        "butter": ("масла", "masla", "MAS-la", ""),
        "oel": ("алей", "aley", "a-LEJ", "Cooking/vegetable oil"),
        "kartoffel": ("бульба", "bul'ba", "BUL-ba", "Iconic Belarusian word"),
        "huhn": ("курыца", "kurytsa", "ku-RY-tsa", ""),
        "tomate": ("памідор", "pamidor", "pa-mi-DOR", ""),
        "apfel": ("яблык", "yablyk", "JA-blyk", ""),
        "kuchen": ("торт", "tort", "tort", ""),
        "kochen": ("гатаваць", "hatavats'", "ha-ta-WATS", ""),
        "restaurant": ("рэстаран", "restaran", "re-sta-RAN", ""),
        "fruehstueck": ("сняданак", "snyadanak", "snja-DA-nak", ""),
        "abendessen": ("вячэра", "vyachera", "wja-TSCHE-ra", ""),
        # natur_wetter
        "wald": ("лес", "les", "ljes", ""),
        "himmel": ("неба", "neba", "NJE-ba", ""),
        "stern": ("зорка", "zorka", "SOR-ka", ""),
        "erde": ("зямля", "zyamlya", "zjam-LJA", ""),
        "wind": ("вецер", "vetser", "WJE-tser", ""),
        "wolke": ("воблака", "voblaka", "WO-bla-ka", ""),
        "donner": ("гром", "hrom", "hrom", ""),
        "insel": ("востраў", "vostraŭ", "WO-straw", ""),
        "see_lake": ("возера", "vozera", "WO-zje-ra", ""),
        "gras": ("трава", "trava", "tra-WA", ""),
        "stein": ("камень", "kamen'", "KA-mjen", ""),
        "sand": ("пясок", "pyasok", "pja-SOK", ""),
        "eis": ("лёд", "lyod", "ljot", ""),
        "nebel": ("туман", "tuman", "tu-MAN", ""),
        "strand": ("пляж", "plyazh", "pljasch", ""),
        "wueste": ("пустыня", "pustynya", "pu-STY-nja", ""),
        "fruehling": ("вясна", "vyasna", "wjas-NA", ""),
        "sommer": ("лета", "leta", "LJE-ta", ""),
        "herbst": ("восень", "vosen'", "WO-sjen", ""),
        "winter": ("зіма", "zima", "zi-MA", ""),
        "luft": ("паветра", "pavetra", "pa-WJE-tra", ""),
        "feuer": ("агонь", "ahon'", "a-HON", ""),
        "sturm": ("бура", "bura", "BU-ra", ""),
        "regenbogen": ("вясёлка", "vyasyolka", "wja-SJOL-ka", ""),
        "feld": ("поле", "pole", "PO-lje", ""),
        # beruf_bildung
        "lehrer": ("настаўнік", "nastaŭnik", "na-STAW-nik", ""),
        "schueler": ("вучань", "vuchan'", "WU-tschan", ""),
        "buero": ("офіс", "ofis", "O-fis", ""),
        "computer": ("камп'ютар", "kamp'yutar", "kam-PJU-tar", ""),
        "universitaet": ("універсітэт", "universiteht", "u-ni-wer-si-TET", ""),
        "pruefung": ("іспыт", "ispyt", "IS-pyt", ""),
        "beruf": ("прафесія", "prafesiya", "pra-FE-si-ja", ""),
        "chef": ("начальнік", "nachal'nik", "na-TSCHAL-nik", ""),
        "gehalt": ("зарплата", "zarplata", "zar-PLA-ta", ""),
        "ingenieur": ("інжынер", "inzhyner", "in-zhy-NER", ""),
        "rechtsanwalt": ("адвакат", "advakat", "ad-wa-KAT", ""),
        "polizist": ("паліцэйскі", "palitseyski", "pa-li-ZEJ-ski", ""),
        "wissenschaft": ("навука", "navuka", "na-WU-ka", ""),
        "mathematik": ("матэматыка", "matematyka", "ma-te-MA-ty-ka", ""),
        "geschichte": ("гісторыя", "historyya", "his-TO-ry-ja", ""),
        "sprache_lang": ("мова", "mova", "MO-wa", ""),
        "bibliothek": ("бібліятэка", "bibliyateka", "bib-li-ja-TE-ka", ""),
        "klasse": ("клас", "klas", "klas", ""),
        "studieren": ("вучыцца", "vuchytstsa", "wu-TSCHYZ-tsa", ""),
        "unterrichten": ("выкладаць", "vykladats'", "wy-kla-DATS", ""),
        "aufgabe": ("задача", "zadacha", "za-DA-tscha", ""),
        "erfahrung": ("досвед", "dosved", "DOS-wed", ""),
        "unternehmen": ("кампанія", "kampaniya", "kam-PA-ni-ja", ""),
        "projekt": ("праект", "prayekt", "pra-JEKT", ""),
        "meeting": ("нарада", "narada", "na-RA-da", ""),
    },

    # ================================================================
    # SLOVAK (sk) - Latin
    # ================================================================
    "sk": {
        # koerper_gesundheit
        "hand": ("ruka", "", "RU-ka", "Also means arm"),
        "fuss": ("noha", "", "NO-ha", "Also means leg"),
        "zahn": ("zub", "", "sub", ""),
        "ohr": ("ucho", "", "U-cho", ""),
        "nase": ("nos", "", "nos", ""),
        "mund": ("ústa", "", "UU-sta", "Plural tantum"),
        "finger": ("prst", "", "prst", ""),
        "ruecken": ("chrbát", "", "CHRR-baat", ""),
        "arm_body": ("ruka", "", "RU-ka", "Same word as hand in Slovak"),
        "bein": ("noha", "", "NO-ha", "Same word as foot in Slovak"),
        "haut": ("koža", "", "KO-zha", "ž = zh"),
        "blut": ("krv", "", "krw", ""),
        "knochen": ("kosť", "", "kosstj", ""),
        "krankenhaus": ("nemocnica", "", "NJE-mots-ni-tsa", ""),
        "medizin": ("liek", "", "ljek", "Means medicine/drug"),
        "krank": ("chorý", "", "CHO-rii", ""),
        "gesund": ("zdravý", "", "SDRA-wii", ""),
        "bauch": ("brucho", "", "BRU-cho", ""),
        "arzt": ("lekár", "", "LJE-kaar", ""),
        "schmerz": ("bolesť", "", "BO-lestj", ""),
        "fieber": ("horúčka", "", "ho-RUUTSCH-ka", ""),
        "husten": ("kašeľ", "", "KA-schelj", ""),
        "apotheke": ("lekáreň", "", "LJE-kaa-renj", ""),
        "zunge": ("jazyk", "", "JA-sik", "Also means language"),
        "schulter": ("plece", "", "PLJE-tse", ""),
        # essen_trinken
        "fleisch": ("mäso", "", "MÄ-so", "ä = open e"),
        "fisch": ("ryba", "", "RI-ba", ""),
        "reis": ("ryža", "", "RI-zha", ""),
        "kaffee": ("káva", "", "KAA-wa", ""),
        "tee": ("čaj", "", "tschai", ""),
        "bier": ("pivo", "", "PI-wo", ""),
        "wein": ("víno", "", "WII-no", ""),
        "suppe": ("polievka", "", "po-LJEV-ka", ""),
        "gemuese": ("zelenina", "", "SE-lje-ni-na", ""),
        "obst": ("ovocie", "", "O-wo-tsje", ""),
        "ei": ("vajce", "", "WAI-tse", ""),
        "kaese": ("syr", "", "sir", ""),
        "zucker": ("cukor", "", "TSU-kor", ""),
        "salz": ("soľ", "", "solj", ""),
        "butter": ("maslo", "", "MAS-lo", ""),
        "oel": ("olej", "", "O-lej", ""),
        "kartoffel": ("zemiak", "", "SE-mjak", ""),
        "huhn": ("kura", "", "KU-ra", ""),
        "tomate": ("paradajka", "", "pa-ra-DAI-ka", ""),
        "apfel": ("jablko", "", "JABL-ko", ""),
        "kuchen": ("koláč", "", "KO-laatsch", ""),
        "kochen": ("variť", "", "WA-ritj", ""),
        "restaurant": ("reštaurácia", "", "resch-tau-RAA-tsi-ja", ""),
        "fruehstueck": ("raňajky", "", "RA-njaj-ki", "Plural"),
        "abendessen": ("večera", "", "WE-tsche-ra", ""),
        # natur_wetter
        "wald": ("les", "", "ljes", ""),
        "himmel": ("nebo", "", "NJE-bo", ""),
        "stern": ("hviezda", "", "HWJES-da", ""),
        "erde": ("zem", "", "sem", ""),
        "wind": ("vietor", "", "WJE-tor", ""),
        "wolke": ("oblak", "", "O-blak", ""),
        "donner": ("hrom", "", "hrom", ""),
        "insel": ("ostrov", "", "O-strow", ""),
        "see_lake": ("jazero", "", "JA-se-ro", ""),
        "gras": ("tráva", "", "TRAA-wa", ""),
        "stein": ("kameň", "", "KA-menj", ""),
        "sand": ("piesok", "", "PJE-sok", ""),
        "eis": ("ľad", "", "ljad", ""),
        "nebel": ("hmla", "", "HM-la", ""),
        "strand": ("pláž", "", "plaazh", ""),
        "wueste": ("púšť", "", "puuschtj", ""),
        "fruehling": ("jar", "", "jar", ""),
        "sommer": ("leto", "", "LJE-to", ""),
        "herbst": ("jeseň", "", "JE-senj", ""),
        "winter": ("zima", "", "SI-ma", ""),
        "luft": ("vzduch", "", "WSDUCH", ""),
        "feuer": ("oheň", "", "O-henj", ""),
        "sturm": ("búrka", "", "BUUR-ka", ""),
        "regenbogen": ("dúha", "", "DUU-ha", ""),
        "feld": ("pole", "", "PO-lje", ""),
        # beruf_bildung
        "lehrer": ("učiteľ", "", "U-tschi-telj", ""),
        "schueler": ("žiak", "", "zhiak", ""),
        "buero": ("kancelária", "", "kan-tse-LAA-ri-ja", ""),
        "computer": ("počítač", "", "PO-tschii-tatsch", ""),
        "universitaet": ("univerzita", "", "u-ni-WER-si-ta", ""),
        "pruefung": ("skúška", "", "SKUUSCH-ka", ""),
        "beruf": ("povolanie", "", "po-wo-LA-nje", ""),
        "chef": ("šéf", "", "schef", ""),
        "gehalt": ("plat", "", "plat", ""),
        "ingenieur": ("inžinier", "", "in-zhi-NJER", ""),
        "rechtsanwalt": ("advokát", "", "ad-wo-KAAT", ""),
        "polizist": ("policajt", "", "po-li-TSAJT", ""),
        "wissenschaft": ("veda", "", "WJE-da", ""),
        "mathematik": ("matematika", "", "ma-tje-MA-ti-ka", ""),
        "geschichte": ("dejiny", "", "DJE-ji-ni", "Plural; história also used"),
        "sprache_lang": ("jazyk", "", "JA-sik", "Also means tongue"),
        "bibliothek": ("knižnica", "", "KNIZH-ni-tsa", ""),
        "klasse": ("trieda", "", "TRJE-da", ""),
        "studieren": ("študovať", "", "SCHTU-do-watj", ""),
        "unterrichten": ("vyučovať", "", "WI-u-tscho-watj", ""),
        "aufgabe": ("úloha", "", "UU-lo-ha", ""),
        "erfahrung": ("skúsenosť", "", "SKUU-se-nostj", ""),
        "unternehmen": ("firma", "", "FIR-ma", "Or podnik"),
        "projekt": ("projekt", "", "PRO-jekt", ""),
        "meeting": ("porada", "", "PO-ra-da", ""),
    },

    # ================================================================
    # CZECH (cs) - Latin
    # ================================================================
    "cs": {
        # koerper_gesundheit
        "hand": ("ruka", "", "RU-ka", "Also means arm"),
        "fuss": ("noha", "", "NO-ha", "Also means leg"),
        "zahn": ("zub", "", "sub", ""),
        "ohr": ("ucho", "", "U-cho", ""),
        "nase": ("nos", "", "nos", ""),
        "mund": ("ústa", "", "UU-sta", "Plural tantum"),
        "finger": ("prst", "", "prst", ""),
        "ruecken": ("záda", "", "SAA-da", "Plural tantum"),
        "arm_body": ("paže", "", "PA-zhe", "Distinct from ruka for arm specifically"),
        "bein": ("noha", "", "NO-ha", "Same word as foot in Czech"),
        "haut": ("kůže", "", "KUU-zhe", "ů = long u"),
        "blut": ("krev", "", "kref", ""),
        "knochen": ("kost", "", "kost", ""),
        "krankenhaus": ("nemocnice", "", "NJE-mots-ni-tse", ""),
        "medizin": ("lék", "", "ljek", "Means medicine/drug"),
        "krank": ("nemocný", "", "NJE-mots-nii", ""),
        "gesund": ("zdravý", "", "SDRA-wii", ""),
        "bauch": ("břicho", "", "BRZHI-cho", "ř = special Czech sound"),
        "arzt": ("lékař", "", "LJE-karzh", "ř = special Czech sound"),
        "schmerz": ("bolest", "", "BO-lest", ""),
        "fieber": ("horečka", "", "HO-retsch-ka", ""),
        "husten": ("kašel", "", "KA-schel", ""),
        "apotheke": ("lékárna", "", "LJE-kaar-na", ""),
        "zunge": ("jazyk", "", "JA-sik", "Also means language"),
        "schulter": ("rameno", "", "RA-me-no", ""),
        # essen_trinken
        "fleisch": ("maso", "", "MA-so", ""),
        "fisch": ("ryba", "", "RI-ba", ""),
        "reis": ("rýže", "", "RII-zhe", ""),
        "kaffee": ("káva", "", "KAA-wa", ""),
        "tee": ("čaj", "", "tschai", ""),
        "bier": ("pivo", "", "PI-wo", ""),
        "wein": ("víno", "", "WII-no", ""),
        "suppe": ("polévka", "", "PO-ljef-ka", ""),
        "gemuese": ("zelenina", "", "SE-lje-ni-na", ""),
        "obst": ("ovoce", "", "O-wo-tse", ""),
        "ei": ("vejce", "", "WEI-tse", ""),
        "kaese": ("sýr", "", "siir", ""),
        "zucker": ("cukr", "", "TSU-kr", ""),
        "salz": ("sůl", "", "suul", "ů = long u"),
        "butter": ("máslo", "", "MAAS-lo", ""),
        "oel": ("olej", "", "O-lej", ""),
        "kartoffel": ("brambor", "", "BRAM-bor", ""),
        "huhn": ("kuře", "", "KU-rzhe", ""),
        "tomate": ("rajče", "", "RAI-tsche", ""),
        "apfel": ("jablko", "", "JABL-ko", ""),
        "kuchen": ("dort", "", "dort", ""),
        "kochen": ("vařit", "", "WA-rzhit", ""),
        "restaurant": ("restaurace", "", "re-stau-RA-tse", ""),
        "fruehstueck": ("snídaně", "", "SNII-da-nje", ""),
        "abendessen": ("večeře", "", "WE-tsche-rzhe", ""),
        # natur_wetter
        "wald": ("les", "", "ljes", ""),
        "himmel": ("nebe", "", "NJE-be", ""),
        "stern": ("hvězda", "", "HWJES-da", ""),
        "erde": ("země", "", "SE-mnje", ""),
        "wind": ("vítr", "", "WII-tr", ""),
        "wolke": ("oblak", "", "O-blak", ""),
        "donner": ("hrom", "", "hrom", ""),
        "insel": ("ostrov", "", "O-strow", ""),
        "see_lake": ("jezero", "", "JE-se-ro", ""),
        "gras": ("tráva", "", "TRAA-wa", ""),
        "stein": ("kámen", "", "KAA-men", ""),
        "sand": ("písek", "", "PII-sek", ""),
        "eis": ("led", "", "led", ""),
        "nebel": ("mlha", "", "ML-ha", ""),
        "strand": ("pláž", "", "plaazh", ""),
        "wueste": ("poušť", "", "POUSCH-tj", ""),
        "fruehling": ("jaro", "", "JA-ro", ""),
        "sommer": ("léto", "", "LJE-to", ""),
        "herbst": ("podzim", "", "POD-sim", ""),
        "winter": ("zima", "", "SI-ma", ""),
        "luft": ("vzduch", "", "WSDUCH", ""),
        "feuer": ("oheň", "", "O-henj", ""),
        "sturm": ("bouře", "", "BOU-rzhe", ""),
        "regenbogen": ("duha", "", "DU-ha", ""),
        "feld": ("pole", "", "PO-le", ""),
        # beruf_bildung
        "lehrer": ("učitel", "", "U-tschi-tel", ""),
        "schueler": ("žák", "", "zhaak", ""),
        "buero": ("kancelář", "", "KAN-tse-laarzh", ""),
        "computer": ("počítač", "", "PO-tschii-tatsch", ""),
        "universitaet": ("univerzita", "", "u-ni-WER-si-ta", ""),
        "pruefung": ("zkouška", "", "SKOUSCH-ka", ""),
        "beruf": ("povolání", "", "po-wo-LAA-nii", ""),
        "chef": ("šéf", "", "schef", ""),
        "gehalt": ("plat", "", "plat", ""),
        "ingenieur": ("inženýr", "", "in-zhe-NIIR", ""),
        "rechtsanwalt": ("advokát", "", "ad-wo-KAAT", ""),
        "polizist": ("policista", "", "po-li-TSIS-ta", ""),
        "wissenschaft": ("věda", "", "WJE-da", ""),
        "mathematik": ("matematika", "", "ma-te-MA-ti-ka", ""),
        "geschichte": ("dějiny", "", "DJE-ji-ni", "Plural; historie also used"),
        "sprache_lang": ("jazyk", "", "JA-sik", "Also means tongue"),
        "bibliothek": ("knihovna", "", "KNI-how-na", ""),
        "klasse": ("třída", "", "TRZHII-da", ""),
        "studieren": ("studovat", "", "STU-do-wat", ""),
        "unterrichten": ("vyučovat", "", "WI-u-tscho-wat", ""),
        "aufgabe": ("úkol", "", "UU-kol", ""),
        "erfahrung": ("zkušenost", "", "SKU-she-nost", ""),
        "unternehmen": ("firma", "", "FIR-ma", "Or podnik"),
        "projekt": ("projekt", "", "PRO-jekt", ""),
        "meeting": ("porada", "", "PO-ra-da", ""),
    },

    # ================================================================
    # POLISH (pl) - Latin
    # ================================================================
    "pl": {
        # koerper_gesundheit
        "hand": ("ręka", "", "REN-ka", "ę = nasal e; also means arm"),
        "fuss": ("stopa", "", "STO-pa", "Foot specifically; noga = leg/foot"),
        "zahn": ("ząb", "", "zomp", "ą = nasal o"),
        "ohr": ("ucho", "", "U-cho", ""),
        "nase": ("nos", "", "nos", ""),
        "mund": ("usta", "", "U-sta", "Plural tantum"),
        "finger": ("palec", "", "PA-lets", ""),
        "ruecken": ("plecy", "", "PLEH-tsy", "Plural tantum"),
        "arm_body": ("ramię", "", "RA-mje", "ę = nasal e"),
        "bein": ("noga", "", "NO-ga", "Also means foot"),
        "haut": ("skóra", "", "SKOO-ra", "ó = u"),
        "blut": ("krew", "", "kref", ""),
        "knochen": ("kość", "", "koshtsh", "ś = soft sh"),
        "krankenhaus": ("szpital", "", "SCHPI-tal", ""),
        "medizin": ("lekarstwo", "", "le-KAR-stwo", ""),
        "krank": ("chory", "", "HO-ry", "ch = h"),
        "gesund": ("zdrowy", "", "SDRO-wy", ""),
        "bauch": ("brzuch", "", "bzhuch", ""),
        "arzt": ("lekarz", "", "LJE-kazh", ""),
        "schmerz": ("ból", "", "bul", "ó = u"),
        "fieber": ("gorączka", "", "go-RONTSCH-ka", ""),
        "husten": ("kaszel", "", "KA-schel", ""),
        "apotheke": ("apteka", "", "ap-TE-ka", ""),
        "zunge": ("język", "", "JEN-zyk", "ę = nasal e; also means language"),
        "schulter": ("ramię", "", "RA-mje", "Also means arm"),
        # essen_trinken
        "fleisch": ("mięso", "", "MJEN-so", "ę = nasal e"),
        "fisch": ("ryba", "", "RY-ba", ""),
        "reis": ("ryż", "", "rysh", "ż = zh"),
        "kaffee": ("kawa", "", "KA-wa", ""),
        "tee": ("herbata", "", "her-BA-ta", ""),
        "bier": ("piwo", "", "PI-wo", ""),
        "wein": ("wino", "", "WI-no", ""),
        "suppe": ("zupa", "", "SU-pa", ""),
        "gemuese": ("warzywa", "", "wa-ZHY-wa", "Plural"),
        "obst": ("owoce", "", "o-WO-tse", "Plural"),
        "ei": ("jajko", "", "JAI-ko", ""),
        "kaese": ("ser", "", "ser", ""),
        "zucker": ("cukier", "", "TSU-kjer", ""),
        "salz": ("sól", "", "sul", "ó = u"),
        "butter": ("masło", "", "MAS-wo", "ł = w"),
        "oel": ("olej", "", "O-lej", ""),
        "kartoffel": ("ziemniak", "", "ZJEM-njak", ""),
        "huhn": ("kurczak", "", "KUR-tschak", ""),
        "tomate": ("pomidor", "", "po-MI-dor", ""),
        "apfel": ("jabłko", "", "JAB-ko", "ł = w (silent almost)"),
        "kuchen": ("ciasto", "", "TSJAS-to", ""),
        "kochen": ("gotować", "", "go-TO-wach", ""),
        "restaurant": ("restauracja", "", "re-stau-RA-tsja", ""),
        "fruehstueck": ("śniadanie", "", "shnja-DA-nje", ""),
        "abendessen": ("kolacja", "", "ko-LA-tsja", ""),
        # natur_wetter
        "wald": ("las", "", "las", ""),
        "himmel": ("niebo", "", "NJE-bo", ""),
        "stern": ("gwiazda", "", "GWJAS-da", ""),
        "erde": ("ziemia", "", "ZJE-mja", ""),
        "wind": ("wiatr", "", "wjatr", ""),
        "wolke": ("chmura", "", "CHMU-ra", ""),
        "donner": ("grzmot", "", "GZHM-ot", ""),
        "insel": ("wyspa", "", "WYS-pa", ""),
        "see_lake": ("jezioro", "", "je-ZJO-ro", ""),
        "gras": ("trawa", "", "TRA-wa", ""),
        "stein": ("kamień", "", "KA-mjenj", ""),
        "sand": ("piasek", "", "PJA-sek", ""),
        "eis": ("lód", "", "lut", "ó = u"),
        "nebel": ("mgła", "", "MGWA", ""),
        "strand": ("plaża", "", "PLA-zha", ""),
        "wueste": ("pustynia", "", "pu-STY-nja", ""),
        "fruehling": ("wiosna", "", "WJOS-na", ""),
        "sommer": ("lato", "", "LA-to", ""),
        "herbst": ("jesień", "", "JE-sjenj", ""),
        "winter": ("zima", "", "ZI-ma", ""),
        "luft": ("powietrze", "", "po-WJE-tshe", ""),
        "feuer": ("ogień", "", "O-gjenj", ""),
        "sturm": ("burza", "", "BU-zha", ""),
        "regenbogen": ("tęcza", "", "TEN-tscha", "ę = nasal e"),
        "feld": ("pole", "", "PO-le", ""),
        # beruf_bildung
        "lehrer": ("nauczyciel", "", "nau-TSCHY-tsjel", ""),
        "schueler": ("uczeń", "", "U-tschenj", ""),
        "buero": ("biuro", "", "BJU-ro", ""),
        "computer": ("komputer", "", "kom-PU-ter", ""),
        "universitaet": ("uniwersytet", "", "u-ni-WER-sy-tet", ""),
        "pruefung": ("egzamin", "", "eg-ZA-min", ""),
        "beruf": ("zawód", "", "ZA-wut", "ó = u"),
        "chef": ("szef", "", "schef", ""),
        "gehalt": ("pensja", "", "PEN-sja", "Or wynagrodzenie"),
        "ingenieur": ("inżynier", "", "in-ZHY-njer", ""),
        "rechtsanwalt": ("adwokat", "", "ad-WO-kat", ""),
        "polizist": ("policjant", "", "po-LI-tsjant", ""),
        "wissenschaft": ("nauka", "", "NA-u-ka", ""),
        "mathematik": ("matematyka", "", "ma-te-MA-ty-ka", ""),
        "geschichte": ("historia", "", "hi-STOR-ja", ""),
        "sprache_lang": ("język", "", "JEN-zyk", "Also means tongue"),
        "bibliothek": ("biblioteka", "", "bi-bljo-TE-ka", ""),
        "klasse": ("klasa", "", "KLA-sa", ""),
        "studieren": ("studiować", "", "stu-DJO-wach", ""),
        "unterrichten": ("uczyć", "", "U-tschych", ""),
        "aufgabe": ("zadanie", "", "za-DA-nje", ""),
        "erfahrung": ("doświadczenie", "", "do-SCHWJAD-tsche-nje", ""),
        "unternehmen": ("firma", "", "FIR-ma", ""),
        "projekt": ("projekt", "", "PRO-jekt", ""),
        "meeting": ("spotkanie", "", "spot-KA-nje", "Or zebranie"),
    },

    # ================================================================
    # SLOVENIAN (sl) - Latin
    # ================================================================
    "sl": {
        # koerper_gesundheit
        "hand": ("roka", "", "RO-ka", "Also means arm"),
        "fuss": ("noga", "", "NO-ga", "Also means leg"),
        "zahn": ("zob", "", "zob", ""),
        "ohr": ("uho", "", "U-ho", ""),
        "nase": ("nos", "", "nos", ""),
        "mund": ("usta", "", "U-sta", "Plural tantum"),
        "finger": ("prst", "", "prst", ""),
        "ruecken": ("hrbet", "", "HER-bet", ""),
        "arm_body": ("roka", "", "RO-ka", "Same word as hand in Slovenian"),
        "bein": ("noga", "", "NO-ga", "Same word as foot in Slovenian"),
        "haut": ("koža", "", "KO-zha", ""),
        "blut": ("kri", "", "kri", ""),
        "knochen": ("kost", "", "kost", ""),
        "krankenhaus": ("bolnišnica", "", "bol-NISCH-ni-tsa", ""),
        "medizin": ("zdravilo", "", "SDRA-wi-lo", ""),
        "krank": ("bolan", "", "BO-lan", ""),
        "gesund": ("zdrav", "", "sdraw", ""),
        "bauch": ("trebuh", "", "TRE-buch", ""),
        "arzt": ("zdravnik", "", "SDRAW-nik", ""),
        "schmerz": ("bolečina", "", "bo-LE-tschi-na", ""),
        "fieber": ("vročina", "", "wro-TSCHI-na", ""),
        "husten": ("kašelj", "", "KA-schelj", ""),
        "apotheke": ("lekarna", "", "le-KAR-na", ""),
        "zunge": ("jezik", "", "JE-sik", "Also means language"),
        "schulter": ("rama", "", "RA-ma", ""),
        # essen_trinken
        "fleisch": ("meso", "", "ME-so", ""),
        "fisch": ("riba", "", "RI-ba", ""),
        "reis": ("riž", "", "rizh", ""),
        "kaffee": ("kava", "", "KA-wa", ""),
        "tee": ("čaj", "", "tschai", ""),
        "bier": ("pivo", "", "PI-wo", ""),
        "wein": ("vino", "", "WI-no", ""),
        "suppe": ("juha", "", "JU-ha", ""),
        "gemuese": ("zelenjava", "", "se-le-NJA-wa", ""),
        "obst": ("sadje", "", "SAD-je", ""),
        "ei": ("jajce", "", "JAI-tse", ""),
        "kaese": ("sir", "", "sir", ""),
        "zucker": ("sladkor", "", "SLAD-kor", ""),
        "salz": ("sol", "", "sol", ""),
        "butter": ("maslo", "", "MAS-lo", ""),
        "oel": ("olje", "", "OL-je", ""),
        "kartoffel": ("krompir", "", "KROM-pir", ""),
        "huhn": ("piščanec", "", "pisch-TSCHA-nets", ""),
        "tomate": ("paradižnik", "", "pa-ra-DIZH-nik", ""),
        "apfel": ("jabolko", "", "JA-bol-ko", ""),
        "kuchen": ("torta", "", "TOR-ta", ""),
        "kochen": ("kuhati", "", "KU-ha-ti", ""),
        "restaurant": ("restavracija", "", "re-staw-RA-tsi-ja", ""),
        "fruehstueck": ("zajtrk", "", "ZAI-trk", ""),
        "abendessen": ("večerja", "", "we-TSCHER-ja", ""),
        # natur_wetter
        "wald": ("gozd", "", "gosd", ""),
        "himmel": ("nebo", "", "NE-bo", ""),
        "stern": ("zvezda", "", "SWES-da", ""),
        "erde": ("zemlja", "", "SEM-lja", ""),
        "wind": ("veter", "", "WE-ter", ""),
        "wolke": ("oblak", "", "O-blak", ""),
        "donner": ("grom", "", "grom", ""),
        "insel": ("otok", "", "O-tok", ""),
        "see_lake": ("jezero", "", "je-SE-ro", ""),
        "gras": ("trava", "", "TRA-wa", ""),
        "stein": ("kamen", "", "KA-men", ""),
        "sand": ("pesek", "", "PE-sek", ""),
        "eis": ("led", "", "led", ""),
        "nebel": ("megla", "", "MEG-la", ""),
        "strand": ("plaža", "", "PLA-zha", ""),
        "wueste": ("puščava", "", "pusch-TSCHA-wa", ""),
        "fruehling": ("pomlad", "", "POM-lad", ""),
        "sommer": ("poletje", "", "po-LET-je", ""),
        "herbst": ("jesen", "", "JE-sen", ""),
        "winter": ("zima", "", "SI-ma", ""),
        "luft": ("zrak", "", "srak", ""),
        "feuer": ("ogenj", "", "O-genj", ""),
        "sturm": ("nevihta", "", "NE-wich-ta", ""),
        "regenbogen": ("mavrica", "", "MAW-ri-tsa", ""),
        "feld": ("polje", "", "POL-je", ""),
        # beruf_bildung
        "lehrer": ("učitelj", "", "u-TSCHI-telj", ""),
        "schueler": ("učenec", "", "u-TSCHE-nets", "Or dijak"),
        "buero": ("pisarna", "", "pi-SAR-na", ""),
        "computer": ("računalnik", "", "ra-tschu-NAL-nik", ""),
        "universitaet": ("univerza", "", "u-ni-WER-sa", ""),
        "pruefung": ("izpit", "", "IS-pit", ""),
        "beruf": ("poklic", "", "POK-lits", ""),
        "chef": ("šef", "", "schef", ""),
        "gehalt": ("plača", "", "PLA-tscha", ""),
        "ingenieur": ("inženir", "", "in-zhe-NIR", ""),
        "rechtsanwalt": ("odvetnik", "", "od-WET-nik", ""),
        "polizist": ("policist", "", "po-li-TSIST", ""),
        "wissenschaft": ("znanost", "", "SNA-nost", ""),
        "mathematik": ("matematika", "", "ma-te-MA-ti-ka", ""),
        "geschichte": ("zgodovina", "", "sgo-do-WI-na", ""),
        "sprache_lang": ("jezik", "", "JE-sik", "Also means tongue"),
        "bibliothek": ("knjižnica", "", "KNIZH-ni-tsa", ""),
        "klasse": ("razred", "", "RAS-red", ""),
        "studieren": ("študirati", "", "schtu-DI-ra-ti", ""),
        "unterrichten": ("poučevati", "", "po-u-TSCHE-wa-ti", ""),
        "aufgabe": ("naloga", "", "na-LO-ga", ""),
        "erfahrung": ("izkušnja", "", "is-KUSCH-nja", ""),
        "unternehmen": ("podjetje", "", "pod-JET-je", ""),
        "projekt": ("projekt", "", "pro-JEKT", ""),
        "meeting": ("sestanek", "", "se-STA-nek", ""),
    },

    # ================================================================
    # CROATIAN (hr) - Latin
    # ================================================================
    "hr": {
        # koerper_gesundheit
        "hand": ("ruka", "", "RU-ka", "Also means arm"),
        "fuss": ("stopalo", "", "sto-PA-lo", "Foot specifically"),
        "zahn": ("zub", "", "sub", ""),
        "ohr": ("uho", "", "U-ho", ""),
        "nase": ("nos", "", "nos", ""),
        "mund": ("usta", "", "U-sta", "Plural tantum"),
        "finger": ("prst", "", "prst", ""),
        "ruecken": ("leđa", "", "LE-dja", "đ = soft dj; plural tantum"),
        "arm_body": ("ruka", "", "RU-ka", "Same word as hand in Croatian"),
        "bein": ("noga", "", "NO-ga", "Also means foot"),
        "haut": ("koža", "", "KO-zha", ""),
        "blut": ("krv", "", "krw", ""),
        "knochen": ("kost", "", "kost", ""),
        "krankenhaus": ("bolnica", "", "BOL-ni-tsa", ""),
        "medizin": ("lijek", "", "LI-jek", ""),
        "krank": ("bolestan", "", "BO-le-stan", ""),
        "gesund": ("zdrav", "", "sdraw", ""),
        "bauch": ("trbuh", "", "TR-buch", ""),
        "arzt": ("liječnik", "", "LI-jetsch-nik", ""),
        "schmerz": ("bol", "", "bol", ""),
        "fieber": ("vrućica", "", "WRU-tschi-tsa", ""),
        "husten": ("kašalj", "", "KA-schalj", ""),
        "apotheke": ("ljekarna", "", "LJE-kar-na", ""),
        "zunge": ("jezik", "", "JE-zik", "Also means language"),
        "schulter": ("rame", "", "RA-me", ""),
        # essen_trinken
        "fleisch": ("meso", "", "ME-so", ""),
        "fisch": ("riba", "", "RI-ba", ""),
        "reis": ("riža", "", "RI-zha", ""),
        "kaffee": ("kava", "", "KA-wa", ""),
        "tee": ("čaj", "", "tschai", ""),
        "bier": ("pivo", "", "PI-wo", ""),
        "wein": ("vino", "", "WI-no", ""),
        "suppe": ("juha", "", "JU-ha", ""),
        "gemuese": ("povrće", "", "PO-wr-tsche", ""),
        "obst": ("voće", "", "WO-tsche", ""),
        "ei": ("jaje", "", "JA-je", ""),
        "kaese": ("sir", "", "sir", ""),
        "zucker": ("šećer", "", "SCHE-tscher", ""),
        "salz": ("sol", "", "sol", ""),
        "butter": ("maslac", "", "MAS-lats", ""),
        "oel": ("ulje", "", "UL-je", ""),
        "kartoffel": ("krumpir", "", "KRUM-pir", ""),
        "huhn": ("piletina", "", "pi-LE-ti-na", ""),
        "tomate": ("rajčica", "", "RAI-tschi-tsa", ""),
        "apfel": ("jabuka", "", "JA-bu-ka", ""),
        "kuchen": ("torta", "", "TOR-ta", ""),
        "kochen": ("kuhati", "", "KU-ha-ti", ""),
        "restaurant": ("restoran", "", "re-STO-ran", ""),
        "fruehstueck": ("doručak", "", "DO-ru-tschak", ""),
        "abendessen": ("večera", "", "WE-tsche-ra", ""),
        # natur_wetter
        "wald": ("šuma", "", "SCHU-ma", ""),
        "himmel": ("nebo", "", "NE-bo", ""),
        "stern": ("zvijezda", "", "SWI-jes-da", ""),
        "erde": ("zemlja", "", "SEM-lja", ""),
        "wind": ("vjetar", "", "WJEH-tar", ""),
        "wolke": ("oblak", "", "O-blak", ""),
        "donner": ("grom", "", "grom", ""),
        "insel": ("otok", "", "O-tok", ""),
        "see_lake": ("jezero", "", "JE-se-ro", ""),
        "gras": ("trava", "", "TRA-wa", ""),
        "stein": ("kamen", "", "KA-men", ""),
        "sand": ("pijesak", "", "PI-je-sak", ""),
        "eis": ("led", "", "led", ""),
        "nebel": ("magla", "", "MAG-la", ""),
        "strand": ("plaža", "", "PLA-zha", ""),
        "wueste": ("pustinja", "", "pu-STI-nja", ""),
        "fruehling": ("proljeće", "", "PRO-lje-tsche", ""),
        "sommer": ("ljeto", "", "LJE-to", ""),
        "herbst": ("jesen", "", "JE-sen", ""),
        "winter": ("zima", "", "SI-ma", ""),
        "luft": ("zrak", "", "srak", ""),
        "feuer": ("vatra", "", "WA-tra", ""),
        "sturm": ("oluja", "", "O-lu-ja", ""),
        "regenbogen": ("duga", "", "DU-ga", ""),
        "feld": ("polje", "", "POL-je", ""),
        # beruf_bildung
        "lehrer": ("učitelj", "", "u-TSCHI-telj", ""),
        "schueler": ("učenik", "", "u-TSCHE-nik", ""),
        "buero": ("ured", "", "U-red", ""),
        "computer": ("računalo", "", "ra-TSCHU-na-lo", ""),
        "universitaet": ("sveučilište", "", "swe-u-TSCHI-lisch-te", ""),
        "pruefung": ("ispit", "", "IS-pit", ""),
        "beruf": ("zanimanje", "", "za-ni-MA-nje", ""),
        "chef": ("šef", "", "schef", ""),
        "gehalt": ("plaća", "", "PLA-tscha", ""),
        "ingenieur": ("inženjer", "", "in-ZHEN-jer", ""),
        "rechtsanwalt": ("odvjetnik", "", "od-WJET-nik", ""),
        "polizist": ("policajac", "", "po-li-TSA-jats", ""),
        "wissenschaft": ("znanost", "", "SNA-nost", ""),
        "mathematik": ("matematika", "", "ma-te-MA-ti-ka", ""),
        "geschichte": ("povijest", "", "PO-wi-jest", ""),
        "sprache_lang": ("jezik", "", "JE-zik", "Also means tongue"),
        "bibliothek": ("knjižnica", "", "KNIZH-ni-tsa", ""),
        "klasse": ("razred", "", "RAS-red", ""),
        "studieren": ("studirati", "", "stu-DI-ra-ti", ""),
        "unterrichten": ("podučavati", "", "po-du-TSCHA-wa-ti", ""),
        "aufgabe": ("zadatak", "", "ZA-da-tak", ""),
        "erfahrung": ("iskustvo", "", "is-KU-stwo", ""),
        "unternehmen": ("tvrtka", "", "TWRT-ka", ""),
        "projekt": ("projekt", "", "PRO-jekt", ""),
        "meeting": ("sastanak", "", "SA-sta-nak", ""),
    },

    # ================================================================
    # BULGARIAN (bg) - Cyrillic
    # ================================================================
    "bg": {
        # koerper_gesundheit
        "hand": ("ръка", "rŭka", "ruh-KA", "Also means arm"),
        "fuss": ("крак", "krak", "krak", "Also means leg"),
        "zahn": ("зъб", "zŭb", "zuhb", ""),
        "ohr": ("ухо", "ukho", "U-cho", ""),
        "nase": ("нос", "nos", "nos", ""),
        "mund": ("уста", "usta", "u-STA", ""),
        "finger": ("пръст", "prŭst", "pruhst", ""),
        "ruecken": ("гръб", "grŭb", "gruhb", ""),
        "arm_body": ("ръка", "rŭka", "ruh-KA", "Same word as hand in Bulgarian"),
        "bein": ("крак", "krak", "krak", "Same word as foot in Bulgarian"),
        "haut": ("кожа", "kozha", "KO-zha", ""),
        "blut": ("кръв", "krŭv", "kruhw", ""),
        "knochen": ("кост", "kost", "kost", ""),
        "krankenhaus": ("болница", "bolnitsa", "bol-NI-tsa", ""),
        "medizin": ("лекарство", "lekarstvo", "le-KAR-stwo", ""),
        "krank": ("болен", "bolen", "BO-len", ""),
        "gesund": ("здрав", "zdrav", "sdraw", ""),
        "bauch": ("корем", "korem", "ko-REM", ""),
        "arzt": ("лекар", "lekar", "LE-kar", ""),
        "schmerz": ("болка", "bolka", "BOL-ka", ""),
        "fieber": ("треска", "treska", "TRES-ka", ""),
        "husten": ("кашлица", "kashlitsa", "kasch-LI-tsa", ""),
        "apotheke": ("аптека", "apteka", "ap-TE-ka", ""),
        "zunge": ("език", "ezik", "e-ZIK", "Also means language"),
        "schulter": ("рамо", "ramo", "ra-MO", ""),
        # essen_trinken
        "fleisch": ("месо", "meso", "me-SO", ""),
        "fisch": ("риба", "riba", "RI-ba", ""),
        "reis": ("ориз", "oriz", "o-RIS", ""),
        "kaffee": ("кафе", "kafe", "ka-FE", ""),
        "tee": ("чай", "chay", "tschai", ""),
        "bier": ("бира", "bira", "BI-ra", ""),
        "wein": ("вино", "vino", "wi-NO", ""),
        "suppe": ("супа", "supa", "SU-pa", ""),
        "gemuese": ("зеленчуци", "zelenchutsi", "se-len-TSCHU-tsi", ""),
        "obst": ("плодове", "plodove", "plo-DO-we", ""),
        "ei": ("яйце", "yaytse", "jaj-ZE", ""),
        "kaese": ("сирене", "sirene", "si-RE-ne", ""),
        "zucker": ("захар", "zakhar", "ZA-char", ""),
        "salz": ("сол", "sol", "sol", ""),
        "butter": ("масло", "maslo", "MAS-lo", ""),
        "oel": ("олио", "olio", "o-LI-o", ""),
        "kartoffel": ("картоф", "kartof", "kar-TOF", ""),
        "huhn": ("пиле", "pile", "pi-LE", ""),
        "tomate": ("домат", "domat", "do-MAT", ""),
        "apfel": ("ябълка", "yabŭlka", "JA-buhl-ka", ""),
        "kuchen": ("торта", "torta", "TOR-ta", ""),
        "kochen": ("готвя", "gotvya", "GOT-wja", ""),
        "restaurant": ("ресторант", "restorant", "re-sto-RANT", ""),
        "fruehstueck": ("закуска", "zakuska", "za-KU-ska", ""),
        "abendessen": ("вечеря", "vecherya", "we-TSCHE-rja", ""),
        # natur_wetter
        "wald": ("гора", "gora", "go-RA", "Also means mountain in some contexts"),
        "himmel": ("небе", "nebe", "NE-be", ""),
        "stern": ("звезда", "zvezda", "swez-DA", ""),
        "erde": ("земя", "zemya", "ze-MJA", ""),
        "wind": ("вятър", "vyatŭr", "WJA-tuhr", ""),
        "wolke": ("облак", "oblak", "O-blak", ""),
        "donner": ("гръм", "grŭm", "gruhm", ""),
        "insel": ("остров", "ostrov", "O-strow", ""),
        "see_lake": ("езеро", "ezero", "E-ze-ro", ""),
        "gras": ("трева", "treva", "tre-WA", ""),
        "stein": ("камък", "kamŭk", "KA-muhk", ""),
        "sand": ("пясък", "pyasŭk", "PJA-suhk", ""),
        "eis": ("лед", "led", "led", ""),
        "nebel": ("мъгла", "mŭgla", "muhg-LA", ""),
        "strand": ("плаж", "plazh", "plazh", ""),
        "wueste": ("пустиня", "pustinya", "pu-STI-nja", ""),
        "fruehling": ("пролет", "prolet", "pro-LET", ""),
        "sommer": ("лято", "lyato", "LJA-to", ""),
        "herbst": ("есен", "esen", "E-sen", ""),
        "winter": ("зима", "zima", "zi-MA", ""),
        "luft": ("въздух", "vŭzdukh", "wuhz-DUCH", ""),
        "feuer": ("огън", "ogŭn", "o-GUHN", ""),
        "sturm": ("буря", "burya", "BU-rja", ""),
        "regenbogen": ("дъга", "dŭga", "duh-GA", ""),
        "feld": ("поле", "pole", "PO-le", ""),
        # beruf_bildung
        "lehrer": ("учител", "uchitel", "u-TSCHI-tel", ""),
        "schueler": ("ученик", "uchenik", "u-tsche-NIK", ""),
        "buero": ("офис", "ofis", "O-fis", ""),
        "computer": ("компютър", "kompyutŭr", "kom-PJU-tuhr", ""),
        "universitaet": ("университет", "universitet", "u-ni-wer-si-TET", ""),
        "pruefung": ("изпит", "izpit", "IS-pit", ""),
        "beruf": ("професия", "profesiya", "pro-FE-si-ja", ""),
        "chef": ("шеф", "shef", "schef", ""),
        "gehalt": ("заплата", "zaplata", "za-PLA-ta", ""),
        "ingenieur": ("инженер", "inzhener", "in-zhe-NER", ""),
        "rechtsanwalt": ("адвокат", "advokat", "ad-wo-KAT", ""),
        "polizist": ("полицай", "politsay", "po-li-TSAJ", ""),
        "wissenschaft": ("наука", "nauka", "na-U-ka", ""),
        "mathematik": ("математика", "matematika", "ma-te-MA-ti-ka", ""),
        "geschichte": ("история", "istoriya", "is-TO-ri-ja", ""),
        "sprache_lang": ("език", "ezik", "e-ZIK", "Also means tongue"),
        "bibliothek": ("библиотека", "biblioteka", "bib-li-o-TE-ka", ""),
        "klasse": ("клас", "klas", "klas", ""),
        "studieren": ("уча", "ucha", "u-TSCHA", "Also means to learn"),
        "unterrichten": ("преподавам", "prepodavam", "pre-po-DA-wam", ""),
        "aufgabe": ("задача", "zadacha", "za-DA-tscha", ""),
        "erfahrung": ("опит", "opit", "O-pit", ""),
        "unternehmen": ("фирма", "firma", "FIR-ma", ""),
        "projekt": ("проект", "proekt", "pro-EKT", ""),
        "meeting": ("среща", "sreshta", "SRESCHT-a", ""),
    },

    # ================================================================
    # MACEDONIAN (mk) - Cyrillic
    # ================================================================
    "mk": {
        # koerper_gesundheit
        "hand": ("рака", "raka", "RA-ka", "Also means arm"),
        "fuss": ("нога", "noga", "NO-ga", "Also means leg"),
        "zahn": ("заб", "zab", "zab", ""),
        "ohr": ("уво", "uvo", "U-wo", ""),
        "nase": ("нос", "nos", "nos", ""),
        "mund": ("уста", "usta", "U-sta", ""),
        "finger": ("прст", "prst", "prst", ""),
        "ruecken": ("грб", "grb", "grb", ""),
        "arm_body": ("рака", "raka", "RA-ka", "Same word as hand in Macedonian"),
        "bein": ("нога", "noga", "NO-ga", "Same word as foot in Macedonian"),
        "haut": ("кожа", "kozha", "KO-zha", ""),
        "blut": ("крв", "krv", "krw", ""),
        "knochen": ("коска", "koska", "KOS-ka", ""),
        "krankenhaus": ("болница", "bolnitsa", "bol-NI-tsa", ""),
        "medizin": ("лек", "lek", "lek", ""),
        "krank": ("болен", "bolen", "BO-len", ""),
        "gesund": ("здрав", "zdrav", "sdraw", ""),
        "bauch": ("стомак", "stomak", "STO-mak", ""),
        "arzt": ("лекар", "lekar", "LE-kar", ""),
        "schmerz": ("болка", "bolka", "BOL-ka", ""),
        "fieber": ("температура", "temperatura", "tem-pe-ra-TU-ra", ""),
        "husten": ("кашлица", "kashlitsa", "kasch-LI-tsa", ""),
        "apotheke": ("аптека", "apteka", "ap-TE-ka", ""),
        "zunge": ("јазик", "jazik", "JA-zik", "Also means language"),
        "schulter": ("рамо", "ramo", "RA-mo", ""),
        # essen_trinken
        "fleisch": ("месо", "meso", "ME-so", ""),
        "fisch": ("риба", "riba", "RI-ba", ""),
        "reis": ("ориз", "oriz", "o-RIS", ""),
        "kaffee": ("кафе", "kafe", "ka-FE", ""),
        "tee": ("чај", "chaj", "tschai", ""),
        "bier": ("пиво", "pivo", "PI-wo", ""),
        "wein": ("вино", "vino", "WI-no", ""),
        "suppe": ("супа", "supa", "SU-pa", ""),
        "gemuese": ("зеленчук", "zelenchuk", "se-len-TSCHUK", ""),
        "obst": ("овошје", "ovoshje", "O-wosch-je", ""),
        "ei": ("јајце", "jajtse", "JAI-tse", ""),
        "kaese": ("сирење", "sirenje", "SI-re-nje", ""),
        "zucker": ("шеќер", "shekjer", "SCHE-kjer", "ќ = kj"),
        "salz": ("сол", "sol", "sol", ""),
        "butter": ("путер", "puter", "PU-ter", ""),
        "oel": ("масло", "maslo", "MAS-lo", ""),
        "kartoffel": ("компир", "kompir", "KOM-pir", ""),
        "huhn": ("пилешко", "pileshko", "PI-lesch-ko", ""),
        "tomate": ("домат", "domat", "do-MAT", ""),
        "apfel": ("јаболко", "jabolko", "JA-bol-ko", ""),
        "kuchen": ("торта", "torta", "TOR-ta", ""),
        "kochen": ("готви", "gotvi", "GOT-wi", ""),
        "restaurant": ("ресторан", "restoran", "re-sto-RAN", ""),
        "fruehstueck": ("појадок", "pojadok", "PO-ja-dok", ""),
        "abendessen": ("вечера", "vechera", "WE-tsche-ra", ""),
        # natur_wetter
        "wald": ("шума", "shuma", "SCHU-ma", ""),
        "himmel": ("небо", "nebo", "NE-bo", ""),
        "stern": ("ѕвезда", "dzvezda", "DZWES-da", "ѕ = dz"),
        "erde": ("земја", "zemja", "SEM-ja", ""),
        "wind": ("ветер", "veter", "WE-ter", ""),
        "wolke": ("облак", "oblak", "O-blak", ""),
        "donner": ("гром", "grom", "grom", ""),
        "insel": ("остров", "ostrov", "O-strow", ""),
        "see_lake": ("езеро", "ezero", "E-ze-ro", ""),
        "gras": ("трева", "treva", "TRE-wa", ""),
        "stein": ("камен", "kamen", "KA-men", ""),
        "sand": ("песок", "pesok", "PE-sok", ""),
        "eis": ("мраз", "mraz", "mras", "Also means frost"),
        "nebel": ("магла", "magla", "MAG-la", ""),
        "strand": ("плажа", "plazha", "PLA-zha", ""),
        "wueste": ("пустина", "pustina", "pu-STI-na", ""),
        "fruehling": ("пролет", "prolet", "PRO-let", ""),
        "sommer": ("лето", "leto", "LE-to", ""),
        "herbst": ("есен", "esen", "E-sen", ""),
        "winter": ("зима", "zima", "ZI-ma", ""),
        "luft": ("воздух", "vozdukh", "WOZ-duch", ""),
        "feuer": ("оган", "ogan", "O-gan", ""),
        "sturm": ("бура", "bura", "BU-ra", ""),
        "regenbogen": ("виножито", "vinozhito", "wi-no-ZHI-to", ""),
        "feld": ("поле", "pole", "PO-le", ""),
        # beruf_bildung
        "lehrer": ("наставник", "nastavnik", "na-STAW-nik", ""),
        "schueler": ("ученик", "uchenik", "u-TSCHE-nik", ""),
        "buero": ("канцеларија", "kantselarija", "kan-tse-LA-ri-ja", ""),
        "computer": ("компјутер", "kompjuter", "kom-PJU-ter", ""),
        "universitaet": ("универзитет", "univerzitet", "u-ni-wer-zi-TET", ""),
        "pruefung": ("испит", "ispit", "IS-pit", ""),
        "beruf": ("професија", "profesija", "pro-FE-si-ja", ""),
        "chef": ("шеф", "shef", "schef", ""),
        "gehalt": ("плата", "plata", "PLA-ta", ""),
        "ingenieur": ("инженер", "inzhener", "in-zhe-NER", ""),
        "rechtsanwalt": ("адвокат", "advokat", "ad-wo-KAT", ""),
        "polizist": ("полицаец", "politsaets", "po-li-TSA-ets", ""),
        "wissenschaft": ("наука", "nauka", "na-U-ka", ""),
        "mathematik": ("математика", "matematika", "ma-te-MA-ti-ka", ""),
        "geschichte": ("историја", "istorija", "is-TO-ri-ja", ""),
        "sprache_lang": ("јазик", "jazik", "JA-zik", "Also means tongue"),
        "bibliothek": ("библиотека", "biblioteka", "bib-li-o-TE-ka", ""),
        "klasse": ("клас", "klas", "klas", ""),
        "studieren": ("студира", "studira", "stu-DI-ra", ""),
        "unterrichten": ("предава", "predava", "pre-DA-wa", ""),
        "aufgabe": ("задача", "zadacha", "za-DA-tscha", ""),
        "erfahrung": ("искуство", "iskustvo", "is-KU-stwo", ""),
        "unternehmen": ("фирма", "firma", "FIR-ma", ""),
        "projekt": ("проект", "proekt", "pro-EKT", ""),
        "meeting": ("состанок", "sostanok", "so-STA-nok", ""),
    },
}


def build_entry(concept_id, meaning_de, meaning_en, category, frequency_rank,
                word, romanization, pronunciation_hint, notes):
    """Build a single word entry dict."""
    return {
        "word": word,
        "romanization": romanization,
        "pronunciation_hint": pronunciation_hint,
        "meaning_de": meaning_de,
        "meaning_en": meaning_en,
        "category": category,
        "frequency_rank": frequency_rank,
        "concept_id": concept_id,
        "tone": None,
        "notes": notes,
    }


def update_language_file(lang_id, lang_name):
    """Read existing JSON, append new entries, write back."""
    filepath = os.path.join(DATA_DIR, f"{lang_name}.json")

    if not os.path.exists(filepath):
        print(f"  SKIP: {filepath} not found")
        return

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Gather existing concept_ids
    existing_concepts = {w["concept_id"] for w in data["words"]}

    # Find max frequency_rank
    max_rank = max(w["frequency_rank"] for w in data["words"])

    lang_translations = TRANSLATIONS.get(lang_id)
    if lang_translations is None:
        print(f"  SKIP: No translations defined for {lang_id}")
        return

    added = 0
    rank = max_rank

    for category_name, category_words in ALL_CATEGORIES:
        for concept_id, meaning_de, meaning_en in category_words:
            if concept_id in existing_concepts:
                print(f"  SKIP existing concept '{concept_id}' in {lang_name}")
                continue

            if concept_id not in lang_translations:
                print(f"  WARNING: Missing translation for '{concept_id}' in {lang_id}")
                continue

            word, romanization, pronunciation_hint, notes = lang_translations[concept_id]
            rank += 1
            entry = build_entry(
                concept_id=concept_id,
                meaning_de=meaning_de,
                meaning_en=meaning_en,
                category=category_name,
                frequency_rank=rank,
                word=word,
                romanization=romanization,
                pronunciation_hint=pronunciation_hint,
                notes=notes,
            )
            data["words"].append(entry)
            existing_concepts.add(concept_id)
            added += 1

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"  {lang_name}.json: added {added} entries (ranks {max_rank+1}..{rank})")


if __name__ == "__main__":
    print("Generating Slavic vocabulary entries...")
    print(f"Data directory: {DATA_DIR}")
    print()
    for lang_id, filename in LANG_FILES.items():
        print(f"Processing {lang_id} ({filename})...")
        update_language_file(lang_id, filename)
    print()
    print("Done.")
